import { z } from 'zod';

const VoluntaryRetirementProcessSchema = z.object({
	voluntaryId: z.number().int().nonnegative(),
	certifierId: z.number().int().nonnegative().optional(),
	certifiedStatus: z.string().max(75).optional(),
	certifiedRemark: z.string().optional(),
	certifiedDate: z.string().datetime(),
	confirmerId: z.number().int().nonnegative().optional(),
	confirmedStatus: z.string().max(75).optional(),
	confirmedRemark: z.string().optional(),
	confirmedDate: z.string().datetime(),
	supporter1Id: z.number().int().nonnegative().optional(),
	supported1Status: z.string().max(75).optional(),
	supported1Remark: z.string().optional(),
	supported1Date: z.string().datetime(),
	supporter2Id: z.number().int().nonnegative().optional(),
	supported2Status: z.string().max(75).optional(),
	supported2Remark: z.string().optional(),
	supported2Date: z.string().datetime(),
	appointedApproverId: z.number().int().nonnegative().optional(),
	appointedApprovedStatus: z.string().max(75).optional(),
	appointedApprovedRemark: z.string().optional(),
	appointedApprovedDate: z.string().datetime(),
	secretaryApproverId: z.number().int().nonnegative().optional(),
	secretaryApprovedStatus: z.string().max(75).optional(),
	secretaryApprovedRemark: z.string().optional(),
	secretaryApprovedDate: z.string().datetime(),
	secretaryCertifierId: z.number().int().nonnegative().optional(),
	secretaryCertifiedStatus: z.string().max(75).optional(),
	secretaryCertifiedRemark: z.string().optional(),
	secretaryCertifiedDate: z.string().datetime(),
	active: z.boolean().optional(),
	createdBy: z.string().max(75).optional(),
	createdAt: z.date().optional(),
	modifiedBy: z.string().max(75).optional(),
	modifiedAt: z.date().optional(),
});

export default VoluntaryRetirementProcessSchema;