import BaseSeeder from '@ioc:Adonis/Lucid/Seeder';
import { DateTime } from 'luxon';
import { Faker, en } from '@faker-js/faker';
import ChecklistInterim from 'App/Models/ChecklistInterim';
import Employee from 'App/Models/Employee';
import Employee from 'App/Models/Employee';

export default class extends BaseSeeder {

	public async run () {
		const employees = await Employee.all();
		const employees = await Employee.all();
		const faker = new Faker({ locale: [en] });
		await ChecklistInterim.createMany([
			{
				preparerId: employees![Math.floor(Math.random() * 10)].id,
				checkerId: employees![Math.floor(Math.random() * 10)].id,
				applicationLetterStatus: true,
				applicationLetterCheck: true,
				certifiedFormStatus: true,
				certifiedFormCheck: true,
				organisationalChartStatus: true,
				organisationalChartCheck: true,
				jobDescriptionStatus: true,
				jobDescriptionCheck: true,
				orderLetterStatus: true,
				orderLetterCheck: true,
				leaveStatementStatus: true,
				leaveStatementCheck: true,
				documentListStatus: true,
				documentListCheck: true,
				justificationStatus: true,
				justificationCheck: true,
				active: true,
				createdBy: 'Admin'
			},
			{
				preparerId: employees![Math.floor(Math.random() * 10)].id,
				checkerId: employees![Math.floor(Math.random() * 10)].id,
				applicationLetterStatus: true,
				applicationLetterCheck: true,
				certifiedFormStatus: true,
				certifiedFormCheck: true,
				organisationalChartStatus: true,
				organisationalChartCheck: true,
				jobDescriptionStatus: true,
				jobDescriptionCheck: true,
				orderLetterStatus: true,
				orderLetterCheck: true,
				leaveStatementStatus: true,
				leaveStatementCheck: true,
				documentListStatus: true,
				documentListCheck: true,
				justificationStatus: true,
				justificationCheck: true,
				active: true,
				createdBy: 'Admin'
			},
			{
				preparerId: employees![Math.floor(Math.random() * 10)].id,
				checkerId: employees![Math.floor(Math.random() * 10)].id,
				applicationLetterStatus: true,
				applicationLetterCheck: true,
				certifiedFormStatus: true,
				certifiedFormCheck: true,
				organisationalChartStatus: true,
				organisationalChartCheck: true,
				jobDescriptionStatus: true,
				jobDescriptionCheck: true,
				orderLetterStatus: true,
				orderLetterCheck: true,
				leaveStatementStatus: true,
				leaveStatementCheck: true,
				documentListStatus: true,
				documentListCheck: true,
				justificationStatus: true,
				justificationCheck: true,
				active: true,
				createdBy: 'Admin'
			},
			{
				preparerId: employees![Math.floor(Math.random() * 10)].id,
				checkerId: employees![Math.floor(Math.random() * 10)].id,
				applicationLetterStatus: true,
				applicationLetterCheck: true,
				certifiedFormStatus: true,
				certifiedFormCheck: true,
				organisationalChartStatus: true,
				organisationalChartCheck: true,
				jobDescriptionStatus: true,
				jobDescriptionCheck: true,
				orderLetterStatus: true,
				orderLetterCheck: true,
				leaveStatementStatus: true,
				leaveStatementCheck: true,
				documentListStatus: true,
				documentListCheck: true,
				justificationStatus: true,
				justificationCheck: true,
				active: true,
				createdBy: 'Admin'
			},
			{
				preparerId: employees![Math.floor(Math.random() * 10)].id,
				checkerId: employees![Math.floor(Math.random() * 10)].id,
				applicationLetterStatus: true,
				applicationLetterCheck: true,
				certifiedFormStatus: true,
				certifiedFormCheck: true,
				organisationalChartStatus: true,
				organisationalChartCheck: true,
				jobDescriptionStatus: true,
				jobDescriptionCheck: true,
				orderLetterStatus: true,
				orderLetterCheck: true,
				leaveStatementStatus: true,
				leaveStatementCheck: true,
				documentListStatus: true,
				documentListCheck: true,
				justificationStatus: true,
				justificationCheck: true,
				active: true,
				createdBy: 'Admin'
			},
			{
				preparerId: employees![Math.floor(Math.random() * 10)].id,
				checkerId: employees![Math.floor(Math.random() * 10)].id,
				applicationLetterStatus: true,
				applicationLetterCheck: true,
				certifiedFormStatus: true,
				certifiedFormCheck: true,
				organisationalChartStatus: true,
				organisationalChartCheck: true,
				jobDescriptionStatus: true,
				jobDescriptionCheck: true,
				orderLetterStatus: true,
				orderLetterCheck: true,
				leaveStatementStatus: true,
				leaveStatementCheck: true,
				documentListStatus: true,
				documentListCheck: true,
				justificationStatus: true,
				justificationCheck: true,
				active: true,
				createdBy: 'Admin'
			},
			{
				preparerId: employees![Math.floor(Math.random() * 10)].id,
				checkerId: employees![Math.floor(Math.random() * 10)].id,
				applicationLetterStatus: true,
				applicationLetterCheck: true,
				certifiedFormStatus: true,
				certifiedFormCheck: true,
				organisationalChartStatus: true,
				organisationalChartCheck: true,
				jobDescriptionStatus: true,
				jobDescriptionCheck: true,
				orderLetterStatus: true,
				orderLetterCheck: true,
				leaveStatementStatus: true,
				leaveStatementCheck: true,
				documentListStatus: true,
				documentListCheck: true,
				justificationStatus: true,
				justificationCheck: true,
				active: true,
				createdBy: 'Admin'
			},
			{
				preparerId: employees![Math.floor(Math.random() * 10)].id,
				checkerId: employees![Math.floor(Math.random() * 10)].id,
				applicationLetterStatus: true,
				applicationLetterCheck: true,
				certifiedFormStatus: true,
				certifiedFormCheck: true,
				organisationalChartStatus: true,
				organisationalChartCheck: true,
				jobDescriptionStatus: true,
				jobDescriptionCheck: true,
				orderLetterStatus: true,
				orderLetterCheck: true,
				leaveStatementStatus: true,
				leaveStatementCheck: true,
				documentListStatus: true,
				documentListCheck: true,
				justificationStatus: true,
				justificationCheck: true,
				active: true,
				createdBy: 'Admin'
			},
			{
				preparerId: employees![Math.floor(Math.random() * 10)].id,
				checkerId: employees![Math.floor(Math.random() * 10)].id,
				applicationLetterStatus: true,
				applicationLetterCheck: true,
				certifiedFormStatus: true,
				certifiedFormCheck: true,
				organisationalChartStatus: true,
				organisationalChartCheck: true,
				jobDescriptionStatus: true,
				jobDescriptionCheck: true,
				orderLetterStatus: true,
				orderLetterCheck: true,
				leaveStatementStatus: true,
				leaveStatementCheck: true,
				documentListStatus: true,
				documentListCheck: true,
				justificationStatus: true,
				justificationCheck: true,
				active: true,
				createdBy: 'Admin'
			},
			{
				preparerId: employees![Math.floor(Math.random() * 10)].id,
				checkerId: employees![Math.floor(Math.random() * 10)].id,
				applicationLetterStatus: true,
				applicationLetterCheck: true,
				certifiedFormStatus: true,
				certifiedFormCheck: true,
				organisationalChartStatus: true,
				organisationalChartCheck: true,
				jobDescriptionStatus: true,
				jobDescriptionCheck: true,
				orderLetterStatus: true,
				orderLetterCheck: true,
				leaveStatementStatus: true,
				leaveStatementCheck: true,
				documentListStatus: true,
				documentListCheck: true,
				justificationStatus: true,
				justificationCheck: true,
				active: true,
				createdBy: 'Admin'
			},
		])
	}
}
