import BaseSeeder from '@ioc:Adonis/Lucid/Seeder';
import { DateTime } from 'luxon';
import { Faker, en } from '@faker-js/faker';
import WithoutPayLeaveProcess from 'App/Models/WithoutPayLeaveProcess';
import WithoutPayLeave from 'App/Models/WithoutPayLeave';
import Employee from 'App/Models/Employee';

export default class extends BaseSeeder {

	public async run () {
		const withoutPayLeaves = await WithoutPayLeave.all();
		const employees = await Employee.all();
		const faker = new Faker({ locale: [en] });
		await WithoutPayLeaveProcess.createMany([
			{
				withoutPayLeaveId: withoutPayLeaves![Math.floor(Math.random() * 10)].id,
				directorSupporterId: employees![Math.floor(Math.random() * 10)].id,
				directorSupportedStatus: faker.person.firstName(),
				directorSupportedRemark: faker.commerce.productDescription(),
				directorSupportedDate: DateTime.fromJSDate(faker.date.past()),
				verifierId: employees![Math.floor(Math.random() * 10)].id,
				verifiedStatus: faker.person.firstName(),
				verifiedRemark: faker.commerce.productDescription(),
				verifiedDate: DateTime.fromJSDate(faker.date.past()),
				confirmerId: employees![Math.floor(Math.random() * 10)].id,
				confirmedStatus: faker.person.firstName(),
				confirmedRemark: faker.commerce.productDescription(),
				confirmedDate: DateTime.fromJSDate(faker.date.past()),
				appointedSupporterId: employees![Math.floor(Math.random() * 10)].id,
				appointedSupportedStatus: faker.person.firstName(),
				appointedSupportedRemark: faker.commerce.productDescription(),
				appointedSupportedDate: DateTime.fromJSDate(faker.date.past()),
				approverId: employees![Math.floor(Math.random() * 10)].id,
				approvedStatus: faker.person.firstName(),
				approvedRemark: faker.commerce.productDescription(),
				approvedDate: DateTime.fromJSDate(faker.date.past()),
				meetingResult: faker.person.fullName(),
				meetingRemark: faker.person.fullName(),
				active: true,
				createdBy: 'Admin'
			},
			{
				withoutPayLeaveId: withoutPayLeaves![Math.floor(Math.random() * 10)].id,
				directorSupporterId: employees![Math.floor(Math.random() * 10)].id,
				directorSupportedStatus: faker.person.firstName(),
				directorSupportedRemark: faker.commerce.productDescription(),
				directorSupportedDate: DateTime.fromJSDate(faker.date.past()),
				verifierId: employees![Math.floor(Math.random() * 10)].id,
				verifiedStatus: faker.person.firstName(),
				verifiedRemark: faker.commerce.productDescription(),
				verifiedDate: DateTime.fromJSDate(faker.date.past()),
				confirmerId: employees![Math.floor(Math.random() * 10)].id,
				confirmedStatus: faker.person.firstName(),
				confirmedRemark: faker.commerce.productDescription(),
				confirmedDate: DateTime.fromJSDate(faker.date.past()),
				appointedSupporterId: employees![Math.floor(Math.random() * 10)].id,
				appointedSupportedStatus: faker.person.firstName(),
				appointedSupportedRemark: faker.commerce.productDescription(),
				appointedSupportedDate: DateTime.fromJSDate(faker.date.past()),
				approverId: employees![Math.floor(Math.random() * 10)].id,
				approvedStatus: faker.person.firstName(),
				approvedRemark: faker.commerce.productDescription(),
				approvedDate: DateTime.fromJSDate(faker.date.past()),
				meetingResult: faker.person.fullName(),
				meetingRemark: faker.person.fullName(),
				active: true,
				createdBy: 'Admin'
			},
			{
				withoutPayLeaveId: withoutPayLeaves![Math.floor(Math.random() * 10)].id,
				directorSupporterId: employees![Math.floor(Math.random() * 10)].id,
				directorSupportedStatus: faker.person.firstName(),
				directorSupportedRemark: faker.commerce.productDescription(),
				directorSupportedDate: DateTime.fromJSDate(faker.date.past()),
				verifierId: employees![Math.floor(Math.random() * 10)].id,
				verifiedStatus: faker.person.firstName(),
				verifiedRemark: faker.commerce.productDescription(),
				verifiedDate: DateTime.fromJSDate(faker.date.past()),
				confirmerId: employees![Math.floor(Math.random() * 10)].id,
				confirmedStatus: faker.person.firstName(),
				confirmedRemark: faker.commerce.productDescription(),
				confirmedDate: DateTime.fromJSDate(faker.date.past()),
				appointedSupporterId: employees![Math.floor(Math.random() * 10)].id,
				appointedSupportedStatus: faker.person.firstName(),
				appointedSupportedRemark: faker.commerce.productDescription(),
				appointedSupportedDate: DateTime.fromJSDate(faker.date.past()),
				approverId: employees![Math.floor(Math.random() * 10)].id,
				approvedStatus: faker.person.firstName(),
				approvedRemark: faker.commerce.productDescription(),
				approvedDate: DateTime.fromJSDate(faker.date.past()),
				meetingResult: faker.person.fullName(),
				meetingRemark: faker.person.fullName(),
				active: true,
				createdBy: 'Admin'
			},
			{
				withoutPayLeaveId: withoutPayLeaves![Math.floor(Math.random() * 10)].id,
				directorSupporterId: employees![Math.floor(Math.random() * 10)].id,
				directorSupportedStatus: faker.person.firstName(),
				directorSupportedRemark: faker.commerce.productDescription(),
				directorSupportedDate: DateTime.fromJSDate(faker.date.past()),
				verifierId: employees![Math.floor(Math.random() * 10)].id,
				verifiedStatus: faker.person.firstName(),
				verifiedRemark: faker.commerce.productDescription(),
				verifiedDate: DateTime.fromJSDate(faker.date.past()),
				confirmerId: employees![Math.floor(Math.random() * 10)].id,
				confirmedStatus: faker.person.firstName(),
				confirmedRemark: faker.commerce.productDescription(),
				confirmedDate: DateTime.fromJSDate(faker.date.past()),
				appointedSupporterId: employees![Math.floor(Math.random() * 10)].id,
				appointedSupportedStatus: faker.person.firstName(),
				appointedSupportedRemark: faker.commerce.productDescription(),
				appointedSupportedDate: DateTime.fromJSDate(faker.date.past()),
				approverId: employees![Math.floor(Math.random() * 10)].id,
				approvedStatus: faker.person.firstName(),
				approvedRemark: faker.commerce.productDescription(),
				approvedDate: DateTime.fromJSDate(faker.date.past()),
				meetingResult: faker.person.fullName(),
				meetingRemark: faker.person.fullName(),
				active: true,
				createdBy: 'Admin'
			},
			{
				withoutPayLeaveId: withoutPayLeaves![Math.floor(Math.random() * 10)].id,
				directorSupporterId: employees![Math.floor(Math.random() * 10)].id,
				directorSupportedStatus: faker.person.firstName(),
				directorSupportedRemark: faker.commerce.productDescription(),
				directorSupportedDate: DateTime.fromJSDate(faker.date.past()),
				verifierId: employees![Math.floor(Math.random() * 10)].id,
				verifiedStatus: faker.person.firstName(),
				verifiedRemark: faker.commerce.productDescription(),
				verifiedDate: DateTime.fromJSDate(faker.date.past()),
				confirmerId: employees![Math.floor(Math.random() * 10)].id,
				confirmedStatus: faker.person.firstName(),
				confirmedRemark: faker.commerce.productDescription(),
				confirmedDate: DateTime.fromJSDate(faker.date.past()),
				appointedSupporterId: employees![Math.floor(Math.random() * 10)].id,
				appointedSupportedStatus: faker.person.firstName(),
				appointedSupportedRemark: faker.commerce.productDescription(),
				appointedSupportedDate: DateTime.fromJSDate(faker.date.past()),
				approverId: employees![Math.floor(Math.random() * 10)].id,
				approvedStatus: faker.person.firstName(),
				approvedRemark: faker.commerce.productDescription(),
				approvedDate: DateTime.fromJSDate(faker.date.past()),
				meetingResult: faker.person.fullName(),
				meetingRemark: faker.person.fullName(),
				active: true,
				createdBy: 'Admin'
			},
			{
				withoutPayLeaveId: withoutPayLeaves![Math.floor(Math.random() * 10)].id,
				directorSupporterId: employees![Math.floor(Math.random() * 10)].id,
				directorSupportedStatus: faker.person.firstName(),
				directorSupportedRemark: faker.commerce.productDescription(),
				directorSupportedDate: DateTime.fromJSDate(faker.date.past()),
				verifierId: employees![Math.floor(Math.random() * 10)].id,
				verifiedStatus: faker.person.firstName(),
				verifiedRemark: faker.commerce.productDescription(),
				verifiedDate: DateTime.fromJSDate(faker.date.past()),
				confirmerId: employees![Math.floor(Math.random() * 10)].id,
				confirmedStatus: faker.person.firstName(),
				confirmedRemark: faker.commerce.productDescription(),
				confirmedDate: DateTime.fromJSDate(faker.date.past()),
				appointedSupporterId: employees![Math.floor(Math.random() * 10)].id,
				appointedSupportedStatus: faker.person.firstName(),
				appointedSupportedRemark: faker.commerce.productDescription(),
				appointedSupportedDate: DateTime.fromJSDate(faker.date.past()),
				approverId: employees![Math.floor(Math.random() * 10)].id,
				approvedStatus: faker.person.firstName(),
				approvedRemark: faker.commerce.productDescription(),
				approvedDate: DateTime.fromJSDate(faker.date.past()),
				meetingResult: faker.person.fullName(),
				meetingRemark: faker.person.fullName(),
				active: true,
				createdBy: 'Admin'
			},
			{
				withoutPayLeaveId: withoutPayLeaves![Math.floor(Math.random() * 10)].id,
				directorSupporterId: employees![Math.floor(Math.random() * 10)].id,
				directorSupportedStatus: faker.person.firstName(),
				directorSupportedRemark: faker.commerce.productDescription(),
				directorSupportedDate: DateTime.fromJSDate(faker.date.past()),
				verifierId: employees![Math.floor(Math.random() * 10)].id,
				verifiedStatus: faker.person.firstName(),
				verifiedRemark: faker.commerce.productDescription(),
				verifiedDate: DateTime.fromJSDate(faker.date.past()),
				confirmerId: employees![Math.floor(Math.random() * 10)].id,
				confirmedStatus: faker.person.firstName(),
				confirmedRemark: faker.commerce.productDescription(),
				confirmedDate: DateTime.fromJSDate(faker.date.past()),
				appointedSupporterId: employees![Math.floor(Math.random() * 10)].id,
				appointedSupportedStatus: faker.person.firstName(),
				appointedSupportedRemark: faker.commerce.productDescription(),
				appointedSupportedDate: DateTime.fromJSDate(faker.date.past()),
				approverId: employees![Math.floor(Math.random() * 10)].id,
				approvedStatus: faker.person.firstName(),
				approvedRemark: faker.commerce.productDescription(),
				approvedDate: DateTime.fromJSDate(faker.date.past()),
				meetingResult: faker.person.fullName(),
				meetingRemark: faker.person.fullName(),
				active: true,
				createdBy: 'Admin'
			},
			{
				withoutPayLeaveId: withoutPayLeaves![Math.floor(Math.random() * 10)].id,
				directorSupporterId: employees![Math.floor(Math.random() * 10)].id,
				directorSupportedStatus: faker.person.firstName(),
				directorSupportedRemark: faker.commerce.productDescription(),
				directorSupportedDate: DateTime.fromJSDate(faker.date.past()),
				verifierId: employees![Math.floor(Math.random() * 10)].id,
				verifiedStatus: faker.person.firstName(),
				verifiedRemark: faker.commerce.productDescription(),
				verifiedDate: DateTime.fromJSDate(faker.date.past()),
				confirmerId: employees![Math.floor(Math.random() * 10)].id,
				confirmedStatus: faker.person.firstName(),
				confirmedRemark: faker.commerce.productDescription(),
				confirmedDate: DateTime.fromJSDate(faker.date.past()),
				appointedSupporterId: employees![Math.floor(Math.random() * 10)].id,
				appointedSupportedStatus: faker.person.firstName(),
				appointedSupportedRemark: faker.commerce.productDescription(),
				appointedSupportedDate: DateTime.fromJSDate(faker.date.past()),
				approverId: employees![Math.floor(Math.random() * 10)].id,
				approvedStatus: faker.person.firstName(),
				approvedRemark: faker.commerce.productDescription(),
				approvedDate: DateTime.fromJSDate(faker.date.past()),
				meetingResult: faker.person.fullName(),
				meetingRemark: faker.person.fullName(),
				active: true,
				createdBy: 'Admin'
			},
			{
				withoutPayLeaveId: withoutPayLeaves![Math.floor(Math.random() * 10)].id,
				directorSupporterId: employees![Math.floor(Math.random() * 10)].id,
				directorSupportedStatus: faker.person.firstName(),
				directorSupportedRemark: faker.commerce.productDescription(),
				directorSupportedDate: DateTime.fromJSDate(faker.date.past()),
				verifierId: employees![Math.floor(Math.random() * 10)].id,
				verifiedStatus: faker.person.firstName(),
				verifiedRemark: faker.commerce.productDescription(),
				verifiedDate: DateTime.fromJSDate(faker.date.past()),
				confirmerId: employees![Math.floor(Math.random() * 10)].id,
				confirmedStatus: faker.person.firstName(),
				confirmedRemark: faker.commerce.productDescription(),
				confirmedDate: DateTime.fromJSDate(faker.date.past()),
				appointedSupporterId: employees![Math.floor(Math.random() * 10)].id,
				appointedSupportedStatus: faker.person.firstName(),
				appointedSupportedRemark: faker.commerce.productDescription(),
				appointedSupportedDate: DateTime.fromJSDate(faker.date.past()),
				approverId: employees![Math.floor(Math.random() * 10)].id,
				approvedStatus: faker.person.firstName(),
				approvedRemark: faker.commerce.productDescription(),
				approvedDate: DateTime.fromJSDate(faker.date.past()),
				meetingResult: faker.person.fullName(),
				meetingRemark: faker.person.fullName(),
				active: true,
				createdBy: 'Admin'
			},
			{
				withoutPayLeaveId: withoutPayLeaves![Math.floor(Math.random() * 10)].id,
				directorSupporterId: employees![Math.floor(Math.random() * 10)].id,
				directorSupportedStatus: faker.person.firstName(),
				directorSupportedRemark: faker.commerce.productDescription(),
				directorSupportedDate: DateTime.fromJSDate(faker.date.past()),
				verifierId: employees![Math.floor(Math.random() * 10)].id,
				verifiedStatus: faker.person.firstName(),
				verifiedRemark: faker.commerce.productDescription(),
				verifiedDate: DateTime.fromJSDate(faker.date.past()),
				confirmerId: employees![Math.floor(Math.random() * 10)].id,
				confirmedStatus: faker.person.firstName(),
				confirmedRemark: faker.commerce.productDescription(),
				confirmedDate: DateTime.fromJSDate(faker.date.past()),
				appointedSupporterId: employees![Math.floor(Math.random() * 10)].id,
				appointedSupportedStatus: faker.person.firstName(),
				appointedSupportedRemark: faker.commerce.productDescription(),
				appointedSupportedDate: DateTime.fromJSDate(faker.date.past()),
				approverId: employees![Math.floor(Math.random() * 10)].id,
				approvedStatus: faker.person.firstName(),
				approvedRemark: faker.commerce.productDescription(),
				approvedDate: DateTime.fromJSDate(faker.date.past()),
				meetingResult: faker.person.fullName(),
				meetingRemark: faker.person.fullName(),
				active: true,
				createdBy: 'Admin'
			},
		])
	}
}
