import BaseSeeder from '@ioc:Adonis/Lucid/Seeder';
import { DateTime } from 'luxon';
import { Faker, en } from '@faker-js/faker';
import GradeActingTypesProcess from 'App/Models/GradeActingTypesProcess';
import GradeActingType from 'App/Models/GradeActingType';
import Employee from 'App/Models/Employee';

export default class extends BaseSeeder {

	public async run () {
		const gradeActingTypes = await GradeActingType.all();
		const employees = await Employee.all();
		const faker = new Faker({ locale: [en] });
		await GradeActingTypesProcess.createMany([
			{
				actingId: gradeActingTypes![Math.floor(Math.random() * 10)].id,
				integrityCertifierId: employees![Math.floor(Math.random() * 10)].id,
				integrityCertifiedStatus: faker.person.firstName(),
				integrityCertifiedRemark: faker.commerce.productDescription(),
				integrityCertifiedDate: DateTime.fromJSDate(faker.date.past()),
				directorCertifierId: employees![Math.floor(Math.random() * 10)].id,
				directorCertifiedStatus: faker.person.firstName(),
				directorCertifiedRemark: faker.commerce.productDescription(),
				directorCertifiedDate: DateTime.fromJSDate(faker.date.past()),
				supporterId: employees![Math.floor(Math.random() * 10)].id,
				supportedStatus: faker.person.firstName(),
				supportedRemark: faker.commerce.productDescription(),
				supportedDate: DateTime.fromJSDate(faker.date.past()),
				approverId: employees![Math.floor(Math.random() * 10)].id,
				approvedStatus: faker.person.firstName(),
				approvedRemark: faker.commerce.productDescription(),
				approvedDate: DateTime.fromJSDate(faker.date.past()),
				active: true,
				createdBy: 'Admin'
			},
			{
				actingId: gradeActingTypes![Math.floor(Math.random() * 10)].id,
				integrityCertifierId: employees![Math.floor(Math.random() * 10)].id,
				integrityCertifiedStatus: faker.person.firstName(),
				integrityCertifiedRemark: faker.commerce.productDescription(),
				integrityCertifiedDate: DateTime.fromJSDate(faker.date.past()),
				directorCertifierId: employees![Math.floor(Math.random() * 10)].id,
				directorCertifiedStatus: faker.person.firstName(),
				directorCertifiedRemark: faker.commerce.productDescription(),
				directorCertifiedDate: DateTime.fromJSDate(faker.date.past()),
				supporterId: employees![Math.floor(Math.random() * 10)].id,
				supportedStatus: faker.person.firstName(),
				supportedRemark: faker.commerce.productDescription(),
				supportedDate: DateTime.fromJSDate(faker.date.past()),
				approverId: employees![Math.floor(Math.random() * 10)].id,
				approvedStatus: faker.person.firstName(),
				approvedRemark: faker.commerce.productDescription(),
				approvedDate: DateTime.fromJSDate(faker.date.past()),
				active: true,
				createdBy: 'Admin'
			},
			{
				actingId: gradeActingTypes![Math.floor(Math.random() * 10)].id,
				integrityCertifierId: employees![Math.floor(Math.random() * 10)].id,
				integrityCertifiedStatus: faker.person.firstName(),
				integrityCertifiedRemark: faker.commerce.productDescription(),
				integrityCertifiedDate: DateTime.fromJSDate(faker.date.past()),
				directorCertifierId: employees![Math.floor(Math.random() * 10)].id,
				directorCertifiedStatus: faker.person.firstName(),
				directorCertifiedRemark: faker.commerce.productDescription(),
				directorCertifiedDate: DateTime.fromJSDate(faker.date.past()),
				supporterId: employees![Math.floor(Math.random() * 10)].id,
				supportedStatus: faker.person.firstName(),
				supportedRemark: faker.commerce.productDescription(),
				supportedDate: DateTime.fromJSDate(faker.date.past()),
				approverId: employees![Math.floor(Math.random() * 10)].id,
				approvedStatus: faker.person.firstName(),
				approvedRemark: faker.commerce.productDescription(),
				approvedDate: DateTime.fromJSDate(faker.date.past()),
				active: true,
				createdBy: 'Admin'
			},
			{
				actingId: gradeActingTypes![Math.floor(Math.random() * 10)].id,
				integrityCertifierId: employees![Math.floor(Math.random() * 10)].id,
				integrityCertifiedStatus: faker.person.firstName(),
				integrityCertifiedRemark: faker.commerce.productDescription(),
				integrityCertifiedDate: DateTime.fromJSDate(faker.date.past()),
				directorCertifierId: employees![Math.floor(Math.random() * 10)].id,
				directorCertifiedStatus: faker.person.firstName(),
				directorCertifiedRemark: faker.commerce.productDescription(),
				directorCertifiedDate: DateTime.fromJSDate(faker.date.past()),
				supporterId: employees![Math.floor(Math.random() * 10)].id,
				supportedStatus: faker.person.firstName(),
				supportedRemark: faker.commerce.productDescription(),
				supportedDate: DateTime.fromJSDate(faker.date.past()),
				approverId: employees![Math.floor(Math.random() * 10)].id,
				approvedStatus: faker.person.firstName(),
				approvedRemark: faker.commerce.productDescription(),
				approvedDate: DateTime.fromJSDate(faker.date.past()),
				active: true,
				createdBy: 'Admin'
			},
			{
				actingId: gradeActingTypes![Math.floor(Math.random() * 10)].id,
				integrityCertifierId: employees![Math.floor(Math.random() * 10)].id,
				integrityCertifiedStatus: faker.person.firstName(),
				integrityCertifiedRemark: faker.commerce.productDescription(),
				integrityCertifiedDate: DateTime.fromJSDate(faker.date.past()),
				directorCertifierId: employees![Math.floor(Math.random() * 10)].id,
				directorCertifiedStatus: faker.person.firstName(),
				directorCertifiedRemark: faker.commerce.productDescription(),
				directorCertifiedDate: DateTime.fromJSDate(faker.date.past()),
				supporterId: employees![Math.floor(Math.random() * 10)].id,
				supportedStatus: faker.person.firstName(),
				supportedRemark: faker.commerce.productDescription(),
				supportedDate: DateTime.fromJSDate(faker.date.past()),
				approverId: employees![Math.floor(Math.random() * 10)].id,
				approvedStatus: faker.person.firstName(),
				approvedRemark: faker.commerce.productDescription(),
				approvedDate: DateTime.fromJSDate(faker.date.past()),
				active: true,
				createdBy: 'Admin'
			},
			{
				actingId: gradeActingTypes![Math.floor(Math.random() * 10)].id,
				integrityCertifierId: employees![Math.floor(Math.random() * 10)].id,
				integrityCertifiedStatus: faker.person.firstName(),
				integrityCertifiedRemark: faker.commerce.productDescription(),
				integrityCertifiedDate: DateTime.fromJSDate(faker.date.past()),
				directorCertifierId: employees![Math.floor(Math.random() * 10)].id,
				directorCertifiedStatus: faker.person.firstName(),
				directorCertifiedRemark: faker.commerce.productDescription(),
				directorCertifiedDate: DateTime.fromJSDate(faker.date.past()),
				supporterId: employees![Math.floor(Math.random() * 10)].id,
				supportedStatus: faker.person.firstName(),
				supportedRemark: faker.commerce.productDescription(),
				supportedDate: DateTime.fromJSDate(faker.date.past()),
				approverId: employees![Math.floor(Math.random() * 10)].id,
				approvedStatus: faker.person.firstName(),
				approvedRemark: faker.commerce.productDescription(),
				approvedDate: DateTime.fromJSDate(faker.date.past()),
				active: true,
				createdBy: 'Admin'
			},
			{
				actingId: gradeActingTypes![Math.floor(Math.random() * 10)].id,
				integrityCertifierId: employees![Math.floor(Math.random() * 10)].id,
				integrityCertifiedStatus: faker.person.firstName(),
				integrityCertifiedRemark: faker.commerce.productDescription(),
				integrityCertifiedDate: DateTime.fromJSDate(faker.date.past()),
				directorCertifierId: employees![Math.floor(Math.random() * 10)].id,
				directorCertifiedStatus: faker.person.firstName(),
				directorCertifiedRemark: faker.commerce.productDescription(),
				directorCertifiedDate: DateTime.fromJSDate(faker.date.past()),
				supporterId: employees![Math.floor(Math.random() * 10)].id,
				supportedStatus: faker.person.firstName(),
				supportedRemark: faker.commerce.productDescription(),
				supportedDate: DateTime.fromJSDate(faker.date.past()),
				approverId: employees![Math.floor(Math.random() * 10)].id,
				approvedStatus: faker.person.firstName(),
				approvedRemark: faker.commerce.productDescription(),
				approvedDate: DateTime.fromJSDate(faker.date.past()),
				active: true,
				createdBy: 'Admin'
			},
			{
				actingId: gradeActingTypes![Math.floor(Math.random() * 10)].id,
				integrityCertifierId: employees![Math.floor(Math.random() * 10)].id,
				integrityCertifiedStatus: faker.person.firstName(),
				integrityCertifiedRemark: faker.commerce.productDescription(),
				integrityCertifiedDate: DateTime.fromJSDate(faker.date.past()),
				directorCertifierId: employees![Math.floor(Math.random() * 10)].id,
				directorCertifiedStatus: faker.person.firstName(),
				directorCertifiedRemark: faker.commerce.productDescription(),
				directorCertifiedDate: DateTime.fromJSDate(faker.date.past()),
				supporterId: employees![Math.floor(Math.random() * 10)].id,
				supportedStatus: faker.person.firstName(),
				supportedRemark: faker.commerce.productDescription(),
				supportedDate: DateTime.fromJSDate(faker.date.past()),
				approverId: employees![Math.floor(Math.random() * 10)].id,
				approvedStatus: faker.person.firstName(),
				approvedRemark: faker.commerce.productDescription(),
				approvedDate: DateTime.fromJSDate(faker.date.past()),
				active: true,
				createdBy: 'Admin'
			},
			{
				actingId: gradeActingTypes![Math.floor(Math.random() * 10)].id,
				integrityCertifierId: employees![Math.floor(Math.random() * 10)].id,
				integrityCertifiedStatus: faker.person.firstName(),
				integrityCertifiedRemark: faker.commerce.productDescription(),
				integrityCertifiedDate: DateTime.fromJSDate(faker.date.past()),
				directorCertifierId: employees![Math.floor(Math.random() * 10)].id,
				directorCertifiedStatus: faker.person.firstName(),
				directorCertifiedRemark: faker.commerce.productDescription(),
				directorCertifiedDate: DateTime.fromJSDate(faker.date.past()),
				supporterId: employees![Math.floor(Math.random() * 10)].id,
				supportedStatus: faker.person.firstName(),
				supportedRemark: faker.commerce.productDescription(),
				supportedDate: DateTime.fromJSDate(faker.date.past()),
				approverId: employees![Math.floor(Math.random() * 10)].id,
				approvedStatus: faker.person.firstName(),
				approvedRemark: faker.commerce.productDescription(),
				approvedDate: DateTime.fromJSDate(faker.date.past()),
				active: true,
				createdBy: 'Admin'
			},
			{
				actingId: gradeActingTypes![Math.floor(Math.random() * 10)].id,
				integrityCertifierId: employees![Math.floor(Math.random() * 10)].id,
				integrityCertifiedStatus: faker.person.firstName(),
				integrityCertifiedRemark: faker.commerce.productDescription(),
				integrityCertifiedDate: DateTime.fromJSDate(faker.date.past()),
				directorCertifierId: employees![Math.floor(Math.random() * 10)].id,
				directorCertifiedStatus: faker.person.firstName(),
				directorCertifiedRemark: faker.commerce.productDescription(),
				directorCertifiedDate: DateTime.fromJSDate(faker.date.past()),
				supporterId: employees![Math.floor(Math.random() * 10)].id,
				supportedStatus: faker.person.firstName(),
				supportedRemark: faker.commerce.productDescription(),
				supportedDate: DateTime.fromJSDate(faker.date.past()),
				approverId: employees![Math.floor(Math.random() * 10)].id,
				approvedStatus: faker.person.firstName(),
				approvedRemark: faker.commerce.productDescription(),
				approvedDate: DateTime.fromJSDate(faker.date.past()),
				active: true,
				createdBy: 'Admin'
			},
		])
	}
}
