import BaseSeeder from '@ioc:Adonis/Lucid/Seeder';
import { DateTime } from 'luxon';
import { Faker, en } from '@faker-js/faker';
import FundApplicationProcess from 'App/Models/FundApplicationProcess';
import EducationFundApplication from 'App/Models/EducationFundApplication';
import Employee from 'App/Models/Employee';

export default class extends BaseSeeder {

	public async run () {
		const educationFundApplications = await EducationFundApplication.all();
		const employees = await Employee.all();
		const faker = new Faker({ locale: [en] });
		await FundApplicationProcess.createMany([
			{
				fundId: educationFundApplications![Math.floor(Math.random() * 10)].id,
				supporterId: employees![Math.floor(Math.random() * 10)].id,
				supportedStatus: faker.person.firstName(),
				supportedRemark: faker.commerce.productDescription(),
				supportedDate: DateTime.fromJSDate(faker.date.past()),
				certifierId: employees![Math.floor(Math.random() * 10)].id,
				certifiedStatus: faker.person.firstName(),
				certifiedRemark: faker.commerce.productDescription(),
				certifiedDate: DateTime.fromJSDate(faker.date.past()),
				confirmerId: employees![Math.floor(Math.random() * 10)].id,
				confirmedStatus: faker.person.firstName(),
				confirmedRemark: faker.commerce.productDescription(),
				confirmedDate: DateTime.fromJSDate(faker.date.past()),
				verifierId: employees![Math.floor(Math.random() * 10)].id,
				verifiedStatus: faker.person.firstName(),
				verifiedRemark: faker.commerce.productDescription(),
				verifiedDate: DateTime.fromJSDate(faker.date.past()),
				active: true,
				createdBy: 'Admin'
			},
			{
				fundId: educationFundApplications![Math.floor(Math.random() * 10)].id,
				supporterId: employees![Math.floor(Math.random() * 10)].id,
				supportedStatus: faker.person.firstName(),
				supportedRemark: faker.commerce.productDescription(),
				supportedDate: DateTime.fromJSDate(faker.date.past()),
				certifierId: employees![Math.floor(Math.random() * 10)].id,
				certifiedStatus: faker.person.firstName(),
				certifiedRemark: faker.commerce.productDescription(),
				certifiedDate: DateTime.fromJSDate(faker.date.past()),
				confirmerId: employees![Math.floor(Math.random() * 10)].id,
				confirmedStatus: faker.person.firstName(),
				confirmedRemark: faker.commerce.productDescription(),
				confirmedDate: DateTime.fromJSDate(faker.date.past()),
				verifierId: employees![Math.floor(Math.random() * 10)].id,
				verifiedStatus: faker.person.firstName(),
				verifiedRemark: faker.commerce.productDescription(),
				verifiedDate: DateTime.fromJSDate(faker.date.past()),
				active: true,
				createdBy: 'Admin'
			},
			{
				fundId: educationFundApplications![Math.floor(Math.random() * 10)].id,
				supporterId: employees![Math.floor(Math.random() * 10)].id,
				supportedStatus: faker.person.firstName(),
				supportedRemark: faker.commerce.productDescription(),
				supportedDate: DateTime.fromJSDate(faker.date.past()),
				certifierId: employees![Math.floor(Math.random() * 10)].id,
				certifiedStatus: faker.person.firstName(),
				certifiedRemark: faker.commerce.productDescription(),
				certifiedDate: DateTime.fromJSDate(faker.date.past()),
				confirmerId: employees![Math.floor(Math.random() * 10)].id,
				confirmedStatus: faker.person.firstName(),
				confirmedRemark: faker.commerce.productDescription(),
				confirmedDate: DateTime.fromJSDate(faker.date.past()),
				verifierId: employees![Math.floor(Math.random() * 10)].id,
				verifiedStatus: faker.person.firstName(),
				verifiedRemark: faker.commerce.productDescription(),
				verifiedDate: DateTime.fromJSDate(faker.date.past()),
				active: true,
				createdBy: 'Admin'
			},
			{
				fundId: educationFundApplications![Math.floor(Math.random() * 10)].id,
				supporterId: employees![Math.floor(Math.random() * 10)].id,
				supportedStatus: faker.person.firstName(),
				supportedRemark: faker.commerce.productDescription(),
				supportedDate: DateTime.fromJSDate(faker.date.past()),
				certifierId: employees![Math.floor(Math.random() * 10)].id,
				certifiedStatus: faker.person.firstName(),
				certifiedRemark: faker.commerce.productDescription(),
				certifiedDate: DateTime.fromJSDate(faker.date.past()),
				confirmerId: employees![Math.floor(Math.random() * 10)].id,
				confirmedStatus: faker.person.firstName(),
				confirmedRemark: faker.commerce.productDescription(),
				confirmedDate: DateTime.fromJSDate(faker.date.past()),
				verifierId: employees![Math.floor(Math.random() * 10)].id,
				verifiedStatus: faker.person.firstName(),
				verifiedRemark: faker.commerce.productDescription(),
				verifiedDate: DateTime.fromJSDate(faker.date.past()),
				active: true,
				createdBy: 'Admin'
			},
			{
				fundId: educationFundApplications![Math.floor(Math.random() * 10)].id,
				supporterId: employees![Math.floor(Math.random() * 10)].id,
				supportedStatus: faker.person.firstName(),
				supportedRemark: faker.commerce.productDescription(),
				supportedDate: DateTime.fromJSDate(faker.date.past()),
				certifierId: employees![Math.floor(Math.random() * 10)].id,
				certifiedStatus: faker.person.firstName(),
				certifiedRemark: faker.commerce.productDescription(),
				certifiedDate: DateTime.fromJSDate(faker.date.past()),
				confirmerId: employees![Math.floor(Math.random() * 10)].id,
				confirmedStatus: faker.person.firstName(),
				confirmedRemark: faker.commerce.productDescription(),
				confirmedDate: DateTime.fromJSDate(faker.date.past()),
				verifierId: employees![Math.floor(Math.random() * 10)].id,
				verifiedStatus: faker.person.firstName(),
				verifiedRemark: faker.commerce.productDescription(),
				verifiedDate: DateTime.fromJSDate(faker.date.past()),
				active: true,
				createdBy: 'Admin'
			},
			{
				fundId: educationFundApplications![Math.floor(Math.random() * 10)].id,
				supporterId: employees![Math.floor(Math.random() * 10)].id,
				supportedStatus: faker.person.firstName(),
				supportedRemark: faker.commerce.productDescription(),
				supportedDate: DateTime.fromJSDate(faker.date.past()),
				certifierId: employees![Math.floor(Math.random() * 10)].id,
				certifiedStatus: faker.person.firstName(),
				certifiedRemark: faker.commerce.productDescription(),
				certifiedDate: DateTime.fromJSDate(faker.date.past()),
				confirmerId: employees![Math.floor(Math.random() * 10)].id,
				confirmedStatus: faker.person.firstName(),
				confirmedRemark: faker.commerce.productDescription(),
				confirmedDate: DateTime.fromJSDate(faker.date.past()),
				verifierId: employees![Math.floor(Math.random() * 10)].id,
				verifiedStatus: faker.person.firstName(),
				verifiedRemark: faker.commerce.productDescription(),
				verifiedDate: DateTime.fromJSDate(faker.date.past()),
				active: true,
				createdBy: 'Admin'
			},
			{
				fundId: educationFundApplications![Math.floor(Math.random() * 10)].id,
				supporterId: employees![Math.floor(Math.random() * 10)].id,
				supportedStatus: faker.person.firstName(),
				supportedRemark: faker.commerce.productDescription(),
				supportedDate: DateTime.fromJSDate(faker.date.past()),
				certifierId: employees![Math.floor(Math.random() * 10)].id,
				certifiedStatus: faker.person.firstName(),
				certifiedRemark: faker.commerce.productDescription(),
				certifiedDate: DateTime.fromJSDate(faker.date.past()),
				confirmerId: employees![Math.floor(Math.random() * 10)].id,
				confirmedStatus: faker.person.firstName(),
				confirmedRemark: faker.commerce.productDescription(),
				confirmedDate: DateTime.fromJSDate(faker.date.past()),
				verifierId: employees![Math.floor(Math.random() * 10)].id,
				verifiedStatus: faker.person.firstName(),
				verifiedRemark: faker.commerce.productDescription(),
				verifiedDate: DateTime.fromJSDate(faker.date.past()),
				active: true,
				createdBy: 'Admin'
			},
			{
				fundId: educationFundApplications![Math.floor(Math.random() * 10)].id,
				supporterId: employees![Math.floor(Math.random() * 10)].id,
				supportedStatus: faker.person.firstName(),
				supportedRemark: faker.commerce.productDescription(),
				supportedDate: DateTime.fromJSDate(faker.date.past()),
				certifierId: employees![Math.floor(Math.random() * 10)].id,
				certifiedStatus: faker.person.firstName(),
				certifiedRemark: faker.commerce.productDescription(),
				certifiedDate: DateTime.fromJSDate(faker.date.past()),
				confirmerId: employees![Math.floor(Math.random() * 10)].id,
				confirmedStatus: faker.person.firstName(),
				confirmedRemark: faker.commerce.productDescription(),
				confirmedDate: DateTime.fromJSDate(faker.date.past()),
				verifierId: employees![Math.floor(Math.random() * 10)].id,
				verifiedStatus: faker.person.firstName(),
				verifiedRemark: faker.commerce.productDescription(),
				verifiedDate: DateTime.fromJSDate(faker.date.past()),
				active: true,
				createdBy: 'Admin'
			},
			{
				fundId: educationFundApplications![Math.floor(Math.random() * 10)].id,
				supporterId: employees![Math.floor(Math.random() * 10)].id,
				supportedStatus: faker.person.firstName(),
				supportedRemark: faker.commerce.productDescription(),
				supportedDate: DateTime.fromJSDate(faker.date.past()),
				certifierId: employees![Math.floor(Math.random() * 10)].id,
				certifiedStatus: faker.person.firstName(),
				certifiedRemark: faker.commerce.productDescription(),
				certifiedDate: DateTime.fromJSDate(faker.date.past()),
				confirmerId: employees![Math.floor(Math.random() * 10)].id,
				confirmedStatus: faker.person.firstName(),
				confirmedRemark: faker.commerce.productDescription(),
				confirmedDate: DateTime.fromJSDate(faker.date.past()),
				verifierId: employees![Math.floor(Math.random() * 10)].id,
				verifiedStatus: faker.person.firstName(),
				verifiedRemark: faker.commerce.productDescription(),
				verifiedDate: DateTime.fromJSDate(faker.date.past()),
				active: true,
				createdBy: 'Admin'
			},
			{
				fundId: educationFundApplications![Math.floor(Math.random() * 10)].id,
				supporterId: employees![Math.floor(Math.random() * 10)].id,
				supportedStatus: faker.person.firstName(),
				supportedRemark: faker.commerce.productDescription(),
				supportedDate: DateTime.fromJSDate(faker.date.past()),
				certifierId: employees![Math.floor(Math.random() * 10)].id,
				certifiedStatus: faker.person.firstName(),
				certifiedRemark: faker.commerce.productDescription(),
				certifiedDate: DateTime.fromJSDate(faker.date.past()),
				confirmerId: employees![Math.floor(Math.random() * 10)].id,
				confirmedStatus: faker.person.firstName(),
				confirmedRemark: faker.commerce.productDescription(),
				confirmedDate: DateTime.fromJSDate(faker.date.past()),
				verifierId: employees![Math.floor(Math.random() * 10)].id,
				verifiedStatus: faker.person.firstName(),
				verifiedRemark: faker.commerce.productDescription(),
				verifiedDate: DateTime.fromJSDate(faker.date.past()),
				active: true,
				createdBy: 'Admin'
			},
		])
	}
}
