import BaseSeeder from '@ioc:Adonis/Lucid/Seeder';
import Title from 'App/Models/Title';

export default class extends BaseSeeder {
    public async run() {
        const uniqueKey = 'description';
        await Title.updateOrCreateMany(uniqueKey, [
            {
                code: `5501`,
                description: `Doktor`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `C001`,
                description: `Tun`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `C002`,
                description: `Tan Sri`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `C003`,
                description: `Tan Sri Dato'`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `C004`,
                description: `Tan Sri Dato' Dr.`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `C005`,
                description: `Tan Sri Dato' Ir.`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `C006`,
                description: `Tan Sri Dato' Seri`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `C007`,
                description: `Tan Sri Datuk`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `C008`,
                description: `Tan Sri Datuk Dr.`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `C009`,
                description: `Tan Sri Datuk Profesor`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `C010`,
                description: `Tan Sri Datuk Profesor Dr.`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `C011`,
                description: `Tan Sri Dr.`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `C012`,
                description: `Tan Sri Jeneral`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `C013`,
                description: `Tan Sri Profesor`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `C014`,
                description: `Dato'`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `C015`,
                description: `Dato' Dr.`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `C016`,
                description: `Dato' Ir.`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `C017`,
                description: `Dato' Ir. Dr.`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `C018`,
                description: `Dato' Paduka Dr.`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `C019`,
                description: `Dato' Profesor Madya Dr.`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `C020`,
                description: `Dato' Senara Muda`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `C021`,
                description: `Dato' Seri`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `C022`,
                description: `Dato' Sri`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `C023`,
                description: `Brigedier Jeneral Dato'`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `C024`,
                description: `Datuk`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `C025`,
                description: `Datuk Amar`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `C026`,
                description: `Datuk Bentara Luar`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `C027`,
                description: `Datuk Bentara Raja`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `C028`,
                description: `Datuk Dr.`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `C029`,
                description: `Datuk Ir.`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `C030`,
                description: `Datuk Patinggi`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `C031`,
                description: `Datuk Profesor`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `C032`,
                description: `Datuk Profesor Dr.`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `C033`,
                description: `Datuk Setia`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `C034`,
                description: `Datuk Setia Wangsa`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `C035`,
                description: `Datuk Sri`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `C036`,
                description: `Datuk Sri Amar DiRaja`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `C037`,
                description: `Datuk Sri Dr.`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `C038`,
                description: `Datuk Wira`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `C039`,
                description: `Datuk Wira Jaya`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `C040`,
                description: `Dato' Seri DiRaja`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `C041`,
                description: `Ir.`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `C042`,
                description: `Ir. Dr.`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `C043`,
                description: `Jeneral`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `C044`,
                description: `Kapten`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `C045`,
                description: `Kolonel`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `C046`,
                description: `Lt. Kolonel`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `C047`,
                description: `Major`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `C048`,
                description: `Profesor`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `C049`,
                description: `Profesor DiRaja`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `C050`,
                description: `Profesor Dr.`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `C051`,
                description: `Profesor Madya`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `C052`,
                description: `Profesor Madya Dr.`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `C053`,
                description: `Datu`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `C054`,
                description: `Dr.`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `C055`,
                description: `Datuk Kol.`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `C056`,
                description: `Datuk Seri`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `C057`,
                description: `Dato' Paduka`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `C058`,
                description: `Dato' Wira`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `C059`,
                description: `Datuk Seri Utama`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `C060`,
                description: `Dato' Seri Utama`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `C061`,
                description: `Dato' Pahlawan`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `C062`,
                description: `Dato' Seri Panglima`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `C063`,
                description: `Datuk Seri Panglima`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `C064`,
                description: `Sr.`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `C065`,
                description: `Dato' Setia`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `C066`,
                description: `Dato' Sri Dr.`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `C067`,
                description: `Profesor Dato' Dr.`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `C068`,
                description: `Profesor Emeritus Tan Sri Dato' Dr.`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `C069`,
                description: `Profesor Emeritus Dato' Dr.`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `C070`,
                description: `Dato' Seri Setia DiRaja`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `C071`,
                description: `Profesor Ir. Dr.`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `C072`,
                description: `Profesor Madya Ir.`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `C073`,
                description: `Profesor Madya Ir. Dr.`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `C074`,
                description: `Prof. Dato' Paduka Dr.`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `C075`,
                description: `Mejar Profesor Madya Dr.`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `C076`,
                description: `Dato' Seri Profesor Dr.`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `C077`,
                description: `Profesor Sr. Dr.`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `C078`,
                description: `Dato' Profesor Emeritus Dr.`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `C079`,
                description: `Datuk Profesor Emeritus`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `C080`,
                description: `Datuk Profesor Emeritus Dr.`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `C081`,
                description: `Profesor Emeritus Dr.`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `C082`,
                description: `Profesor Ir.`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `C083`,
                description: `Profesor Madya Sr. Dr.`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `C084`,
                description: `Sr. Dr.`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `C085`,
                description: `Datuk Profesor Madya`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `C086`,
                description: `Dato' Paduka Profesor`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `C087`,
                description: `Datuk Profesor Madya Dr.`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `C088`,
                description: `Dato' Profesor Sr. Dr.`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `C089`,
                description: `Kepten`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `C090`,
                description: `Datu Dr.`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `C091`,
                description: `Yang Mulia`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `C092`,
                description: `Ar.`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `C093`,
                description: `Datuk Seri Dr.`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `C094`,
                description: `Tan Sri Dato' Sri`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `C095`,
                description: `Profesor Datuk Dr.`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `C096`,
                description: `Mejar Jeneral Dato'`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `C097`,
                description: `Ts.`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `C098`,
                description: `Tc.`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `C099`,
                description: `Dato' Indera`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `C100`,
                description: `Dato' Profesor`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `C101`,
                description: `Dato' Profesor Dr.`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `C102`,
                description: `Profesor Emeritus Dato' Paduka Dr.`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `C103`,
                description: `Dato' Profesor Ir. Dr.`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `C104`,
                description: `Tan Sri Dato' Seri Dr.`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `C105`,
                description: `Tan Sri Dato' Sri Profesor Ir. Dr.`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `C106`,
                description: `Ts. Dr.`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `C107`,
                description: `Dato' Profesor Madya`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `C108`,
                description: `Dato' Profesor Madya Ir.`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `C109`,
                description: `Datuk Ir. Dr.`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `C110`,
                description: `Profesor Emeritus Tan Sri Dato' Seri Ir. Dr.`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `C111`,
                description: `Profesor Madya Ar.`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `C112`,
                description: `Profesor Madya Sr.`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `C113`,
                description: `Profesor Sr. Ir. Dr.`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `C114`,
                description: `LAr. Dr.`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `C115`,
                description: `Kol. Dato' Profesor Dr.`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `C116`,
                description: `Kolonel (B) Dr.`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `C117`,
                description: `Ir. Ts. Dr.`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `C118`,
                description: `Ir. Ts.`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `C119`,
                description: `Profesor Madya Dr.`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `C120`,
                description: `Profesor Madya Dato' Dr.`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `C121`,
                description: `Profesor Ts. Dr.`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `C122`,
                description: `Profesor Madya Ir.Ts.Dr.`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `C123`,
                description: `Profesor Emeritus Ir. Dr.`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `C124`,
                description: `Dr.-Ing.`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `C125`,
                description: `Dato' Seri Dr.`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `C126`,
                description: `Profesor Madya Ts. Dr.`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `C127`,
                description: `Tun Dr.`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `C128`,
                description: `Datuk Seri Ir. Dr.`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `C129`,
                description: `Datuk Wira Dr.`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `C130`,
                description: `Tan Sri Datuk Seri`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `C131`,
                description: `Dato' Seri Wira`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `C132`,
                description: `Dato' Diraja`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `C133`,
                description: `Dato' Sri Diraja`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `C134`,
                description: `TPr.`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `C135`,
                description: `Dato' Seri DiRaja Bendahara Negara`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `C136`,
                description: `Ar. Dr.`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `C137`,
                description: `YB Senator`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `C138`,
                description: `YB`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `C139`,
                description: `ChM. Dr.`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `C140`,
                description: `Dato' Kaya Setia`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `C141`,
                description: `Dato' Perwira Raja`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `C142`,
                description: `Yang Mulia Dato'`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `C143`,
                description: `Dato' Seri Ir. Dr.`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `C144`,
                description: `ChM.`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `C145`,
                description: `Dato' Profesor Sr. Ir. Ts. Dr.`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `C146`,
                description: `Dato' Profesor Ts. Dr.`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `C147`,
                description: `Dato' Profesor Ir. Ts. Dr.`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `C148`,
                description: `Dato' Profesor Sr. Ir. Dr.`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `C149`,
                description: `Sr. Ts.`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `C150`,
                description: `Datuk Ir. Ts. Dr.`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `C151`,
                description: `LAr.`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `C152`,
                description: `Profesor Emeritus Tan Sri Dato' Sri Dr.`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `C153`,
                description: `Profesor Madya Gs. Dr.`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `C154`,
                description: `Datuk Ts. Dr.`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `C155`,
                description: `Brigedier Jeneral`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `C156`,
                description: `Ts. ChM. Dr.`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `L001`,
                description: `Encik`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `L002`,
                description: `Tuan`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `L003`,
                description: `Haji`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `L004`,
                description: `Ir. Haji`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `L005`,
                description: `Datuk Haji`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `L006`,
                description: `Dato' Haji`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `L007`,
                description: `Dato' Ir. Haji`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `L008`,
                description: `Dr. Haji`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `L009`,
                description: `Profesor Dr. Haji`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `L010`,
                description: `Profesor Haji`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `L011`,
                description: `Profesor Ir. Dr. Haji`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `L012`,
                description: `Profesor Madya Dr. Haji`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `L013`,
                description: `Profesor Madya Dr. Ir. Haji`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `L014`,
                description: `Profesor Madya Haji`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `L015`,
                description: `Profesor Emeritus Datuk Dr.`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `L016`,
                description: `Profesor Ts. Dr. Haji`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `L017`,
                description: `Profesor Sr. Ts. Dr. Haji`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `L018`,
                description: `Tan Sri Datuk Seri Panglima Haji`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `L019`,
                description: `Datuk Seri Panglima Dr.`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `L020`,
                description: `Datuk Dr. Haji`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `L021`,
                description: `Dato' Dr. Haji`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `L022`,
                description: `Dato' Sri Dr. Haji`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `L023`,
                description: `Dato' Sri Haji`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `L024`,
                description: `Datuk Seri Haji`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `L025`,
                description: `Datuk Seri Panglima Haji`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `L026`,
                description: `Dato' Seri Haji`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `L027`,
                description: `Dato' Setia Dr. Haji`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `L028`,
                description: `Ir. Ts. Dr. Haji`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `P001`,
                description: `To' Puan Seri`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `P002`,
                description: `Toh Puan`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `P003`,
                description: `Puan Sri`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `P004`,
                description: `Puan Sri Datin`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `P005`,
                description: `Puan Sri Datin Profesor`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `P006`,
                description: `Puan Sri Dr.`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `P007`,
                description: `Puan Sri Utama`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `P008`,
                description: `Datin`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `P009`,
                description: `Datin Amar`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `P010`,
                description: `Datin Dr.`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `P011`,
                description: `Datin Paduka`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `P012`,
                description: `Datin Patinggi`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `P013`,
                description: `Datin Profesor`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `P014`,
                description: `Profesor Datin Dr.`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `P015`,
                description: `Datin Setia`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `P016`,
                description: `Datin Sri`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `P017`,
                description: `Datin Sri Cempaka`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `P018`,
                description: `Datin Sri Dr.`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `P019`,
                description: `Cik`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `P020`,
                description: `Puan`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `P021`,
                description: `Hajah`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `P022`,
                description: `Datin Seri Setia DiRaja`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `P023`,
                description: `Datin Seri Utama`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `P024`,
                description: `Datin Wira`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `P025`,
                description: `Datin Seri`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `P026`,
                description: `Toh Puan Seri Utama`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `P027`,
                description: `Pehin Sri`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `P028`,
                description: `To' Puan`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `P029`,
                description: `Datin Paduka Setia`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `P030`,
                description: `Datin Paduka Seri`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `P031`,
                description: `Datin Indera`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `P032`,
                description: `Prof. Datin Paduka Dr.`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `P033`,
                description: `Datin Profesor Madya Dr.`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `P034`,
                description: `Puan Sri Profesor Madya`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `P035`,
                description: `Datin Sri Dato'`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `P036`,
                description: `Puan Sri Datuk`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `P037`,
                description: `Puan Sri Dato' Sri`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `P038`,
                description: `Datuk Hajah`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `P039`,
                description: `Datin Profesor Dr.`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `P040`,
                description: `Puan Sri Datin Sri Profesor Dr.`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `P041`,
                description: `Puan Sri Dato' Profesor Madya Dr.`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `P042`,
                description: `Sr. Dr. Hajah`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `P043`,
                description: `Datin Paduka Profesor Madya`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `P044`,
                description: `Datin Profesor Ir. Dr. Hajah`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `P045`,
                description: `Datin Profesor Madya`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `P046`,
                description: `Datin Profesor Madya Hajah`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `P047`,
                description: `Datin Profesor Sr. Dr.`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `P048`,
                description: `Datin Sr. Dr.`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `P049`,
                description: `Dr. Hajah`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `P050`,
                description: `Profesor Dr. Hajah`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `P051`,
                description: `Profesor Hajah`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `P052`,
                description: `Profesor Ir. Dr. Hajah`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `P053`,
                description: `Profesor Madya Dr. Hajah`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `P054`,
                description: `Profesor Madya Hajah`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `P055`,
                description: `Profesor Madya Sr. Hajah`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `P056`,
                description: `Profesor Emerita Dr.`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `P057`,
                description: `Datin Ir.`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `P058`,
                description: `Profesor Datin Paduka Setia Dato' Dr.`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `P059`,
                description: `Datin Sri Diraja`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `P060`,
                description: `Dato' Sri Hajah`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `P061`,
                description: `Datuk Wira Hajah`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `P062`,
                description: `Dato' Hajah`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `P063`,
                description: `To' Puan Seri Utama`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `P064`,
                description: `Datin Seri Diraja`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `P065`,
                description: `Datin Seri Wira`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `P066`,
                description: `Tok Puan`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `P067`,
                description: `Datin Diraja`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `P068`,
                description: `Puan Sri Datin Seri Panglima`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `P069`,
                description: `Datin Seri Panglima`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `P070`,
                description: `Datin Paduka Dr.`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `P071`,
                description: `Puan Sri To' Puan Seri`,
                active: true,
                createdBy: 'Admin',
            },
        ]);
    }
}
