import BaseSeeder from '@ioc:Adonis/Lucid/Seeder';
import Ethnicity from 'App/Models/Ethnicity';

export default class extends BaseSeeder {
    public async run() {
        const uniqueKey = 'description';
        await Ethnicity.updateOrCreateMany(uniqueKey, [
            {
                code: `0000`,
                description: `Tiada Maklumat`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `0100`,
                description: `Melayu`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `0101`,
                description: `Bugis`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `0102`,
                description: `Boyan`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `0103`,
                description: `Banjar`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `0104`,
                description: `Jawa`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `0105`,
                description: `Jawi Pekan`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `0106`,
                description: `Minangkabau`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `0200`,
                description: `Cina`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `0201`,
                description: `Cantonese`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `0202`,
                description: `Foochow`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `0203`,
                description: `Hainanese`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `0204`,
                description: `Henghua`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `0205`,
                description: `Hokchia`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `0206`,
                description: `Hokchiu`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `0207`,
                description: `Hokkien`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `0208`,
                description: `Khek (Hakka)`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `0209`,
                description: `Kwongsai`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `0210`,
                description: `Teochew`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `0211`,
                description: `Kongfoo`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `0212`,
                description: `Hylam`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `0300`,
                description: `India`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `0301`,
                description: `Malayali`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `0302`,
                description: `Punjabi`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `0303`,
                description: `Sikh`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `0304`,
                description: `Tamil`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `0305`,
                description: `Telegu`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `0306`,
                description: `Malabari`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `0307`,
                description: `India Muslim`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `0308`,
                description: `Telugu`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `0309`,
                description: `Orissa`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `0400`,
                description: `Bangladeshi`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `0500`,
                description: `Pakistani`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `0600`,
                description: `Sri Lanka`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `0601`,
                description: `Tamil Sri Lanka`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `0602`,
                description: `Melayu Sri Lanka`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `0603`,
                description: `Sinhalese`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `0604`,
                description: `Ceylonese`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `0700`,
                description: `Indonesia`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `0701`,
                description: `Tidung`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `0799`,
                description: `Lain-lain`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `0800`,
                description: `Bumiputera Sabah`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `0801`,
                description: `Bajau`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `0802`,
                description: `Dusun`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `0803`,
                description: `Kadazan`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `0804`,
                description: `Murut`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `0805`,
                description: `Sino-Native`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `0806`,
                description: `Suluk`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `0807`,
                description: `Tidung`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `0811`,
                description: `Bonggi`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `0812`,
                description: `Toraja`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `0817`,
                description: `Lotud`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `0820`,
                description: `Tatana`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `0821`,
                description: `Tagahas`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `0828`,
                description: `Ubian/Obian`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `0829`,
                description: `Banjar`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `0901`,
                description: `Binadan`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `0902`,
                description: `Bisaya`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `0903`,
                description: `Bongol`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `0904`,
                description: `Brunei`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `0905`,
                description: `Dumpas`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `0906`,
                description: `Iranun`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `0907`,
                description: `Idahan`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `0908`,
                description: `Kwijau`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `0909`,
                description: `Kedayan`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `0910`,
                description: `Lingkabau`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `0911`,
                description: `Lundayeh`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `0912`,
                description: `Lasau`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `0913`,
                description: `Melanau`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `0914`,
                description: `Mangkaak`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `0915`,
                description: `Matagang`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `0916`,
                description: `Minokok`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `0917`,
                description: `Melayu Sabah`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `0918`,
                description: `Momogun`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `0919`,
                description: `Paitan`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `0920`,
                description: `Rumanau`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `0921`,
                description: `Rungus`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `0922`,
                description: `Sungai`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `0923`,
                description: `Sonsongan`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `0924`,
                description: `Sinulihan`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `0925`,
                description: `Tombonuo`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `0926`,
                description: `Tagal`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `0927`,
                description: `Tinagas`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `0928`,
                description: `Cocos`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `0929`,
                description: `Kimaragang`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `0930`,
                description: `Bolongan`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `0931`,
                description: `Buton`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `0932`,
                description: `Kagayan`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `0933`,
                description: `Balabak`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `0934`,
                description: `Kadazan-Sino`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `0935`,
                description: `Dusun-Sino`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `0936`,
                description: `Bajau-Sino`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `0937`,
                description: `Murut-Sino`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `0938`,
                description: `Brunei-Sino`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `0939`,
                description: `Rungus-Sino`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `0940`,
                description: `Bisaya-Sino`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `0941`,
                description: `Idahan-Sino`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `0942`,
                description: `Iranun-Sino`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `0943`,
                description: `Kedayan-Sino`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `0944`,
                description: `Sungai-Sino`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `0945`,
                description: `Lundayeh-Sino`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `0946`,
                description: `Suluk-Sino`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `0947`,
                description: `Tidung-Sino`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `0948`,
                description: `Bolongan-Sino`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `0949`,
                description: `Balabak-Sino`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `1000`,
                description: `Bumiputera Sarawak`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `1001`,
                description: `Melayu Sarawak`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `1002`,
                description: `Melanau`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `1003`,
                description: `Kedayan`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `1004`,
                description: `Iban atau Sea Dayak`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `1005`,
                description: `Bidayuh atau Land Dayak`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `1006`,
                description: `Kayan`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `1007`,
                description: `Kenyah`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `1008`,
                description: `Murut atau Lun Bawang`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `1009`,
                description: `Kelabit`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `1010`,
                description: `Punan`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `1011`,
                description: `Penan`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `1012`,
                description: `Orang Ulu`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `1101`,
                description: `Bisayah`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `1102`,
                description: `Berawan`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `1103`,
                description: `Belot`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `1104`,
                description: `Buket`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `1105`,
                description: `Balau`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `1106`,
                description: `Batang Ai`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `1107`,
                description: `Batu Elah`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `1108`,
                description: `Baketan`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `1109`,
                description: `Bintulu`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `1110`,
                description: `Badang`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `1111`,
                description: `Dusun`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `1112`,
                description: `Jagoi`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `1113`,
                description: `Lakiput`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `1114`,
                description: `Kajang`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `1115`,
                description: `Kejaman`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `1116`,
                description: `Kanowit`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `1117`,
                description: `Lirong`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `1118`,
                description: `Lemanak`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `1119`,
                description: `Lahanan`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `1120`,
                description: `Lisum atau Lugum`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `1121`,
                description: `Matu`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `1122`,
                description: `Memaloh`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `1123`,
                description: `Melikin`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `1124`,
                description: `Melaing`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `1125`,
                description: `Ngurik`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `1126`,
                description: `Menondo`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `1127`,
                description: `Nyamok`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `1128`,
                description: `Sebop`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `1129`,
                description: `Seduan`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `1130`,
                description: `Sekapan`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `1131`,
                description: `Segalang`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `1132`,
                description: `Sihan`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `1133`,
                description: `Sipeng`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `1134`,
                description: `Saribas`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `1135`,
                description: `Sebuyau`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `1136`,
                description: `Skrang`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `1137`,
                description: `Saban`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `1138`,
                description: `Selakan`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `1139`,
                description: `Selako`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `1140`,
                description: `Tagal`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `1141`,
                description: `Tabun`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `1142`,
                description: `Tutong`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `1143`,
                description: `Tanjong`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `1144`,
                description: `Tatau`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `1145`,
                description: `Taup`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `1146`,
                description: `Ukit`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `1147`,
                description: `Unkop`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `1148`,
                description: `Ulu Ai`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `1149`,
                description: `Toraja`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `1150`,
                description: `Timor`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `1151`,
                description: `Menado`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `1152`,
                description: `Manura`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `1153`,
                description: `Batak`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `1154`,
                description: `Pathan`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `1155`,
                description: `Tongans`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `1200`,
                description: `Orang Asli (Semenanjung)`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `1201`,
                description: `Jakun`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `1202`,
                description: `Negrito`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `1203`,
                description: `Sakai`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `1204`,
                description: `Semai`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `1205`,
                description: `Semalai`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `1206`,
                description: `Temiar`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `1207`,
                description: `Senoi`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `1300`,
                description: `Lain-Lain Asia`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `1301`,
                description: `Arab`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `1302`,
                description: `Burmese`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `1303`,
                description: `Eurasian`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `1304`,
                description: `Fijian`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `1305`,
                description: `Filipino`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `1306`,
                description: `Gurkha`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `1307`,
                description: `Japanese`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `1308`,
                description: `Khmer`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `1309`,
                description: `Korean`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `1310`,
                description: `Maltese`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `1311`,
                description: `Portugese`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `1312`,
                description: `Thai`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `1313`,
                description: `Vietnamese`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `1314`,
                description: `Iranian`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `1315`,
                description: `Afghan`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `1318`,
                description: `Ubian`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `1324`,
                description: `Kemboja`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `1325`,
                description: `Myanmar`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `1326`,
                description: `Nepal`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `1400`,
                description: `European`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `1401`,
                description: `British`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `1498`,
                description: `Mesir`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `1601`,
                description: `Siam`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `1701`,
                description: `Sikh`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `9901`,
                description: `Kenya`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `9999`,
                description: `Lain-lain`,
                active: true,
                createdBy: 'Admin',
            },
        ]);
    }
}
