import BaseSeeder from '@ioc:Adonis/Lucid/Seeder';
import Sponsorship from 'App/Models/Sponsorship';

export default class extends BaseSeeder {
    public async run() {
        const uniqueKey = 'description';
        await Sponsorship.updateOrCreateMany(uniqueKey, [
            {
                code: `0`,
                description: `Tiada Maklumat`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `100`,
                description: `Jabatan Perkhidmatan Awam`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `101`,
                description: `Tabung Pembangunan Sains dan Teknologi / JPA`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `102`,
                description: `Universiti Kebangsaan Malaysia`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `103`,
                description: `Dermasiswa Persekutuan`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `104`,
                description: `Majlis Amanah Rakyat (MARA)`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `105`,
                description: `Petronas`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `106`,
                description: `TELEKOM Malaysia`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `107`,
                description: `Perbadanan Tabung Pendidikan Tinggi Nasional (PTPTN)`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `108`,
                description: `Dewan Bandaraya Kuala Lumpur (DBKL)`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `109`,
                description: `Tabung Pembangunan Kemahiran (TPK)`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `200`,
                description: `Commonwealth Scholarship`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `300`,
                description: `Kerajaan British`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `301`,
                description: `British Council`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `302`,
                description: `British High Commissioner's Award`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `303`,
                description: `Royal College Of Defence Studies (RCDS)`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `304`,
                description: `British Columbia Ministry Forests`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `400`,
                description: `Rancangan Colombo`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `401`,
                description: `Colombo - Singapura`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `402`,
                description: `Colombo - India`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `403`,
                description: `Colombo - Australia`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `404`,
                description: `Colombo - Jepun`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `405`,
                description: `Colombo - New Zealand`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `406`,
                description: `Colombo - United Kingdom`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `407`,
                description: `Colombo - Canada`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `499`,
                description: `Colombo - Lain-lain`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `500`,
                description: `Kerajaan Jepun`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `501`,
                description: `Mombushoo`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `510`,
                description: `JICA`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `511`,
                description: `JICA - Jepun`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `512`,
                description: `JICA - Thailand`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `513`,
                description: `JICA - Indonesia`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `514`,
                description: `JICA - Singapura`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `515`,
                description: `JICA - Malaysia`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `516`,
                description: `JICA - Filipina`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `517`,
                description: `Japan Institute Of Invention and Innovation (JIII)`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `599`,
                description: `JICA - Lain-lain`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `600`,
                description: `Negara Korea`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `700`,
                description: `Kerajaan Asing / Cost Sharing`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `701`,
                description: `Kerajaan Sweden`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `702`,
                description: `Kerajaan Republik German`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `703`,
                description: `Kerajaan India`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `704`,
                description: `Kerajaan Belanda`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `705`,
                description: `Kerajaan Kanada`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `706`,
                description: `Kerajaan Thailand`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `707`,
                description: `Kerajaan Filipina`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `708`,
                description: `Kerajaan Singapura`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `709`,
                description: `Kerajaan Indonesia`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `710`,
                description: `Kerajaan Amerika Syarikat (USA)`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `711`,
                description: `Kerajaan Belgium`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `712`,
                description: `Kerajaan Brunei`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `713`,
                description: `Kerajaan Denmark`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `714`,
                description: `Kerajaan Greece`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `715`,
                description: `Kerajaan Italy`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `716`,
                description: `Kerajaan Mesir`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `717`,
                description: `Kerajaan Perancis`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `718`,
                description: `Kerajaan Poland`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `719`,
                description: `Kerajaan Russia`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `720`,
                description: `Kerajaan Switzerland`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `721`,
                description: `Kerajaan Iraq`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `722`,
                description: `Kerajaan Australia`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `799`,
                description: `Lain-lain Kerajaan`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `800`,
                description: `Badan-badan Asing / Bukan Kerajaan`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `801`,
                description: `MACEE Fellowship`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `802`,
                description: `South East Asia Fisheries Development Centre (SEAFDEC)`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `803`,
                description: `AARRO`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `804`,
                description: `Conference Of British Industry (CBI)`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `805`,
                description: `Asean Productivity Organization (APO)`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `806`,
                description: `Asean Training Board`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `807`,
                description: `Norwegian Agency For International Development (NORAD)`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `808`,
                description: `Statistical Institute For Asia & Pacific (SIAP)`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `809`,
                description: `Asia-Pacific Institute Of Broadcasting Development (AIBD)`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `898`,
                description: `Kementerian Sumber Manusia`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `899`,
                description: `Badan Asing Lain-lain`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `900`,
                description: `Kerajaan Negeri / Yayasan Negeri`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `901`,
                description: `Kementerian Pendidikan Malaysia`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `902`,
                description: `Kementerian Pertahanan`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `903`,
                description: `Persekutuan Sabah`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `904`,
                description: `Persekutuan Sarawak`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `905`,
                description: `Negeri Johor`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `906`,
                description: `Negeri Kedah`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `907`,
                description: `Negeri Kelantan`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `908`,
                description: `Negeri Pahang`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `909`,
                description: `Negeri Perak`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `910`,
                description: `Negeri Perlis`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `911`,
                description: `Negeri Pulau Pinang`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `912`,
                description: `Negeri Sabah`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `913`,
                description: `Negeri Sarawak`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `914`,
                description: `Negeri Selangor`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `915`,
                description: `Negeri Sembilan`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `916`,
                description: `Negeri Terengganu`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `917`,
                description: `Balwant Singh`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `918`,
                description: `Kumpulan Wang Pelajaran Tinggi`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `919`,
                description: `Lembaga Biasiswa C.M Hashim`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `920`,
                description: `Biasiswa Tan Sri Manikavasagam`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `921`,
                description: `Ong Keng Seng Memorial Education Fund`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `922`,
                description: `K. Ramanathan`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `923`,
                description: `Tan Sri Saw Seng Memorial Education Fund`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `924`,
                description: `Dr Tan Chee Khoon Foundation`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `925`,
                description: `C.J Windsor`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `926`,
                description: `Yayasan Asia`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `927`,
                description: `Yayasan Kelantan`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `928`,
                description: `Yayasan Kuok`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `929`,
                description: `Yayasan Lee`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `930`,
                description: `Yayasan Tan Sri Hj. Mohammed Noah Omar`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `931`,
                description: `Yayasan Sabah`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `932`,
                description: `Yayasan Sarawak`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `933`,
                description: `Yayasan Terengganu`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `934`,
                description: `Yayasan Negeri Sembilan`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `935`,
                description: `Yayasan Ford`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `936`,
                description: `Baitul Mal`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `937`,
                description: `Kementerian Kesihatan`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `938`,
                description: `Kementerian Pembangunan Usahawan Malaysia`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `939`,
                description: `Datuk Bandar`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `940`,
                description: `Yayasan Melaka`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `941`,
                description: `Yayasan Perak`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `942`,
                description: `Kementerian Pengajian Tinggi (KPT)`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `943`,
                description: `Kementerian Belian dan Sukan (KBS)`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `944`,
                description: `KPJ`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `999`,
                description: `Lain-lain Yayasan`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `1000`,
                description: `Agensi Bangsa-bangsa Bersatu`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `1001`,
                description: `Commonwealth Fund Technical Cooperation (CFTC)`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `1002`,
                description: `Economic Development Institut (EDI)`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `1003`,
                description: `East-West Center`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `1004`,
                description: `European Economic Community (EEC)`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `1005`,
                description: `U.N.Econ. & Soc. Commission For Asia & The Pacific (ESCAP)`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `1006`,
                description: `General Agreement On Tariffs and Trade (GATT)`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `1007`,
                description: `International Labour Organization (ILO)`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `1008`,
                description: `International Labour Organization (ILO/PRG)`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `1009`,
                description: `International Monetary Fund (IMF)`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `1010`,
                description: `International Trade Conference (ITC)`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `1011`,
                description: `International Union Of Local Authority (IULA)`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `1012`,
                description: `United Nations Conference On Trade & Development (UNCTAD)`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `1013`,
                description: `United Nations Educational Sci. & Cultural Org. (UNESCO/UNDP)`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `1014`,
                description: `World Bank`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `1015`,
                description: `World Trade Institute`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `1016`,
                description: `Food & Agricultural Organization (FAO)`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `1017`,
                description: `United Nation Development Programme (UNDP)`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `1018`,
                description: `International Atomic Energy Agency (IAEA)`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `1019`,
                description: `International Civil Aviation Organization (ICAO)`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `1020`,
                description: `Inter-Governmental Maritime Consultive Org. (IMCO)`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `1021`,
                description: `International Telecommunications Union (ITU)`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `1022`,
                description: `United Nations Industrial Development Org. (UNIDO)`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `1813`,
                description: `Malayawata Steel Bhd.`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `1814`,
                description: `Matsushita`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `1815`,
                description: `Monsanto`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `1816`,
                description: `Motorola (M) Sdn. Bhd.`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `1817`,
                description: `Penfibre Sdn. Bhd.`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `1818`,
                description: `Syarikat Chemical Co.Ot Malaysia Bhd.`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `1819`,
                description: `Temco Cutler`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `1820`,
                description: `Toshiba`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `1821`,
                description: `Universiti Pendidikan Sultan Idris`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `1822`,
                description: `Kumpulan Wang Simpanan Pekerja (KWSP)`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `1823`,
                description: `Jabatan Kemajuan Masyarakat (KEMAS)`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `1833`,
                description: `Pembiayaan Sendiri`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `1834`,
                description: `Kerajaan China`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `1900`,
                description: `NULL`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `1901`,
                description: `Lembaga Zakat Selangor`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `1902`,
                description: `FELDA`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `1903`,
                description: `Tabung Kumpulan Wang Biasiswa Negeri Selangor (TKWBNS)`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `1904`,
                description: `African-Asian Rural Development Organization (AARDO)`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `1905`,
                description: `Kerajaan Korea Selatan`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `1906`,
                description: `Jabatan Kemajuan Islam Malaysia (JAKIM)`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `9999`,
                description: `Lain-lain`,
                active: true,
                createdBy: 'Admin',
            },
        ]);
    }
}
