import BaseSeeder from '@ioc:Adonis/Lucid/Seeder';
import ServiceClass from 'App/Models/ServiceClass';

export default class extends BaseSeeder {
    public async run() {
        const uniqueKey = 'description';
        await ServiceClass.updateOrCreateMany(uniqueKey, [
            {
                code: `1`,
                description: `Jawatan Istana`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `2`,
                description: `Jawatan Terbuka`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `3`,
                description: `Anggota Pentadbiran`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `4`,
                description: `Kakitangan Ambilan Tempatan`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `5`,
                description: `Sistem Saraan Yang Diasingkan`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `A `,
                description: `Pengangkutan`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `B `,
                description: `Bakat dan Seni`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `C `,
                description: `Sains`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `CA `,
                description: `Pembantu Kawalan Alam Sekitar`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `D `,
                description: `Pendidikan`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `DG `,
                description: `Pegawai Perkhidmatan Pendidikan`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `DGA `,
                description: `Pegawai Perkhidmatan Pendidikan Lepasan Diploma`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `DGZ `,
                description: `Pendidikan Tentera -Pendidikan Berijazah dan Bukan Berijazah`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `DL `,
                description: `Pegawai Latihan Kemahiran`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `DM `,
                description: `Pensyarah UiTM`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `DS `,
                description: `Pensyarah Universiti`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `E `,
                description: `Ekonomi`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `F `,
                description: `Sistem Maklumat`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `G `,
                description: `Pertanian`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `GA `,
                description: `Pembantu Pertanian`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `GZ `,
                description: `Pertanian - Angkatan Tentera`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `H `,
                description: `Kemahiran`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `J `,
                description: `Kejuruteraan`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `JA `,
                description: `Juruteknik`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `JZ `,
                description: `Kejuruteraan - Angkatan Tentera`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `K `,
                description: `Keselamatan dan Pertahanan Awam`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `KB `,
                description: `Bomba`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `KJ `,
                description: `Askar Timbalan Setia Negeri Johor`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `KP `,
                description: `Pentadbiran Keselamatan`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `KR `,
                description: `Siasatan`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `KX `,
                description: `Penjara`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `L `,
                description: `Perundangan dan Kehakiman`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `LS `,
                description: `Perundangan Syariah`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `M `,
                description: `Tadbir dan Diplomatik`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `N `,
                description: `Pentadbiran Dan Sokongan`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `NP `,
                description: `Penghulu`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `NT `,
                description: `Pentadbiran Tanah`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `P `,
                description: `Pencegahan Rasuah`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `Q `,
                description: `Penyelidikan Dan Pembangunan`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `R `,
                description: `Mahir/ Separuh Mahir / Tidak Mahir`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `S `,
                description: `Sosial`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `SZ `,
                description: `Sosial - Angkatan Tentera`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `T `,
                description: `Penguatkuasaan Maritim`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `U `,
                description: `Perubatan dan Kesihatan`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `UD `,
                description: `Pegawai Perubatan`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `UF `,
                description: `Pegawai Farmasi`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `UG `,
                description: `Pegawai Pergigian`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `UZ `,
                description: `Kor Perubatan - Angkatan Tentera`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `VIP `,
                description: `Anggota Pentadbiran`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `W `,
                description: `Kewangan`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `WK `,
                description: `Kastam`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `X `,
                description: `Penguatkuasaan Maritim`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `XX `,
                description: `Tiada Klasifikasi Perkhidmatan`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `Y `,
                description: `Polis`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `YP `,
                description: `Polis Orang Asli`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `Z `,
                description: `Tentera`,
                active: true,
                createdBy: 'Admin',
            },
        ]);
    }
}
