import BaseSeeder from '@ioc:Adonis/Lucid/Seeder';
import Country from 'App/Models/Country';

export default class extends BaseSeeder {
    public async run() {
        const uniqueKey = 'description';
        await Country.updateOrCreateMany(uniqueKey, [
            {
                code: `AFG`,
                description: `Afghanistan`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `AGO`,
                description: `Angola`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `AIA`,
                description: `Anguilla`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `ALB`,
                description: `Albania`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `AND`,
                description: `Andorra`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `ANT`,
                description: `Netherlands Antilles`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `ARE`,
                description: `United Arab Emirates`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `ARG`,
                description: `Argentina`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `ARM`,
                description: `Armenia`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `ASM`,
                description: `American Samoa`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `ATA`,
                description: `Antartica`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `ATF`,
                description: `French Southern Territories`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `ATG`,
                description: `Antigua And Barbuda`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `AUS`,
                description: `Australia`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `AUT`,
                description: `Austria`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `AZE`,
                description: `Azerbaijan`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `BDI`,
                description: `Burundi`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `BEL`,
                description: `Belgium`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `BEN`,
                description: `Benin`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `BFA`,
                description: `Burkina Faso`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `BGD`,
                description: `Bangladesh`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `BGR`,
                description: `Bulgaria`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `BHR`,
                description: `Bahrain`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `BHS`,
                description: `Bahamas`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `BIH`,
                description: `Bosnia And Herzegovina`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `BLR`,
                description: `Belarus`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `BLZ`,
                description: `Belize`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `BMU`,
                description: `Bermuda`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `BOL`,
                description: `Bolivia`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `BRA`,
                description: `Brazil`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `BRB`,
                description: `Barbados`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `BRN`,
                description: `Brunei Darussalam`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `BTN`,
                description: `Bhutan`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `BVT`,
                description: `Bouvet Island`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `BWA`,
                description: `Botswana`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `CAF`,
                description: `Central African Republic`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `CAN`,
                description: `Canada`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `CCK`,
                description: `Cocos (Keeling) Islands`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `CHE`,
                description: `Switzerland`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `CHL`,
                description: `Chile`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `CHN`,
                description: `China`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `CIV`,
                description: `Cote D'ivoire`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `CMR`,
                description: `Cameroon`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `COD`,
                description: `"Congo, The Democratic Republic Of The"`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `COG`,
                description: `Congo (Zaire)`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `COK`,
                description: `Cook Island`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `COL`,
                description: `Colombia`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `COM`,
                description: `Comoros`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `CPV`,
                description: `Cape Verde`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `CRI`,
                description: `Costa Rica`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `CUB`,
                description: `Cuba`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `CXR`,
                description: `Christmas Island`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `CYM`,
                description: `Cayman Islands`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `CYP`,
                description: `Cyprus`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `CZE`,
                description: `Czech Republic`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `DEU`,
                description: `Germany`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `DJI`,
                description: `Djibouti`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `DMA`,
                description: `Dominica`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `DNK`,
                description: `Denmark`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `DOM`,
                description: `Dominican Republic`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `DZA`,
                description: `Algeria`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `ECU`,
                description: `Ecuador`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `EGY`,
                description: `Egypt`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `ERI`,
                description: `Eritrea`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `ESH`,
                description: `Western Sahara`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `ESP`,
                description: `Spain`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `EST`,
                description: `Estonia`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `ETH`,
                description: `Ethiopia`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `FIN`,
                description: `Finland`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `FJI`,
                description: `Fiji`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `FLK`,
                description: `Falkland Islands (Malvinas)`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `FRA`,
                description: `France`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `FRO`,
                description: `Faroe Islands`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `FSM`,
                description: `"Micronesia, Federated States Of"`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `GAB`,
                description: `Gabon`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `GBR`,
                description: `United Kingdom`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `GEO`,
                description: `Georgia`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `GHA`,
                description: `Ghana`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `GIB`,
                description: `Gibraltar`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `GIN`,
                description: `Guinea`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `GLP`,
                description: `Guadeloupe`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `GMB`,
                description: `Gambia`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `GNB`,
                description: `Guinea-Bissau`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `GNQ`,
                description: `Equatorial Guinea`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `GRC`,
                description: `Greece`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `GRD`,
                description: `Grenada`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `GTM`,
                description: `Guatemala`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `GUF`,
                description: `French Guiana`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `GUM`,
                description: `Guam`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `GUY`,
                description: `Guyana`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `HKG`,
                description: `Hong Kong`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `HMD`,
                description: `Heard Island And Mcdonald Islands`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `HND`,
                description: `Honduras`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `HRV`,
                description: `Croatia`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `HTI`,
                description: `Haiti`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `HUN`,
                description: `Hungary`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `IDN`,
                description: `Indonesia`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `IND`,
                description: `India`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `IOT`,
                description: `British Indian Ocean Territory`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `IRL`,
                description: `Ireland`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `IRN`,
                description: `"Iran, Islamic Republic Of"`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `IRQ`,
                description: `Iraq`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `ISL`,
                description: `Iceland`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `ISR`,
                description: `Israel`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `ITA`,
                description: `Italy`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `JAM`,
                description: `Jamaica`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `JOR`,
                description: `Jordan`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `JPN`,
                description: `Japan`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `KAZ`,
                description: `Kazakstan`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `KEN`,
                description: `Kenya`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `KGZ`,
                description: `Kyrgyzstan`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `KHM`,
                description: `Cambodia`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `KIR`,
                description: `Kiribati`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `KNA`,
                description: `Saint Kitts And Nevis`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `KOR`,
                description: `"Korea, Republic Of"`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `KWT`,
                description: `Kuwait`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `LAO`,
                description: `Lao People's Democratic Republic`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `LBN`,
                description: `Lebanon`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `LBR`,
                description: `Liberia`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `LBY`,
                description: `Libyan`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `LCA`,
                description: `Saint Lucia`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `LIE`,
                description: `Liehtenstein`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `LKA`,
                description: `Sri Lanka`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `LSO`,
                description: `Lesotho`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `LTU`,
                description: `Lithuania`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `LUX`,
                description: `Luxembourg`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `LVA`,
                description: `Latvia`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `m `,
                description: `Greenland`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `MAC`,
                description: `Macau`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `MAR`,
                description: `Morocco`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `MCO`,
                description: `Monaco`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `MDA`,
                description: `"Moldova, Republic Of"`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `MDG`,
                description: `Madgascar`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `MDV`,
                description: `Maldives`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `MEX`,
                description: `Mexico`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `MHL`,
                description: `Marshall Islands`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `MKD`,
                description: `"Macedonia, The Former Yugoslav Republic Of"`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `MLI`,
                description: `Mali`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `MLT`,
                description: `Malta`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `MMR`,
                description: `Myanmar`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `MNG`,
                description: `Mongolia`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `MNP`,
                description: `Northern Mariana Islands`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `MOZ`,
                description: `Mozambique`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `MRT`,
                description: `Mauritania`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `MSR`,
                description: `Montserrat`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `MTQ`,
                description: `Martinique`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `MUS`,
                description: `Mauritius`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `MWI`,
                description: `Malawi`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `MYS`,
                description: `Malaysia`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `MYT`,
                description: `Mayotte`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `NAM`,
                description: `Namibia`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `NCL`,
                description: `New Caledonia`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `NER`,
                description: `Niger`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `NFK`,
                description: `Norfolk Island`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `NGA`,
                description: `Nigeria`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `NIC`,
                description: `Nicaragua`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `NIU`,
                description: `Niue`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `NLD`,
                description: `Netherlands`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `NOR`,
                description: `Norway`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `NPL`,
                description: `Nepal`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `NRU`,
                description: `Nauru`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `NZL`,
                description: `New Zealand`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `OMN`,
                description: `Oman`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `PAK`,
                description: `Pakistan`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `PAN`,
                description: `Panama`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `PCN`,
                description: `Pitcairn`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `PER`,
                description: `Peru`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `PHL`,
                description: `Philippines`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `PLS`,
                description: `Palestinian Territory`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `PLW`,
                description: `Palau`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `PNG`,
                description: `Papua New Guinea`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `POL`,
                description: `Poland`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `PRI`,
                description: `Puerto Rico`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `PRK`,
                description: `"Korea, Democratic People's Republic Of"`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `PRT`,
                description: `Portugal`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `PRY`,
                description: `Paraguay`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `PYF`,
                description: `French Polunesia`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `QAT`,
                description: `Qatar`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `REU`,
                description: `Reunion`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `ROM`,
                description: `Romania`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `RUS`,
                description: `Russian Federation`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `RWA`,
                description: `Rwanda`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `SAU`,
                description: `Arab Saudi`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `SDN`,
                description: `Sudan`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `SEN`,
                description: `Senegal`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `SER`,
                description: `Serbia and Montenegro`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `SGP`,
                description: `Singapura`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `SGS`,
                description: `South Georgia And The South Sandwich Islands`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `SHN`,
                description: `Saint Helena`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `SJM`,
                description: `Svalbard And Jan Mayen`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `SLB`,
                description: `Solomon Islands`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `SLE`,
                description: `Sierra Leone`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `SLV`,
                description: `El Salvador`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `SMR`,
                description: `San Marino`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `SOM`,
                description: `Somalia`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `SPM`,
                description: `Saint Pierre And Miquelon`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `STP`,
                description: `Sao Tome And Principe`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `SUR`,
                description: `Suriname`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `SVK`,
                description: `Slovakia`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `SVN`,
                description: `Slovenia`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `SWE`,
                description: `Sweden`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `SWZ`,
                description: `Swaziland`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `SYC`,
                description: `Seychelles`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `SYR`,
                description: `Syrian Arab Republic`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `TCA`,
                description: `Turks And Caicos Islands`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `TCD`,
                description: `Chad`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `TGO`,
                description: `Togo`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `THA`,
                description: `Thailand`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `TJK`,
                description: `Tajikistan`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `TKL`,
                description: `Tokelau`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `TKM`,
                description: `Turkmenistan`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `TMP`,
                description: `East Timor`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `TON`,
                description: `Tonga`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `TTO`,
                description: `Tinidad And Tobago`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `TUN`,
                description: `Tunisia`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `TUR`,
                description: `Turkey`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `TUV`,
                description: `Tuvalu`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `TWN`,
                description: `"Taiwan, Province Of China"`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `TZA`,
                description: `"Tanzania, United Republic Of"`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `UGA`,
                description: `Uganda`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `UKR`,
                description: `Ukraine`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `UMI`,
                description: `United States Minor Outlying Islands`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `URY`,
                description: `Uruguay`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `USA`,
                description: `United States`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `UZB`,
                description: `Uzbekistan`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `VAT`,
                description: `Holy See (Vatican City State)`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `VCT`,
                description: `Saints Vincent And The Grenadines`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `VEN`,
                description: `Venuzuela`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `VGB`,
                description: `"Virgin Islands, British"`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `VIR`,
                description: `"Virgin Islands, US"`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `VNM`,
                description: `Vietnam`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `VUT`,
                description: `Vanuatu`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `WLF`,
                description: `Wallis And Futuna`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `WSM`,
                description: `Samoa`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `XXX`,
                description: `Maklumat Tidak Diperolehi`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `YEM`,
                description: `Yemen`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `YUG`,
                description: `Yugoslavia`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `ZAF`,
                description: `South Africa`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `ZMB`,
                description: `Zambia`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `ZWE`,
                description: `Zimbabwe`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `ZZZ`,
                description: `Lain-lain`,
                active: true,
                createdBy: 'Admin',
            },
        ]);
    }
}
