import BaseSeeder from '@ioc:Adonis/Lucid/Seeder';
import State from 'App/Models/State';

export default class extends BaseSeeder {
    public async run() {
        const uniqueKey = 'description';
        await State.updateOrCreateMany(uniqueKey, [
            {
                code: `00`,
                description: `Tiada Maklumat`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `01`,
                description: `Johor`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `02`,
                description: `Kedah`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `03`,
                description: `Kelantan`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `04`,
                description: `Melaka`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `05`,
                description: `Negeri Sembilan`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `06`,
                description: `Pahang`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `07`,
                description: `Pulau Pinang`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `08`,
                description: `Perak`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `09`,
                description: `Perlis`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `10`,
                description: `Selangor`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `11`,
                description: `Terengganu`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `12`,
                description: `Sabah`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `13`,
                description: `Sarawak`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `14`,
                description: `Wilayah Persekutuan Kuala Lumpur`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `15`,
                description: `Wilayah Persekutuan Labuan`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `16`,
                description: `Wilayah Persekutuan Putrajaya`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `19`,
                description: `Sumatera Barat`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `20`,
                description: `Villanueva`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `21`,
                description: `Victoria`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `22`,
                description: `Western Australia`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `23`,
                description: `New South Wales`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `24`,
                description: `Vienna`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `25`,
                description: `Brussels`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `26`,
                description: `Baridhara Model Town`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `27`,
                description: `Kingdom Of Bahrain`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `28`,
                description: `Sarajevo`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `29`,
                description: `Sao Paulo`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `3`,
                description: `Iwate`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `30`,
                description: `Bandar Seri Begawan`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `31`,
                description: `Ontario`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `32`,
                description: `British Columbia`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `33`,
                description: `Geneva`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `34`,
                description: `Washingtonova`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `35`,
                description: `Las Condes`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `36`,
                description: `Sanlitun`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `37`,
                description: `Sichuen`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `38`,
                description: `Guangdong`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `39`,
                description: `Yunnan`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `40`,
                description: `Shanghai`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `41`,
                description: `Playa`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `42`,
                description: `Berlin`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `43`,
                description: `Cologne`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `44`,
                description: `Frankfurt`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `45`,
                description: `El-Biar`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `46`,
                description: `Giza`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `47`,
                description: `Spain`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `48`,
                description: `Suva`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `49`,
                description: `Rue Benouville`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `50`,
                description: `Belgrave Square`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `51`,
                description: `Coleah Comiche Sud`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `52`,
                description: `Wanchai`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `53`,
                description: `Airport Residential Area`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `54`,
                description: `Budapest`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `55`,
                description: `Jakarta Selatan`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `56`,
                description: `Sumatera Utara`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `57`,
                description: `Riau`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `58`,
                description: `Kalimantan Barat`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `59`,
                description: `Numgambakkam`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `60`,
                description: `Santacruz East`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `61`,
                description: `Chanakyapuri`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `62`,
                description: `Ballsbridge`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `63`,
                description: `Tehran`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `64`,
                description: `Milan`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `65`,
                description: `Rome`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `66`,
                description: `Abdoun`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `67`,
                description: `Kadoma Shi`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `68`,
                description: `Shibuya Ku`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `69`,
                description: `Almaty`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `70`,
                description: `Nairobi`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `71`,
                description: `Khan Daun Penh`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `72`,
                description: `Daedonggang District`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `73`,
                description: `Yongsan Ku`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `74`,
                description: `Daiya`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `75`,
                description: `Lao Pdr`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `76`,
                description: `Beirut`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `77`,
                description: `Hai Andalus`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `78`,
                description: `Colombo`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `79`,
                description: `Soussi`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `80`,
                description: `Polanco`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `81`,
                description: `Zagreb`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `82`,
                description: `Windhoek`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `83`,
                description: `Abuja Fct`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `84`,
                description: `Rotterdam`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `85`,
                description: `Kathmandu`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `86`,
                description: `Brooklyn`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `87`,
                description: `Ruwi`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `88`,
                description: `Islamabad`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `89`,
                description: `Karachi`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `90`,
                description: `San Isidro`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `91`,
                description: `Davao City`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `92`,
                description: `Salcedo Village`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `93`,
                description: `Korobosea`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `94`,
                description: `Warsaw`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `95`,
                description: `West Bay Dafna`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `96`,
                description: `Bucharest`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `97`,
                description: `Moscow`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `98`,
                description: `Luar Negeri`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `99`,
                description: `Lain-lain`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `A0`,
                description: `Jeddah`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `A1`,
                description: `Riyadh`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `A2`,
                description: `Alamarat`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `A3`,
                description: `Dakar`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `A4`,
                description: `Stockholm`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `A5`,
                description: `East Mezzeh`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `A6`,
                description: `Sathorn`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `A7`,
                description: `Phuket`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `A8`,
                description: `Songkhla`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `A9`,
                description: `Dili`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `AA`,
                description: `Madinah`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `AB`,
                description: `Makkah`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `AC`,
                description: `Australian Capital Territory`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `AG`,
                description: `Aragon`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `AH`,
                description: `Anhui`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `AK`,
                description: `Alaska`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `AL`,
                description: `Al Anbar`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `AM`,
                description: `Amman`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `AN`,
                description: `Andalucia`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `AR`,
                description: `Arkansas`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `AS`,
                description: `Asturias`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `AU`,
                description: `Auckland`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `AZ`,
                description: `Arizona`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `B0`,
                description: `Gaziosmanpasa`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `B1`,
                description: `Sisli`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `B2`,
                description: `Taipei`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `B3`,
                description: `New Chomiche`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `B4`,
                description: `Zabeel Road`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `B5`,
                description: `Kiev`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `B6`,
                description: `Massachusetts`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `B7`,
                description: `Illinois`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `B8`,
                description: `Suite 400`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `B9`,
                description: `Florida`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `BA`,
                description: `Bali`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `BB`,
                description: `Babil`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `BC`,
                description: `Banda Acheh`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `BD`,
                description: `Baghdad`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `BI`,
                description: `Balearic Islands`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `BJ`,
                description: `Beijing`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `BR`,
                description: `Brunei`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `BS`,
                description: `Basra`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `BY`,
                description: `Basque Country`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `C `,
                description: `Kaherah`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `C0`,
                description: `New York`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `C1`,
                description: `California`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `C2`,
                description: `Washington`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `C3`,
                description: `Tashkent`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `C4`,
                description: `Chuao`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `C5`,
                description: `Ba Dinh District`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `C6`,
                description: `Ho Chi Minh`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `C7`,
                description: `Sana'a`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `C8`,
                description: `Samdton`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `C9`,
                description: `Hatfield`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `CA`,
                description: `Alexandria`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `CB`,
                description: `Cantabria`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `CD`,
                description: `Canary Islands`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `CI`,
                description: `Christmas Island`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `CL`,
                description: `Castilla La Mancha`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `CO`,
                description: `Colorado`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `CT`,
                description: `Connecticut`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `CX`,
                description: `Catalonia`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `CY`,
                description: `Castilla y L�on`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `D0`,
                description: `Avondale`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `D1`,
                description: `Alabama`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `DA`,
                description: `Duhok`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `DB`,
                description: `Durban`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `DE`,
                description: `Delaware`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `DI`,
                description: `Diyala`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `DQ`,
                description: `Dhi Qar`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `DT`,
                description: `Delft`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `DU`,
                description: `Dushanbe`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `EX`,
                description: `Extremadura`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `F1`,
                description: `Helsinki`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `F2`,
                description: `Turku`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `F3`,
                description: `Tampere`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `F4`,
                description: `Lappeenranta`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `F5`,
                description: `Oulu`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `F6`,
                description: `Vaasa`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `F7`,
                description: `Jyvaskyla`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `F8`,
                description: `Kuopio`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `F9`,
                description: `Rovaniemi`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `Fu`,
                description: `Fukuoka`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `G1`,
                description: `England`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `G2`,
                description: `Northern Ireland`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `G3`,
                description: `Scotland`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `G4`,
                description: `Wales`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `G5`,
                description: `Leeds`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `G6`,
                description: `York`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `GA`,
                description: `Georgia`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `GC`,
                description: `Galicia`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `GN`,
                description: `Ghent`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `HA`,
                description: `Hamilton`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `HB`,
                description: `Halabja`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `HI`,
                description: `Hawaii`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `I2`,
                description: `India`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `I3`,
                description: `Karnataka`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `IA`,
                description: `Iowa`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `ID`,
                description: `Idaho`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `IN`,
                description: `Indiana`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `J1`,
                description: `Hokkaido`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `J2`,
                description: `Aomori`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `J3`,
                description: `Iwate`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `J4`,
                description: `Miyagi`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `J5`,
                description: `Akita`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `J6`,
                description: `Yamagata`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `J7`,
                description: `Fukushima`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `J8`,
                description: `Ibaraki`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `J9`,
                description: `Tochigi`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `JA`,
                description: `Jakarta`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `JB`,
                description: `Jawa Barat`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `JK`,
                description: `Kagawa`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `JO`,
                description: `Osaka`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `JP`,
                description: `Tokyo`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `JS`,
                description: `Jalisco`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `JT`,
                description: `Jawa Timur`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `K7`,
                description: `Jeju`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `K8`,
                description: `Seoul`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `K9`,
                description: `Gyeonggi`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `KA`,
                description: `Karbala`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `KI`,
                description: `Kirkuk`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `KS`,
                description: `Kansas`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `KY`,
                description: `Kentucky`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `LA`,
                description: `Louisiana`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `LK`,
                description: `Lugansk`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `LM`,
                description: `Lamongan`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `LR`,
                description: `La Rioja`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `M1`,
                description: `Male`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `M2`,
                description: `Nay Pyi Taw`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `M3`,
                description: `Yangon`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `MA`,
                description: `Maysan`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `MB`,
                description: `Melbourne`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `MC`,
                description: `Macau`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `MD`,
                description: `Maryland`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `ME`,
                description: `Maine`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `MH`,
                description: `Muthanna`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `MI`,
                description: `Michigan`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `MN`,
                description: `Minnesota`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `MO`,
                description: `Missouri`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `MR`,
                description: `Madrid`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `MS`,
                description: `Mississippi`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `MT`,
                description: `Montana`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `MU`,
                description: `Murcia`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `MX`,
                description: `Mexico City`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `N1`,
                description: `New Jersey`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `NA`,
                description: `Najaf`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `NC`,
                description: `North Carolina`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `ND`,
                description: `North Dakota`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `NE`,
                description: `Nebraska`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `NH`,
                description: `New Hampshire`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `NI`,
                description: `Nineveh`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `NM`,
                description: `New Mexico`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `NR`,
                description: `Navarra`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `NT`,
                description: `Northern Territory`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `NV`,
                description: `Nevada`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `O1`,
                description: `Oudenaarde`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `OB`,
                description: `Oblast`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `OH`,
                description: `Ohio`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `OK`,
                description: `Oklahoma`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `OR`,
                description: `Oregon`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `P1`,
                description: `Prague`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `PA`,
                description: `Pennsylvania`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `PJ`,
                description: `Punjab`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `PP`,
                description: `Peloponnisos`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `QA`,
                description: `Al Qadisiyyah`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `QL`,
                description: `Queensland`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `RI`,
                description: `Rhode Island`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `S0`,
                description: `Singapura`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `SA`,
                description: `South Australia`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `SB`,
                description: `Surabaya`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `SC`,
                description: `South Carolina`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `SD`,
                description: `South Dakota`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `SL`,
                description: `Saladin`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `SR`,
                description: `Siem Reap`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `SU`,
                description: `Sulawesi`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `SX`,
                description: `Shaanxi`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `SY`,
                description: `Sulaymaniyah`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `T1`,
                description: `Bangkok`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `T2`,
                description: `Narathiwat`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `T3`,
                description: `Yala`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `T4`,
                description: `Pattani`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `T5`,
                description: `Nakhon Ratchasima`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `TA`,
                description: `Tasmania`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `TI`,
                description: `Tunis`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `TL`,
                description: `Toulouse`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `TN`,
                description: `Tamil Nadu`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `TS`,
                description: `Tennessee`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `TX`,
                description: `Texas`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `Tz`,
                description: `Dar es Salaam`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `U1`,
                description: `London`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `UT`,
                description: `Utah`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `VA`,
                description: `Virginia`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `VC`,
                description: `Valencia`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `VD`,
                description: `Veldhoven`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `VT`,
                description: `Vermont`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `WA`,
                description: `Wasit`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `WI`,
                description: `Wisconsin`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `WV`,
                description: `West Virginia`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `WY`,
                description: `Wyoming`,
                active: true,
                createdBy: 'Admin',
            },
            {
                code: `ZH`,
                description: `Zhejiang`,
                active: true,
                createdBy: 'Admin',
            },
        ]);
    }
}
