const gradeActingTypeRoutes = [
    { routeName: '1-54', actions: ['list'] },
    { routeName: 'flexi-41', actions: ['list'] },
    { routeName: 'main', actions: ['list'] },
    { routeName: 'employee-list', actions: ['list'] },
    { routeName: 'chosen-employee-list', actions: ['list', 'add'] },
    { routeName: 'candidate-selection-meeting', actions: ['edit'] },
    { routeName: 'interview-info', actions: ['list', 'edit'] },
    { routeName: 'interview-result', actions: ['list'] },
    { routeName: 'interview-result-mark', actions: ['list', 'edit'] },
    { routeName: 'promotion-meeting-result', actions: ['list', 'add', 'edit'] },
    { routeName: 'promotion-meeting-result-detail', actions: ['get', 'edit'] },
    { routeName: 'promotion-meeting-placement', actions: ['add', 'edit'] },
    { routeName: 'promotion-meeting-placement-detail', actions: ['edit'] },
    { routeName: 'employee', actions: ['get'] },
    { routeName: 'postpone', actions: ['list', 'get', 'edit'] },
    { routeName: 'postpone-result', actions: ['list'] },
    { routeName: 'acting-result', actions: ['edit'] },
    { routeName: 'acting-confirmation', actions: ['list', 'get'] },
    { routeName: 'director-certify', actions: ['get', 'edit'] },
    { routeName: 'approve', actions: ['edit'] },
    { routeName: 'support', actions: ['edit'] },
];