import BaseSeeder from '@ioc:Adonis/Lucid/Seeder';
import Grade from 'App/Models/Grade';

export default class GradeSeeder extends BaseSeeder {
    public async run() {
        await Grade.createMany([
            {
                code: 'B17',
                name: 'Pelukis',
                active: true,
                createdBy: 'Admin',
            },
            {
                code: 'B22',
                name: 'Pelukis',
                active: true,
                createdBy: 'Admin',
            },
            {
                code: 'E19',
                name: 'Ekonomi',
                active: true,
                createdBy: 'Admin',
            },
            {
                code: 'E22',
                name: 'Ekonomi',
                active: true,
                createdBy: 'Admin',
            },
            {
                code: 'E26',
                name: 'Ekonomi',
                active: true,
                createdBy: 'Admin',
            },
            {
                code: 'E28',
                name: 'Pembantu Ehwal Ekonomi',
                active: true,
                createdBy: 'Admin',
            },
            {
                code: 'E29',
                name: 'Ekonomi',
                active: true,
                createdBy: 'Admin',
            },
            {
                code: 'E32',
                name: 'Ekonomi',
                active: true,
                createdBy: 'Admin',
            },
            {
                code: 'E38',
                name: 'Ekonomi',
                active: true,
                createdBy: 'Admin',
            },
            {
                code: 'E40',
                name: 'Ekonomi',
                active: true,
                createdBy: 'Admin',
            },
            {
                code: 'E41',
                name: 'Ekonomi',
                active: true,
                createdBy: 'Admin',
            },
            {
                code: 'E44',
                name: 'Ekonomi',
                active: true,
                createdBy: 'Admin',
            },
            {
                code: 'E48',
                name: 'Ekonomi',
                active: true,
                createdBy: 'Admin',
            },
            {
                code: 'E52',
                name: 'Ekonomi',
                active: true,
                createdBy: 'Admin',
            },
            {
                code: 'E54',
                name: 'Ekonomi',
                active: true,
                createdBy: 'Admin',
            },
            {
                code: 'F11',
                name: 'Sistem Maklumat',
                active: true,
                createdBy: 'Admin',
            },
            {
                code: 'F14',
                name: 'Sistem Maklumat',
                active: true,
                createdBy: 'Admin',
            },
            {
                code: 'F17',
                name: 'Sistem Maklumat',
                active: true,
                createdBy: 'Admin',
            },
            {
                code: 'F22',
                name: 'Sistem Maklumat',
                active: true,
                createdBy: 'Admin',
            },
            {
                code: 'F29',
                name: 'Sistem Maklumat',
                active: true,
                createdBy: 'Admin',
            },
            {
                code: 'F32',
                name: 'Sistem Maklumat',
                active: true,
                createdBy: 'Admin',
            },
            {
                code: 'F38',
                name: 'Sistem Maklumat',
                active: true,
                createdBy: 'Admin',
            },
            {
                code: 'F41',
                name: 'Sistem Maklumat',
                active: true,
                createdBy: 'Admin',
            },
            {
                code: 'F44',
                name: 'Sistem Maklumat',
                active: true,
                createdBy: 'Admin',
            },
            {
                code: 'F48',
                name: 'Sistem Maklumat',
                active: true,
                createdBy: 'Admin',
            },
            {
                code: 'F52',
                name: 'Sistem Maklumat',
                active: true,
                createdBy: 'Admin',
            },
            {
                code: 'F54',
                name: 'Sistem Maklumat',
                active: true,
                createdBy: 'Admin',
            },
            {
                code: 'FA29',
                name: 'Sistem Maklumat',
                active: true,
                createdBy: 'Admin',
            },
            {
                code: 'FT17',
                name: 'Sistem Maklumat',
                active: true,
                createdBy: 'Admin',
            },
            {
                code: 'FT19',
                name: 'Sisten Maklumat',
                active: true,
                createdBy: 'Admin',
            },
            {
                code: 'FT22',
                name: 'Sistem Maklumat',
                active: true,
                createdBy: 'Admin',
            },
            {
                code: 'FT26',
                name: 'Sistem Maklumat',
                active: true,
                createdBy: 'Admin',
            },
            {
                code: 'H11',
                name: 'Mahir dan Separuh Mahir',
                active: true,
                createdBy: 'Admin',
            },
            {
                code: 'H14',
                name: 'Pemandu Kenderaan',
                active: true,
                createdBy: 'Admin',
            },
            {
                code: 'J11',
                name: 'Kejuruteraan',
                active: true,
                createdBy: 'Admin',
            },
            {
                code: 'J17',
                name: 'Kejuruteraan',
                active: true,
                createdBy: 'Admin',
            },
            {
                code: 'J21',
                name: 'Kejuruteraan',
                active: true,
                createdBy: 'Admin',
            },
            {
                code: 'J22',
                name: 'Kejuruteraan',
                active: true,
                createdBy: 'Admin',
            },
            {
                code: 'J25',
                name: 'Kejuruteraan',
                active: true,
                createdBy: 'Admin',
            },
            {
                code: 'J26',
                name: 'Kejuruteraan',
                active: true,
                createdBy: 'Admin',
            },
            {
                code: 'J29',
                name: 'Kejuruteraan',
                active: true,
                createdBy: 'Admin',
            },
            {
                code: 'J30',
                name: 'Kejuruteraan',
                active: true,
                createdBy: 'Admin',
            },
            {
                code: 'J35',
                name: 'Kejuruteraan',
                active: true,
                createdBy: 'Admin',
            },
            {
                code: 'J36',
                name: 'Kejuruteraan',
                active: true,
                createdBy: 'Admin',
            },
            {
                code: 'J38',
                name: 'Kejuruteraan',
                active: true,
                createdBy: 'Admin',
            },
            {
                code: 'J41',
                name: 'Kejuruteraan',
                active: true,
                createdBy: 'Admin',
            },
            {
                code: 'J42',
                name: 'Kejuruteraan',
                active: true,
                createdBy: 'Admin',
            },
            {
                code: 'J43',
                name: 'Kejuruteraan',
                active: true,
                createdBy: 'Admin',
            },
            {
                code: 'J44',
                name: 'Kejuruteraan',
                active: true,
                createdBy: 'Admin',
            },
            {
                code: 'J47',
                name: 'Kejuruteraan',
                active: true,
                createdBy: 'Admin',
            },
            {
                code: 'J48',
                name: 'Kejuruteraan',
                active: true,
                createdBy: 'Admin',
            },
            {
                code: 'J52',
                name: 'Jurutera',
                active: true,
                createdBy: 'Admin',
            },
            {
                code: 'J54',
                name: 'Kejuruteraan',
                active: true,
                createdBy: 'Admin',
            },
            {
                code: 'J6',
                name: 'Kejuruteraan',
                active: true,
                createdBy: 'Admin',
            },
            {
                code: 'JA29',
                name: 'Kejuruteraan',
                active: true,
                createdBy: 'Admin',
            },
            {
                code: 'KP11',
                name: 'Keselamatan',
                active: true,
                createdBy: 'Admin',
            },
            {
                code: 'KP14',
                name: 'Keselamatan',
                active: true,
                createdBy: 'Admin',
            },
            {
                code: 'KP27',
                name: 'Keselamatan',
                active: true,
                createdBy: 'Admin',
            },
            {
                code: 'KP48',
                name: 'Keselamatan',
                active: true,
                createdBy: 'Admin',
            },
            {
                code: 'L41',
                name: 'Perundangan',
                active: true,
                createdBy: 'Admin',
            },
            {
                code: 'L48',
                name: 'Perundangan',
                active: true,
                createdBy: 'Admin',
            },
            {
                code: 'N1',
                name: 'Pentadbiran dan Sokongan',
                active: true,
                createdBy: 'Admin',
            },
            {
                code: 'N11',
                name: 'Pentadbiran dan Sokongan',
                active: true,
                createdBy: 'Admin',
            },
            {
                code: 'N12',
                name: 'Pentadbiran dan Sokongan',
                active: true,
                createdBy: 'Admin',
            },
            {
                code: 'N14',
                name: 'Pentadbiran dan Sokongan',
                active: true,
                createdBy: 'Admin',
            },
            {
                code: 'N17',
                name: 'Pentadbiran dan Sokongan',
                active: true,
                createdBy: 'Admin',
            },
            {
                code: 'N19',
                name: 'Pentadbiran dan Sokongan',
                active: true,
                createdBy: 'Admin',
            },
            {
                code: 'N20',
                name: 'Pentadbiran dan Sokongan',
                active: true,
                createdBy: 'Admin',
            },
            {
                code: 'N22',
                name: 'Pentadbiran dan Sokongan',
                active: true,
                createdBy: 'Admin',
            },
            {
                code: 'N26',
                name: 'Pentadbiran dan Sokongan',
                active: true,
                createdBy: 'Admin',
            },
            {
                code: 'N27',
                name: 'Pentadbiran dan Sokongan',
                active: true,
                createdBy: 'Admin',
            },
            {
                code: 'N28',
                name: 'Pentadbiran & Sokongan',
                active: true,
                createdBy: 'Admin',
            },
            {
                code: 'N29',
                name: 'Pentadbiran & Sokongan',
                active: true,
                createdBy: 'Admin',
            },
            {
                code: 'N3',
                name: 'Pentadbiran dan Sokongan',
                active: true,
                createdBy: 'Admin',
            },
            {
                code: 'N32',
                name: 'Pentadbiran dan Sokongan',
                active: true,
                createdBy: 'Admin',
            },
            {
                code: 'N4',
                name: 'Pentadbiran dan Sokongan',
                active: true,
                createdBy: 'Admin',
            },
            {
                code: 'N41',
                name: 'Pentadbiran dan Sokongan',
                active: true,
                createdBy: 'Admin',
            },
            {
                code: 'N44',
                name: 'Pentadbiran dan Sokongan',
                active: true,
                createdBy: 'Admin',
            },
            {
                code: 'N48',
                name: 'Pentadbiran dan Sokongan',
                active: true,
                createdBy: 'Admin',
            },
            {
                code: 'N52',
                name: 'Pentadbiran dan Sokongan',
                active: true,
                createdBy: 'Admin',
            },
            {
                code: 'N54',
                name: 'Pentadbiran dan Sokongan',
                active: true,
                createdBy: 'Admin',
            },
            {
                code: 'OZZ9',
                name: 'Bermasalah',
                active: true,
                createdBy: 'Admin',
            },
            {
                code: 'R1',
                name: 'Mahir Separuh Mahir & Tidak Mahir',
                active: true,
                createdBy: 'Admin',
            },
            {
                code: 'R17',
                name: 'Mahir Separuh Mahir & Tidak Mahir',
                active: true,
                createdBy: 'Admin',
            },
            {
                code: 'R22',
                name: 'Mahir Separuh Mahir & Tidak Mahir',
                active: true,
                createdBy: 'Admin',
            },
            {
                code: 'R24',
                name: 'Mahir Separuh Mahir & Tidak Mahir',
                active: true,
                createdBy: 'Admin',
            },
            {
                code: 'R3',
                name: 'Mahir Separuh Mahir & Tidak Mahir',
                active: true,
                createdBy: 'Admin',
            },
            {
                code: 'R4',
                name: 'Mahir Separuh Mahir & Tidak Mahir',
                active: true,
                createdBy: 'Admin',
            },
            {
                code: 'R6',
                name: 'Mahir Separuh Mahir & Tidak Mahir',
                active: true,
                createdBy: 'Admin',
            },
            {
                code: 'R9',
                name: 'Mahir Separuh Mahir & Tidak Mahir',
                active: true,
                createdBy: 'Admin',
            },
            {
                code: 'S17',
                name: 'Sosial',
                active: true,
                createdBy: 'Admin',
            },
            {
                code: 'S22',
                name: 'Sosial',
                active: true,
                createdBy: 'Admin',
            },
            {
                code: 'S27',
                name: 'Sosial',
                active: true,
                createdBy: 'Admin',
            },
            {
                code: 'S28',
                name: 'Sosial',
                active: true,
                createdBy: 'Admin',
            },
            {
                code: 'S32',
                name: 'Sosial',
                active: true,
                createdBy: 'Admin',
            },
            {
                code: 'S41',
                name: 'Sosial',
                active: true,
                createdBy: 'Admin',
            },
            {
                code: 'S44',
                name: 'Sosial',
                active: true,
                createdBy: 'Admin',
            },
            {
                code: 'S48',
                name: 'Sosial',
                active: true,
                createdBy: 'Admin',
            },
            {
                code: 'S52',
                name: 'Sosial',
                active: true,
                createdBy: 'Admin',
            },
            {
                code: 'S54',
                name: 'Sosial',
                active: true,
                createdBy: 'Admin',
            },
            {
                code: 'VK6',
                name: 'Pengurusan Tertinggi',
                active: true,
                createdBy: 'Admin',
            },
            {
                code: 'VK7',
                name: 'Pengurusan Tertinggi',
                active: true,
                createdBy: 'Admin',
            },
            {
                code: 'VU5',
                name: 'Pengurusan Tertinggi',
                active: true,
                createdBy: 'Admin',
            },
            {
                code: 'VU6',
                name: 'Pengurusan Tertinggi',
                active: true,
                createdBy: 'Admin',
            },
            {
                code: 'VU6-1',
                name: 'Pengurusan Tertinggi (JUSA B)',
                active: true,
                createdBy: 'Admin',
            },
            {
                code: 'VU7',
                name: 'Pengurusan Tertinggi',
                active: true,
                createdBy: 'Admin',
            },
            {
                code: 'W17',
                name: 'Kewangan',
                active: true,
                createdBy: 'Admin',
            },
            {
                code: 'W19',
                name: 'Kewangan',
                active: true,
                createdBy: 'Admin',
            },
            {
                code: 'W22',
                name: 'Kewangan',
                active: true,
                createdBy: 'Admin',
            },
            {
                code: 'W26',
                name: 'Kewangan',
                active: true,
                createdBy: 'Admin',
            },
            {
                code: 'W27',
                name: 'Kewangan',
                active: true,
                createdBy: 'Admin',
            },
            {
                code: 'W29',
                name: 'Kewangan',
                active: true,
                createdBy: 'Admin',
            },
            {
                code: 'W32',
                name: 'Kewangan',
                active: true,
                createdBy: 'Admin',
            },
            {
                code: 'W36',
                name: 'Kewangan',
                active: true,
                createdBy: 'Admin',
            },
            {
                code: 'W41',
                name: 'Kewangan',
                active: true,
                createdBy: 'Admin',
            },
            {
                code: 'W44',
                name: 'Kewangan',
                active: true,
                createdBy: 'Admin',
            },
            {
                code: 'W48',
                name: 'Kewangan',
                active: true,
                createdBy: 'Admin',
            },
            {
                code: 'W52',
                name: 'Kewangan',
                active: true,
                createdBy: 'Admin',
            },
            {
                code: 'W54',
                name: 'Kewangan',
                active: true,
                createdBy: 'Admin',
            },
        ]);
    }
}
