import BaseSeeder from '@ioc:Adonis/Lucid/Seeder'
import PersonalDetail from 'App/Models/PersonalDetail';
import Race from 'App/Models/Race';
import State from 'App/Models/State';
import Religion from 'App/Models/Religion';

//import { DateTime } from 'luxon';

export default class extends BaseSeeder {
  public async run () {
    const state = await State.all();
    const race = await Race.all();
    const religion = await Religion.all();

    await PersonalDetail.createMany([
      {
        birthStateId: state![13].id,
        raceId: race![5].id,
        religionId: religion![1].id,
        mailStateId: state![13].id,
        homeStateId: state![13].id,
        name: "Joseph Joestar",
        alternativeName: "Jojo",
        isMalaysian: true,
        identityDocumentType: "MyKad",
        identityDocumentNumber: "700927131921",
        email: "jojo@mail.com",
        marital: "Berkahwin",
        gender: "Lelaki",
        phoneNumber: "012-8345 6789",
        homeNumber: "082-883 8444",
        birthplace: "Miri",
        isExPoliceOrSoldier: false,
        homeAddress: "Liverpool Club Resident, Kuching",
        homePoscode: "93350",
        homeCity: "Kuching",
        mailAddress: "Liverpool Club Resident, Kuching",
        mailPoscode: "93350",
        mailCity: "Kuching",
        active: true,
        createdBy: "Admin",
        modifiedBy: "Admin",
        
      },
      {
        birthStateId: state![13].id,
        raceId: race![5].id,
        religionId: religion![1].id,
        mailStateId: state![13].id,
        homeStateId: state![13].id,
        name: "Jon Bovi",
        alternativeName: "John Bogovi",
        isMalaysian: true,
        identityDocumentType: "MyKad",
        identityDocumentNumber: "620302138881",
        email: "jonbovi@mail.com",
        marital: "Berkahwin",
        gender: "Lelaki",
        phoneNumber: "012-8345 6789",
        homeNumber: "082-883 8444",
        birthplace: "Kuching",
        isExPoliceOrSoldier: false,
        homeAddress: "New Jersey Height, Kuching",
        homePoscode: "93350",
        homeCity: "Kuching",
        mailAddress: "New Jersey Height, Kuching",
        mailPoscode: "93350",
        mailCity: "Kuching",
        active: true,
        createdBy: "Admin",
        modifiedBy: "Admin",
        
      },
      {
        birthStateId: state![13].id,
        raceId: race![1].id,
        religionId: religion![2].id,
        mailStateId: state![13].id,
        homeStateId: state![13].id,
        name: "Jotaro Kujo",
        alternativeName: "Star Platinum",
        isMalaysian: true,
        identityDocumentType: "MyKad",
        identityDocumentNumber: "701227133925", 
        email: "jotaro@mail.com",
        marital: "Berkahwin",
        gender: "Lelaki",
        phoneNumber: "013 888 9999",
        homeNumber: "082 888 9999",
        birthplace: "Kuching",
        isExPoliceOrSoldier: false,
        homeAddress: "Jalan Star Platinum",
        homePoscode: "93350",
        homeCity: "Kuching",
        mailAddress: "Jalan Star Platinum",
        mailPoscode: "93350",
        mailCity: "Kuching",
        active: true,
        createdBy: "Admin",
        modifiedBy: "Admin",
      },
      {
        birthStateId: state![13].id,
        raceId: race![1].id,
        religionId: religion![2].id,
        mailStateId: state![13].id,
        homeStateId: state![13].id,
        name: "Giorno Giovanna",
        alternativeName: "Gold Experience",
        isMalaysian: true,
        identityDocumentType: "MyKad",
        identityDocumentNumber: "010418133562", 
        email: "giorno@mail.com",
        marital: "Berkahwin",
        gender: "Lelaki",
        phoneNumber: "0111 121 5121",
        homeNumber: "082 1210 5122",
        birthplace: "Kuching",
        isExPoliceOrSoldier: false,
        homeAddress: "Via Gold Experience",
        homePoscode: "93350",
        homeCity: "Kuching",
        mailAddress: "Via Gold Experience",
        mailPoscode: "93350",
        mailCity: "Kuching",
        active: true,
        createdBy: "Admin",
        modifiedBy: "Admin",
      },
      {
        birthStateId: state![13].id,
        raceId: race![1].id,
        religionId: religion![3].id,
        mailStateId: state![13].id,
        homeStateId: state![13].id,
        name: "Jolyne Cujoh",
        alternativeName: "Stone Free",
        isMalaysian: true,
        identityDocumentType: "MyKad",
        identityDocumentNumber: "020216132832", 
        email: "jolyne@mail.com",
        marital: "Berkahwin",
        gender: "Perempuan",
        phoneNumber: "019 888 2002",
        homeNumber: "082 888 9999",
        birthplace: "Kuching",
        isExPoliceOrSoldier: false,
        homeAddress: "Taman Stone Free",
        homePoscode: "93350",
        homeCity: "Kuching",
        mailAddress: "Taman Stone Free",
        mailPoscode: "93350",
        mailCity: "Kuching",
        active: true,
        createdBy: "Admin",
        modifiedBy: "Admin",
      }
      
    ]);
  }
}
