import BaseSeeder from '@ioc:Adonis/Lucid/Seeder';
import District from 'App/Models/District';
import Division from 'App/Models/Division';
import State from 'App/Models/State';

export default class DistrictSeeder extends BaseSeeder {
    public async run() {
        const division = await Division.all();
        const state = await State.all();

        await District.createMany([
            {
                divisionId: division![0].id,
                stateId: state![0].id,
                name: 'Perlis',
                active: true,
                createdBy: 'Admin',
            },
            {
                divisionId: division![1].id,
                stateId: state![1].id,
                name: 'Baling',
                active: true,
                createdBy: 'Admin',
            },
            {
                divisionId: division![1].id,
                stateId: state![1].id,
                name: 'Bandar Baharu',
                active: true,
                createdBy: 'Admin',
            },
            {
                divisionId: division![1].id,
                stateId: state![1].id,
                name: 'Kota Setar',
                active: true,
                createdBy: 'Admin',
            },
            {
                divisionId: division![1].id,
                stateId: state![1].id,
                name: 'Kuala Muda',
                active: true,
                createdBy: 'Admin',
            },
            {
                divisionId: division![1].id,
                stateId: state![1].id,
                name: 'Kubang Pasu',
                active: true,
                createdBy: 'Admin',
            },
            {
                divisionId: division![1].id,
                stateId: state![1].id,
                name: 'Kulim',
                active: true,
                createdBy: 'Admin',
            },
            {
                divisionId: division![1].id,
                stateId: state![1].id,
                name: 'Langkawi',
                active: true,
                createdBy: 'Admin',
            },
            {
                divisionId: division![1].id,
                stateId: state![1].id,
                name: 'Padang Terap',
                active: true,
                createdBy: 'Admin',
            },
            {
                divisionId: division![1].id,
                stateId: state![1].id,
                name: 'Pendang',
                active: true,
                createdBy: 'Admin',
            },
            {
                divisionId: division![1].id,
                stateId: state![1].id,
                name: 'Pokok Sena',
                active: true,
                createdBy: 'Admin',
            },
            {
                divisionId: division![1].id,
                stateId: state![1].id,
                name: 'Sik',
                active: true,
                createdBy: 'Admin',
            },
            {
                divisionId: division![1].id,
                stateId: state![1].id,
                name: 'Yan',
                active: true,
                createdBy: 'Admin',
            },
            {
                divisionId: division![2].id,
                stateId: state![2].id,
                name: 'Barat Daya',
                active: true,
                createdBy: 'Admin',
            },
            {
                divisionId: division![2].id,
                stateId: state![2].id,
                name: 'Seberang Perai Selatan',
                active: true,
                createdBy: 'Admin',
            },
            {
                divisionId: division![2].id,
                stateId: state![2].id,
                name: 'Seberang Perai Utara',
                active: true,
                createdBy: 'Admin',
            },
            {
                divisionId: division![2].id,
                stateId: state![2].id,
                name: 'Seberang Perai Tengah',
                active: true,
                createdBy: 'Admin',
            },
            {
                divisionId: division![2].id,
                stateId: state![2].id,
                name: 'Timur Laut',
                active: true,
                createdBy: 'Admin',
            },
            {
                divisionId: division![3].id,
                stateId: state![3].id,
                name: 'Bagan Datuk',
                active: true,
                createdBy: 'Admin',
            },
            {
                divisionId: division![3].id,
                stateId: state![3].id,
                name: 'Batang Padang',
                active: true,
                createdBy: 'Admin',
            },
            {
                divisionId: division![3].id,
                stateId: state![3].id,
                name: 'Hilir Perak',
                active: true,
                createdBy: 'Admin',
            },
            {
                divisionId: division![3].id,
                stateId: state![3].id,
                name: 'Hulu Perak',
                active: true,
                createdBy: 'Admin',
            },
            {
                divisionId: division![3].id,
                stateId: state![3].id,
                name: 'Kampar',
                active: true,
                createdBy: 'Admin',
            },
            {
                divisionId: division![3].id,
                stateId: state![3].id,
                name: 'Kerian',
                active: true,
                createdBy: 'Admin',
            },
            {
                divisionId: division![3].id,
                stateId: state![3].id,
                name: 'Kinta',
                active: true,
                createdBy: 'Admin',
            },
            {
                divisionId: division![3].id,
                stateId: state![3].id,
                name: 'Kuala Kangsar',
                active: true,
                createdBy: 'Admin',
            },
            {
                divisionId: division![3].id,
                stateId: state![3].id,
                name: 'Larut Dan Matang',
                active: true,
                createdBy: 'Admin',
            },
            {
                divisionId: division![3].id,
                stateId: state![3].id,
                name: 'Manjung',
                active: true,
                createdBy: 'Admin',
            },
            {
                divisionId: division![3].id,
                stateId: state![3].id,
                name: 'Muallim',
                active: true,
                createdBy: 'Admin',
            },
            {
                divisionId: division![3].id,
                stateId: state![3].id,
                name: 'Perak Tengah',
                active: true,
                createdBy: 'Admin',
            },
            {
                divisionId: division![3].id,
                stateId: state![3].id,
                name: 'Selama',
                active: true,
                createdBy: 'Admin',
            },
            {
                divisionId: division![4].id,
                stateId: state![4].id,
                name: 'Gombak',
                active: true,
                createdBy: 'Admin',
            },
            {
                divisionId: division![4].id,
                stateId: state![4].id,
                name: 'Klang',
                active: true,
                createdBy: 'Admin',
            },
            {
                divisionId: division![4].id,
                stateId: state![4].id,
                name: 'Kuala Langat',
                active: true,
                createdBy: 'Admin',
            },
            {
                divisionId: division![4].id,
                stateId: state![4].id,
                name: 'Kuala Selangor',
                active: true,
                createdBy: 'Admin',
            },
            {
                divisionId: division![4].id,
                stateId: state![4].id,
                name: 'Petaling',
                active: true,
                createdBy: 'Admin',
            },
            {
                divisionId: division![4].id,
                stateId: state![4].id,
                name: 'Sabak Bernam',
                active: true,
                createdBy: 'Admin',
            },
            {
                divisionId: division![4].id,
                stateId: state![4].id,
                name: 'Sepang',
                active: true,
                createdBy: 'Admin',
            },
            {
                divisionId: division![4].id,
                stateId: state![4].id,
                name: 'Ulu Langat',
                active: true,
                createdBy: 'Admin',
            },
            {
                divisionId: division![4].id,
                stateId: state![4].id,
                name: 'Ulu Selangor',
                active: true,
                createdBy: 'Admin',
            },
            {
                divisionId: division![5].id,
                stateId: state![5].id,
                name: 'Jelebu',
                active: true,
                createdBy: 'Admin',
            },
            {
                divisionId: division![5].id,
                stateId: state![5].id,
                name: 'Jembol',
                active: true,
                createdBy: 'Admin',
            },
            {
                divisionId: division![5].id,
                stateId: state![5].id,
                name: 'Kuala Pilah',
                active: true,
                createdBy: 'Admin',
            },
            {
                divisionId: division![5].id,
                stateId: state![5].id,
                name: 'Port Dickson',
                active: true,
                createdBy: 'Admin',
            },
            {
                divisionId: division![5].id,
                stateId: state![5].id,
                name: 'Rembau',
                active: true,
                createdBy: 'Admin',
            },
            {
                divisionId: division![5].id,
                stateId: state![5].id,
                name: 'Seremban',
                active: true,
                createdBy: 'Admin',
            },
            {
                divisionId: division![5].id,
                stateId: state![5].id,
                name: 'Tampin',
                active: true,
                createdBy: 'Admin',
            },
            {
                divisionId: division![6].id,
                stateId: state![6].id,
                name: 'Alor Gajah',
                active: true,
                createdBy: 'Admin',
            },
            {
                divisionId: division![6].id,
                stateId: state![6].id,
                name: 'Jasin',
                active: true,
                createdBy: 'Admin',
            },
            {
                divisionId: division![6].id,
                stateId: state![6].id,
                name: 'Melaka Tengah',
                active: true,
                createdBy: 'Admin',
            },
            {
                divisionId: division![7].id,
                stateId: state![7].id,
                name: 'Batu Pahat',
                active: true,
                createdBy: 'Admin',
            },
            {
                divisionId: division![7].id,
                stateId: state![7].id,
                name: 'Johor Bahru',
                active: true,
                createdBy: 'Admin',
            },
            {
                divisionId: division![7].id,
                stateId: state![7].id,
                name: 'Kluang',
                active: true,
                createdBy: 'Admin',
            },
            {
                divisionId: division![7].id,
                stateId: state![7].id,
                name: 'Kota Tinggi',
                active: true,
                createdBy: 'Admin',
            },
            {
                divisionId: division![7].id,
                stateId: state![7].id,
                name: 'Kulai',
                active: true,
                createdBy: 'Admin',
            },
            {
                divisionId: division![7].id,
                stateId: state![7].id,
                name: 'Mersing',
                active: true,
                createdBy: 'Admin',
            },
            {
                divisionId: division![7].id,
                stateId: state![7].id,
                name: 'Muar',
                active: true,
                createdBy: 'Admin',
            },
            {
                divisionId: division![7].id,
                stateId: state![7].id,
                name: 'Pontian',
                active: true,
                createdBy: 'Admin',
            },
            {
                divisionId: division![7].id,
                stateId: state![7].id,
                name: 'Segamat',
                active: true,
                createdBy: 'Admin',
            },
            {
                divisionId: division![7].id,
                stateId: state![7].id,
                name: 'Tangkak',
                active: true,
                createdBy: 'Admin',
            },
            {
                divisionId: division![8].id,
                stateId: state![8].id,
                name: 'Bachok',
                active: true,
                createdBy: 'Admin',
            },
            {
                divisionId: division![8].id,
                stateId: state![8].id,
                name: 'Gua Musang ',
                active: true,
                createdBy: 'Admin',
            },
            {
                divisionId: division![8].id,
                stateId: state![8].id,
                name: 'Jeli',
                active: true,
                createdBy: 'Admin',
            },
            {
                divisionId: division![8].id,
                stateId: state![8].id,
                name: 'Kecil Lojing',
                active: true,
                createdBy: 'Admin',
            },
            {
                divisionId: division![8].id,
                stateId: state![8].id,
                name: 'Kota Bharu',
                active: true,
                createdBy: 'Admin',
            },
            {
                divisionId: division![8].id,
                stateId: state![8].id,
                name: 'Kuala Krai',
                active: true,
                createdBy: 'Admin',
            },
            {
                divisionId: division![8].id,
                stateId: state![8].id,
                name: 'Machang',
                active: true,
                createdBy: 'Admin',
            },
            {
                divisionId: division![8].id,
                stateId: state![8].id,
                name: 'Pasir Mas',
                active: true,
                createdBy: 'Admin',
            },
            {
                divisionId: division![8].id,
                stateId: state![8].id,
                name: 'Pasir Puteh',
                active: true,
                createdBy: 'Admin',
            },
            {
                divisionId: division![8].id,
                stateId: state![8].id,
                name: 'Tanah Merah',
                active: true,
                createdBy: 'Admin',
            },
            {
                divisionId: division![8].id,
                stateId: state![8].id,
                name: 'Tumpat',
                active: true,
                createdBy: 'Admin',
            },
            {
                divisionId: division![9].id,
                stateId: state![9].id,
                name: 'Besut',
                active: true,
                createdBy: 'Admin',
            },
            {
                divisionId: division![9].id,
                stateId: state![9].id,
                name: 'Dungun',
                active: true,
                createdBy: 'Admin',
            },
            {
                divisionId: division![9].id,
                stateId: state![9].id,
                name: 'Hulu Terengganu',
                active: true,
                createdBy: 'Admin',
            },
            {
                divisionId: division![9].id,
                stateId: state![9].id,
                name: 'Kemaman',
                active: true,
                createdBy: 'Admin',
            },
            {
                divisionId: division![9].id,
                stateId: state![9].id,
                name: 'Kuala Nerus',
                active: true,
                createdBy: 'Admin',
            },
            {
                divisionId: division![9].id,
                stateId: state![9].id,
                name: 'Kuala Terengganu',
                active: true,
                createdBy: 'Admin',
            },
            {
                divisionId: division![9].id,
                stateId: state![9].id,
                name: 'Marang',
                active: true,
                createdBy: 'Admin',
            },
            {
                divisionId: division![9].id,
                stateId: state![9].id,
                name: 'Setiu',
                active: true,
                createdBy: 'Admin',
            },
            {
                divisionId: division![10].id,
                stateId: state![10].id,
                name: 'Bentong',
                active: true,
                createdBy: 'Admin',
            },
            {
                divisionId: division![10].id,
                stateId: state![10].id,
                name: 'Bera',
                active: true,
                createdBy: 'Admin',
            },
            {
                divisionId: division![10].id,
                stateId: state![10].id,
                name: 'Cameron Highlands',
                active: true,
                createdBy: 'Admin',
            },
            {
                divisionId: division![10].id,
                stateId: state![10].id,
                name: 'Jerantut',
                active: true,
                createdBy: 'Admin',
            },
            {
                divisionId: division![10].id,
                stateId: state![10].id,
                name: 'Kuantan',
                active: true,
                createdBy: 'Admin',
            },
            {
                divisionId: division![10].id,
                stateId: state![10].id,
                name: 'Lipis',
                active: true,
                createdBy: 'Admin',
            },
            {
                divisionId: division![10].id,
                stateId: state![10].id,
                name: 'Maran',
                active: true,
                createdBy: 'Admin',
            },
            {
                divisionId: division![10].id,
                stateId: state![10].id,
                name: 'Pekan',
                active: true,
                createdBy: 'Admin',
            },
            {
                divisionId: division![10].id,
                stateId: state![10].id,
                name: 'Raub',
                active: true,
                createdBy: 'Admin',
            },
            {
                divisionId: division![10].id,
                stateId: state![10].id,
                name: 'Temerloh',
                active: true,
                createdBy: 'Admin',
            },
            {
                divisionId: division![10].id,
                stateId: state![10].id,
                name: 'Rompin',
                active: true,
                createdBy: 'Admin',
            },
            {
                divisionId: division![11].id,
                stateId: state![11].id,
                name: 'Beaufort',
                active: true,
                createdBy: 'Admin',
            },
            {
                divisionId: division![12].id,
                stateId: state![11].id,
                name: 'Beluran',
                active: true,
                createdBy: 'Admin',
            },
            {
                divisionId: division![11].id,
                stateId: state![11].id,
                name: 'Keningau',
                active: true,
                createdBy: 'Admin',
            },
            {
                divisionId: division![11].id,
                stateId: state![11].id,
                name: 'Kinabatangan',
                active: true,
                createdBy: 'Admin',
            },
            {
                divisionId: division![13].id,
                stateId: state![11].id,
                name: 'Kota Belud',
                active: true,
                createdBy: 'Admin',
            },
            {
                divisionId: division![13].id,
                stateId: state![11].id,
                name: 'Kota Kinabalu',
                active: true,
                createdBy: 'Admin',
            },
            {
                divisionId: division![14].id,
                stateId: state![11].id,
                name: 'Kota Marudu',
                active: true,
                createdBy: 'Admin',
            },
            {
                divisionId: division![11].id,
                stateId: state![11].id,
                name: 'Kuala Penyu',
                active: true,
                createdBy: 'Admin',
            },
            {
                divisionId: division![14].id,
                stateId: state![11].id,
                name: 'Kudat',
                active: true,
                createdBy: 'Admin',
            },
            {
                divisionId: division![15].id,
                stateId: state![11].id,
                name: 'Kunak',
                active: true,
                createdBy: 'Admin',
            },
            {
                divisionId: division![15].id,
                stateId: state![11].id,
                name: 'Lahad Datu',
                active: true,
                createdBy: 'Admin',
            },
            {
                divisionId: division![11].id,
                stateId: state![11].id,
                name: 'Nabawan',
                active: true,
                createdBy: 'Admin',
            },
            {
                divisionId: division![13].id,
                stateId: state![11].id,
                name: 'Papar',
                active: true,
                createdBy: 'Admin',
            },
            {
                divisionId: division![13].id,
                stateId: state![11].id,
                name: 'Penampang',
                active: true,
                createdBy: 'Admin',
            },
            {
                divisionId: division![13].id,
                stateId: state![11].id,
                name: 'Putatan',
                active: true,
                createdBy: 'Admin',
            },
            {
                divisionId: division![14].id,
                stateId: state![11].id,
                name: 'Pitas',
                active: true,
                createdBy: 'Admin',
            },
            {
                divisionId: division![13].id,
                stateId: state![11].id,
                name: 'Ranau',
                active: true,
                createdBy: 'Admin',
            },
            {
                divisionId: division![15].id,
                stateId: state![11].id,
                name: 'Sandakan',
                active: true,
                createdBy: 'Admin',
            },
            {
                divisionId: division![12].id,
                stateId: state![11].id,
                name: 'Semporna',
                active: true,
                createdBy: 'Admin',
            },
            {
                divisionId: division![11].id,
                stateId: state![11].id,
                name: 'Sipitang',
                active: true,
                createdBy: 'Admin',
            },
            {
                divisionId: division![11].id,
                stateId: state![11].id,
                name: 'Tambunan',
                active: true,
                createdBy: 'Admin',
            },
            {
                divisionId: division![15].id,
                stateId: state![11].id,
                name: 'Tawau',
                active: true,
                createdBy: 'Admin',
            },
            {
                divisionId: division![12].id,
                stateId: state![11].id,
                name: 'Telupid',
                active: true,
                createdBy: 'Admin',
            },
            {
                divisionId: division![11].id,
                stateId: state![11].id,
                name: 'Tenom',
                active: true,
                createdBy: 'Admin',
            },
            {
                divisionId: division![12].id,
                stateId: state![11].id,
                name: 'Tongod',
                active: true,
                createdBy: 'Admin',
            },
            {
                divisionId: division![13].id,
                stateId: state![11].id,
                name: 'Tuara',
                active: true,
                createdBy: 'Admin',
            },
            {
                divisionId: division![16].id,
                stateId: state![12].id,
                name: 'Kuching',
                active: true,
                createdBy: 'Admin',
            },
            {
                divisionId: division![16].id,
                stateId: state![12].id,
                name: 'Bau',
                active: true,
                createdBy: 'Admin',
            },
            {
                divisionId: division![16].id,
                stateId: state![12].id,
                name: 'Lundu',
                active: true,
                createdBy: 'Admin',
            },
            {
                divisionId: division![17].id,
                stateId: state![12].id,
                name: 'Samarahan',
                active: true,
                createdBy: 'Admin',
            },
            {
                divisionId: division![17].id,
                stateId: state![12].id,
                name: 'Asajaya',
                active: true,
                createdBy: 'Admin',
            },
            {
                divisionId: division![17].id,
                stateId: state![12].id,
                name: 'Simunjan',
                active: true,
                createdBy: 'Admin',
            },
            {
                divisionId: division![17].id,
                stateId: state![12].id,
                name: 'Sebuyau',
                active: true,
                createdBy: 'Admin',
            },
            {
                divisionId: division![17].id,
                stateId: state![12].id,
                name: 'Gedong',
                active: true,
                createdBy: 'Admin',
            },
            {
                divisionId: division![18].id,
                stateId: state![12].id,
                name: 'Serian',
                active: true,
                createdBy: 'Admin',
            },
            {
                divisionId: division![18].id,
                stateId: state![12].id,
                name: 'Siburan',
                active: true,
                createdBy: 'Admin',
            },
            {
                divisionId: division![18].id,
                stateId: state![12].id,
                name: 'Tebedu',
                active: true,
                createdBy: 'Admin',
            },
            {
                divisionId: division![19].id,
                stateId: state![12].id,
                name: 'Sri Aman',
                active: true,
                createdBy: 'Admin',
            },
            {
                divisionId: division![19].id,
                stateId: state![12].id,
                name: 'Lingga',
                active: true,
                createdBy: 'Admin',
            },
            {
                divisionId: division![19].id,
                stateId: state![12].id,
                name: 'Pantu',
                active: true,
                createdBy: 'Admin',
            },
            {
                divisionId: division![19].id,
                stateId: state![12].id,
                name: 'Lubok Antu',
                active: true,
                createdBy: 'Admin',
            },
            {
                divisionId: division![20].id,
                stateId: state![12].id,
                name: 'Betong',
                active: true,
                createdBy: 'Admin',
            },
            {
                divisionId: division![20].id,
                stateId: state![12].id,
                name: 'Saratok',
                active: true,
                createdBy: 'Admin',
            },
            {
                divisionId: division![20].id,
                stateId: state![12].id,
                name: 'Pusa',
                active: true,
                createdBy: 'Admin',
            },
            {
                divisionId: division![20].id,
                stateId: state![12].id,
                name: 'Kabong',
                active: true,
                createdBy: 'Admin',
            },
            {
                divisionId: division![21].id,
                stateId: state![12].id,
                name: 'Sarikei',
                active: true,
                createdBy: 'Admin',
            },
            {
                divisionId: division![21].id,
                stateId: state![12].id,
                name: 'Maradong',
                active: true,
                createdBy: 'Admin',
            },
            {
                divisionId: division![21].id,
                stateId: state![12].id,
                name: 'Pakan',
                active: true,
                createdBy: 'Admin',
            },
            {
                divisionId: division![21].id,
                stateId: state![12].id,
                name: 'Julau',
                active: true,
                createdBy: 'Admin',
            },
            {
                divisionId: division![22].id,
                stateId: state![12].id,
                name: 'Siburan',
                active: true,
                createdBy: 'Admin',
            },
            {
                divisionId: division![22].id,
                stateId: state![12].id,
                name: 'Kanowit',
                active: true,
                createdBy: 'Admin',
            },
            {
                divisionId: division![22].id,
                stateId: state![12].id,
                name: 'Selangau',
                active: true,
                createdBy: 'Admin',
            },
            {
                divisionId: division![23].id,
                stateId: state![12].id,
                name: 'Mukah',
                active: true,
                createdBy: 'Admin',
            },
            {
                divisionId: division![23].id,
                stateId: state![12].id,
                name: 'Dalat',
                active: true,
                createdBy: 'Admin',
            },
            {
                divisionId: division![23].id,
                stateId: state![12].id,
                name: 'Daro',
                active: true,
                createdBy: 'Admin',
            },
            {
                divisionId: division![23].id,
                stateId: state![12].id,
                name: 'Matu',
                active: true,
                createdBy: 'Admin',
            },
            {
                divisionId: division![23].id,
                stateId: state![12].id,
                name: 'Tanjung Manis',
                active: true,
                createdBy: 'Admin',
            },
            {
                divisionId: division![24].id,
                stateId: state![12].id,
                name: 'Bintulu',
                active: true,
                createdBy: 'Admin',
            },
            {
                divisionId: division![24].id,
                stateId: state![12].id,
                name: 'Sebauh',
                active: true,
                createdBy: 'Admin',
            },
            {
                divisionId: division![24].id,
                stateId: state![12].id,
                name: 'Tatau',
                active: true,
                createdBy: 'Admin',
            },
            {
                divisionId: division![25].id,
                stateId: state![12].id,
                name: 'Kapit',
                active: true,
                createdBy: 'Admin',
            },
            {
                divisionId: division![25].id,
                stateId: state![12].id,
                name: 'Belaga',
                active: true,
                createdBy: 'Admin',
            },
            {
                divisionId: division![25].id,
                stateId: state![12].id,
                name: 'Song',
                active: true,
                createdBy: 'Admin',
            },
            {
                divisionId: division![25].id,
                stateId: state![12].id,
                name: 'Bukit Mabong',
                active: true,
                createdBy: 'Admin',
            },
            {
                divisionId: division![26].id,
                stateId: state![12].id,
                name: 'Miri',
                active: true,
                createdBy: 'Admin',
            },
            {
                divisionId: division![26].id,
                stateId: state![12].id,
                name: 'Subis',
                active: true,
                createdBy: 'Admin',
            },
            {
                divisionId: division![26].id,
                stateId: state![12].id,
                name: 'Beluru',
                active: true,
                createdBy: 'Admin',
            },
            {
                divisionId: division![26].id,
                stateId: state![12].id,
                name: 'Marudi',
                active: true,
                createdBy: 'Admin',
            },
            {
                divisionId: division![26].id,
                stateId: state![12].id,
                name: 'Telang Usan',
                active: true,
                createdBy: 'Admin',
            },
            {
                divisionId: division![27].id,
                stateId: state![12].id,
                name: 'Limbang',
                active: true,
                createdBy: 'Admin',
            },
            {
                divisionId: division![27].id,
                stateId: state![12].id,
                name: 'Lawas',
                active: true,
                createdBy: 'Admin',
            },
            {
                divisionId: division![28].id,
                stateId: state![13].id,
                name: 'Wilayah Persekutuan Kuala Lumpur',
                active: true,
                createdBy: 'Admin',
            },
            {
                divisionId: division![29].id,
                stateId: state![14].id,
                name: 'Wilayah Persekutuan Labuan',
                active: true,
                createdBy: 'Admin',
            },
            {
                divisionId: division![30].id,
                stateId: state![15].id,
                name: 'Wilayah Persekutuan Putrajaya',
                active: true,
                createdBy: 'Admin',
            },
        ]);
    }
}
