import BaseSeeder from '@ioc:Adonis/Lucid/Seeder';
import Unit from 'App/Models/Unit';
import Department from 'App/Models/Department';
import Section from 'App/Models/Section';
export default class UnitSeeder extends BaseSeeder {
    public async run() {
        const department = await Department.all();
        const section = await Section.all();

        await Unit.createMany([
            {
                departmentId: department![0].id,
                sectionId: section![0].id,
                name: 'Unit Kumpulan Wang Mengurus (KWM)',
                active: true,
                createdBy: 'Admin',
            },
            {
                departmentId: department![0].id,
                sectionId: section![0].id,
                name: 'Unit Kumpulan Wang Pembangunan (KWP)',
                active: true,
                createdBy: 'Admin',
            },
            {
                departmentId: department![0].id,
                sectionId: section![0].id,
                name: 'Unit Hal Ehwal Gaji Dan Tuntutan',
                active: true,
                createdBy: 'Admin',
            },
            {
                departmentId: department![0].id,
                sectionId: section![0].id,
                name: 'Unit Aset ',
                active: true,
                createdBy: 'Admin',
            },
            {
                departmentId: department![0].id,
                sectionId: section![0].id,
                name: 'Unit Akaun Persatuan Nelayan',
                active: true,
                createdBy: 'Admin',
            },
            {
                departmentId: department![0].id,
                sectionId: section![1].id,
                name: 'Unit Perolehan',
                active: true,
                createdBy: 'Admin',
            },
            {
                departmentId: department![0].id,
                sectionId: section![1].id,
                name: 'Unit Belanjawan',
                active: true,
                createdBy: 'Admin',
            },
            {
                departmentId: department![0].id,
                sectionId: section![1].id,
                name: ' Unit Kawalan Kredit',
                active: true,
                createdBy: 'Admin',
            },
            {
                departmentId: department![0].id,
                sectionId: section![1].id,
                name: 'Unit Pentadbiran Am',
                active: true,
                createdBy: 'Admin',
            },
            {
                departmentId: department![0].id,
                sectionId: section![1].id,
                name: 'Unit Pelaburan',
                active: true,
                createdBy: 'Admin',
            },
            {
                departmentId: department![0].id,
                sectionId: section![2].id,
                name: 'Seksyen Pengurusan Belanjawan',
                active: true,
                createdBy: 'Admin',
            },
            {
                departmentId: department![1].id,
                sectionId: section![3].id,
                name: 'Seksyen Kawalselia',
                active: true,
                createdBy: 'Admin',
            },
            {
                departmentId: department![1].id,
                sectionId: section![4].id,
                name: 'Seksyen Kualiti',
                active: true,
                createdBy: 'Admin',
            },
            {
                departmentId: department![1].id,
                sectionId: section![5].id,
                name: 'Seksyen Penguatkuasaan',
                active: true,
                createdBy: 'Admin',
            },
            {
                departmentId: department![2].id,
                sectionId: section![6].id,
                name: 'Seksyen Pembangunan Aplikasi & Pangkalan Data',
                active: true,
                createdBy: 'Admin',
            },
            {
                departmentId: department![2].id,
                sectionId: section![7].id,
                name: 'Seksyen Sokongan & Operasi',
                active: true,
                createdBy: 'Admin',
            },
            {
                departmentId: department![2].id,
                sectionId: section![8].id,
                name: 'Unit Pentadbiran Am',
                active: true,
                createdBy: 'Admin',
            },
            {
                departmentId: department![3].id,
                sectionId: section![9].id,
                name: 'Seksyen Kejuruteraan Sivil & Struktur',
                active: true,
                createdBy: 'Admin',
            },
            {
                departmentId: department![3].id,
                sectionId: section![10].id,
                name: 'Seksyen Kejuruteraan Mekanikal & Elektrikal',
                active: true,
                createdBy: 'Admin',
            },
            {
                departmentId: department![3].id,
                sectionId: section![11].id,
                name: 'Seksyen Ukur Bahan',
                active: true,
                createdBy: 'Admin',
            },
            {
                departmentId: department![3].id,
                sectionId: section![12].id,
                name: 'Pentadbiran Am',
                active: true,
                createdBy: 'Admin',
            },
            {
                departmentId: department![4].id,
                sectionId: section![13].id,
                name: 'Seksyen Pengurusan Sumber Manusia',
                active: true,
                createdBy: 'Admin',
            },
            {
                departmentId: department![4].id,
                sectionId: section![14].id,
                name: 'Seksyen Pentadbiran',
                active: true,
                createdBy: 'Admin',
            },
            {
                departmentId: department![4].id,
                sectionId: section![15].id,
                name: 'Seksyen Latihan dan Kompetensi',
                active: true,
                createdBy: 'Admin',
            },
            {
                departmentId: department![4].id,
                sectionId: section![15].id,
                name: 'Unit Latihan dan Rekod',
                active: true,
                createdBy: 'Admin',
            },
            {
                departmentId: department![4].id,
                sectionId: section![15].id,
                name: 'Unit Sokong Latihan',
                active: true,
                createdBy: 'Admin',
            },
            {
                departmentId: department![4].id,
                sectionId: section![15].id,
                name: 'Unit Kompetensi & Pentadbiran',
                active: true,
                createdBy: 'Admin',
            },
            {
                departmentId: department![5].id,
                sectionId: section![16].id,
                name: 'Seksyen Perancangan Strategik Dan Khidmat Am',
                active: true,
                createdBy: 'Admin',
            },
            {
                departmentId: department![5].id,
                sectionId: section![17].id,
                name: 'Seksyen Pembangunan Infrastruktur Kompleks/Labuhan/Jeti',
                active: true,
                createdBy: 'Admin',
            },
            {
                departmentId: department![5].id,
                sectionId: section![18].id,
                name: 'Seksyen Pengurusan Kompleks/Labuhan/PPI',
                active: true,
                createdBy: 'Admin',
            },
            {
                departmentId: department![6].id,
                sectionId: section![19].id,
                name: 'Seksyen Pengurusan Maklumat Pemasaran',
                active: true,
                createdBy: 'Admin',
            },
            {
                departmentId: department![6].id,
                sectionId: section![20].id,
                name: 'Seksyen Pengukuhan Pasaran',
                active: true,
                createdBy: 'Admin',
            },
            {
                departmentId: department![6].id,
                sectionId: section![21].id,
                name: 'Seksyen Khidmat Sokongan Pemasaran',
                active: true,
                createdBy: 'Admin',
            },
            {
                departmentId: department![6].id,
                sectionId: section![22].id,
                name: 'Seksyen Komoditi Akuakultur',
                active: true,
                createdBy: 'Admin',
            },
            {
                departmentId: department![6].id,
                sectionId: section![23].id,
                name: 'Seksyen Pelesenan',
                active: true,
                createdBy: 'Admin',
            },
            {
                departmentId: department![7].id,
                sectionId: section![24].id,
                name: 'Seksyen Pembangunan Usahawan, Perniagaan & Pentadbiran Am',
                active: true,
                createdBy: 'Admin',
            },
            {
                departmentId: department![7].id,
                sectionId: section![25].id,
                name: 'Seksyen Pembangunan Industri Proses',
                active: true,
                createdBy: 'Admin',
            },
            {
                departmentId: department![7].id,
                sectionId: section![26].id,
                name: 'Seksyen Pembangunan Perikanan Laut',
                active: true,
                createdBy: 'Admin',
            },
            {
                departmentId: department![8].id,
                sectionId: section![27].id,
                name: 'Seksyen Pembangunan Institusi Nelayan',
                active: true,
                createdBy: 'Admin',
            },
            {
                departmentId: department![9].id,
                sectionId: section![28].id,
                name: 'Seksyen Perancangan Strategik & Antarabangsa (PSA)',
                active: true,
                createdBy: 'Admin',
            },
            {
                departmentId: department![9].id,
                sectionId: section![29].id,
                name: 'Seksyen Pembangunan (PEM)',
                active: true,
                createdBy: 'Admin',
            },
            {
                departmentId: department![9].id,
                sectionId: section![30].id,
                name: 'Seksyen Hal Ehwal Korporat (HEK)',
                active: true,
                createdBy: 'Admin',
            },
            {
                departmentId: department![9].id,
                sectionId: section![31].id,
                name: 'Seksyen Pengurusan Data (PD)',
                active: true,
                createdBy: 'Admin',
            },
            {
                departmentId: department![10].id,
                sectionId: section![32].id,
                name: 'Unit Undang-Undang',
                active: true,
                createdBy: 'Admin',
            },
            {
                departmentId: department![11].id,
                sectionId: section![33].id,
                name: 'Unit Komunikasi Korporat',
                active: true,
                createdBy: 'Admin',
            },
            {
                departmentId: department![12].id,
                sectionId: section![34].id,
                name: 'Unit Pengesanan, Pengesahan & Tatatertib',
                active: true,
                createdBy: 'Admin',
            },
            {
                departmentId: department![12].id,
                sectionId: section![34].id,
                name: 'Unit Pengukuhan Integriti',
                active: true,
                createdBy: 'Admin',
            },
            {
                departmentId: department![12].id,
                sectionId: section![34].id,
                name: 'Unit Pematuhan dan Tadbir Urus',
                active: true,
                createdBy: 'Admin',
            },
            {
                departmentId: department![12].id,
                sectionId: section![34].id,
                name: 'Unit Pengurusan Aduan, Data Statistik dan Pentadbiran Am',
                active: true,
                createdBy: 'Admin',
            },
            {
                departmentId: department![13].id,
                sectionId: section![35].id,
                name: 'Seksyen Audit Kewangana',
                active: true,
                createdBy: 'Admin',
            },
            {
                departmentId: department![13].id,
                sectionId: section![36].id,
                name: 'Seksyen Audit Prestasi ',
                active: true,
                createdBy: 'Admin',
            },
            {
                departmentId: department![13].id,
                sectionId: section![37].id,
                name: 'Unit Urusetia',
                active: true,
                createdBy: 'Admin',
            },
            {
                departmentId: department![14].id,
                sectionId: section![38].id,
                name: 'Unit Perundangan Persatuan Nelayan',
                active: true,
                createdBy: 'Admin',
            },
            {
                departmentId: department![14].id,
                sectionId: section![38].id,
                name: 'Unit Pengurusan Persatuan Nelayan',
                active: true,
                createdBy: 'Admin',
            },
            {
                departmentId: department![14].id,
                sectionId: section![38].id,
                name: 'Unit Akaun dan Audit Persatuan Nelayan',
                active: true,
                createdBy: 'Admin',
            },
            {
                departmentId: department![14].id,
                sectionId: section![38].id,
                name: 'Unit Pentadbiran ',
                active: true,
                createdBy: 'Admin',
            },
        ]);
    }
}
