import BaseSeeder from '@ioc:Adonis/Lucid/Seeder';
import Position from 'App/Models/Position';
import Grade from 'App/Models/Grade';

export default class PositionSeeder extends BaseSeeder {
    public async run() {
        const grade = await Grade.all();

        await Position.createMany([
            {
                gradeId: grade![0].id,
                name: 'Pelukis',
                active: true,
                createdBy: 'Admin',
            },
            {
                gradeId: grade![1].id,
                name: 'Pelukis',
                active: true,
                createdBy: 'Admin',
            },
            {
                gradeId: grade![2].id,
                name: 'Pegawai Ekonomi',
                active: true,
                createdBy: 'Admin',
            },
            {
                gradeId: grade![3].id,
                name: 'Pegawai Ekonomi',
                active: true,
                createdBy: 'Admin',
            },
            {
                gradeId: grade![4].id,
                name: 'Pegawai Ekonomi',
                active: true,
                createdBy: 'Admin',
            },
            {
                gradeId: grade![5].id,
                name: 'Pembantu Ehwal Ekonomi',
                active: true,
                createdBy: 'Admin',
            },
            {
                gradeId: grade![6].id,
                name: 'Pegawai Ekonomi',
                active: true,
                createdBy: 'Admin',
            },
            {
                gradeId: grade![7].id,
                name: 'Pegawai Ekonomi',
                active: true,
                createdBy: 'Admin',
            },
            {
                gradeId: grade![8].id,
                name: 'Pegawai Ekonomi',
                active: true,
                createdBy: 'Admin',
            },
            {
                gradeId: grade![9].id,
                name: 'Pegawai Ekonomi',
                active: true,
                createdBy: 'Admin',
            },
            {
                gradeId: grade![10].id,
                name: 'Pegawai Ekonomi',
                active: true,
                createdBy: 'Admin',
            },
            {
                gradeId: grade![11].id,
                name: 'Pegawai Ekonomi',
                active: true,
                createdBy: 'Admin',
            },
            {
                gradeId: grade![12].id,
                name: 'Pegawai Ekonomi',
                active: true,
                createdBy: 'Admin',
            },
            {
                gradeId: grade![13].id,
                name: 'Pegawai Ekonomi',
                active: true,
                createdBy: 'Admin',
            },
            {
                gradeId: grade![14].id,
                name: 'Pegawai Ekonomi',
                active: true,
                createdBy: 'Admin',
            },
            {
                gradeId: grade![15].id,
                name: 'Pegawai Sistem Maklumat',
                active: true,
                createdBy: 'Admin',
            },
            {
                gradeId: grade![16].id,
                name: 'Pegawai Sistem Maklumat',
                active: true,
                createdBy: 'Admin',
            },
            {
                gradeId: grade![17].id,
                name: 'Pegawai Sistem Maklumat',
                active: true,
                createdBy: 'Admin',
            },
            {
                gradeId: grade![18].id,
                name: 'Pegawai Sistem Maklumat',
                active: true,
                createdBy: 'Admin',
            },
            {
                gradeId: grade![19].id,
                name: 'Pegawai Sistem Maklumat',
                active: true,
                createdBy: 'Admin',
            },
            {
                gradeId: grade![20].id,
                name: 'Pegawai Sistem Maklumat',
                active: true,
                createdBy: 'Admin',
            },
            {
                gradeId: grade![21].id,
                name: 'Pegawai Sistem Maklumat',
                active: true,
                createdBy: 'Admin',
            },
            {
                gradeId: grade![22].id,
                name: 'Pegawai Sistem Maklumat',
                active: true,
                createdBy: 'Admin',
            },
            {
                gradeId: grade![23].id,
                name: 'Pegawai Sistem Maklumat',
                active: true,
                createdBy: 'Admin',
            },
            {
                gradeId: grade![24].id,
                name: 'Pegawai Sistem Maklumat',
                active: true,
                createdBy: 'Admin',
            },
            {
                gradeId: grade![25].id,
                name: 'Pegawai Sistem Maklumat',
                active: true,
                createdBy: 'Admin',
            },
            {
                gradeId: grade![26].id,
                name: 'Pegawai Sistem Maklumat',
                active: true,
                createdBy: 'Admin',
            },
            {
                gradeId: grade![27].id,
                name: 'Pegawai Sistem Maklumat',
                active: true,
                createdBy: 'Admin',
            },
            {
                gradeId: grade![28].id,
                name: 'Pegawai Sistem Maklumat',
                active: true,
                createdBy: 'Admin',
            },
            {
                gradeId: grade![29].id,
                name: 'Pegawai Sistem Maklumat',
                active: true,
                createdBy: 'Admin',
            },
            {
                gradeId: grade![30].id,
                name: 'Pegawai Sistem Maklumat',
                active: true,
                createdBy: 'Admin',
            },
            {
                gradeId: grade![31].id,
                name: 'Pegawai Sistem Maklumat',
                active: true,
                createdBy: 'Admin',
            },
            {
                gradeId: grade![32].id,
                name: 'Pegawai Mahir dan Separuh Mahir',
                active: true,
                createdBy: 'Admin',
            },
            {
                gradeId: grade![33].id,
                name: 'Pemandu Kenderaan',
                active: true,
                createdBy: 'Admin',
            },
            {
                gradeId: grade![34].id,
                name: 'Jurutera',
                active: true,
                createdBy: 'Admin',
            },
            {
                gradeId: grade![35].id,
                name: 'Jurutera',
                active: true,
                createdBy: 'Admin',
            },
            {
                gradeId: grade![36].id,
                name: 'Jurutera',
                active: true,
                createdBy: 'Admin',
            },
            {
                gradeId: grade![37].id,
                name: 'Jurutera',
                active: true,
                createdBy: 'Admin',
            },
            {
                gradeId: grade![38].id,
                name: 'Jurutera',
                active: true,
                createdBy: 'Admin',
            },
            {
                gradeId: grade![39].id,
                name: 'Jurutera',
                active: true,
                createdBy: 'Admin',
            },
            {
                gradeId: grade![40].id,
                name: 'Jurutera',
                active: true,
                createdBy: 'Admin',
            },
            {
                gradeId: grade![41].id,
                name: 'Jurutera',
                active: true,
                createdBy: 'Admin',
            },
            {
                gradeId: grade![42].id,
                name: 'Jurutera',
                active: true,
                createdBy: 'Admin',
            },
            {
                gradeId: grade![43].id,
                name: 'Jurutera',
                active: true,
                createdBy: 'Admin',
            },
            {
                gradeId: grade![44].id,
                name: 'Jurutera',
                active: true,
                createdBy: 'Admin',
            },
            {
                gradeId: grade![45].id,
                name: 'Jurutera',
                active: true,
                createdBy: 'Admin',
            },
            {
                gradeId: grade![46].id,
                name: 'Jurutera',
                active: true,
                createdBy: 'Admin',
            },
            {
                gradeId: grade![47].id,
                name: 'Jurutera',
                active: true,
                createdBy: 'Admin',
            },
            {
                gradeId: grade![48].id,
                name: 'Jurutera',
                active: true,
                createdBy: 'Admin',
            },
            {
                gradeId: grade![49].id,
                name: 'Jurutera',
                active: true,
                createdBy: 'Admin',
            },
            {
                gradeId: grade![50].id,
                name: 'Jurutera',
                active: true,
                createdBy: 'Admin',
            },
            {
                gradeId: grade![51].id,
                name: 'Jurutera',
                active: true,
                createdBy: 'Admin',
            },
            {
                gradeId: grade![52].id,
                name: 'Jurutera',
                active: true,
                createdBy: 'Admin',
            },
            {
                gradeId: grade![53].id,
                name: 'Jurutera',
                active: true,
                createdBy: 'Admin',
            },
            {
                gradeId: grade![54].id,
                name: 'Jurutera',
                active: true,
                createdBy: 'Admin',
            },
            {
                gradeId: grade![55].id,
                name: 'Pegawai Keselamatan',
                active: true,
                createdBy: 'Admin',
            },
            {
                gradeId: grade![56].id,
                name: 'Pegawai Keselamatan',
                active: true,
                createdBy: 'Admin',
            },
            {
                gradeId: grade![57].id,
                name: 'Pegawai Keselamatan',
                active: true,
                createdBy: 'Admin',
            },
            {
                gradeId: grade![58].id,
                name: 'Pegawai Keselamatan',
                active: true,
                createdBy: 'Admin',
            },
            {
                gradeId: grade![59].id,
                name: 'Pegawai Perundangan',
                active: true,
                createdBy: 'Admin',
            },
            {
                gradeId: grade![60].id,
                name: 'Pegawai Perundangan',
                active: true,
                createdBy: 'Admin',
            },
            {
                gradeId: grade![61].id,
                name: 'Pegawai Pentadbiran dan Sokongan',
                active: true,
                createdBy: 'Admin',
            },
            {
                gradeId: grade![62].id,
                name: 'Pegawai Pentadbiran dan Sokongan',
                active: true,
                createdBy: 'Admin',
            },
            {
                gradeId: grade![63].id,
                name: 'Pegawai Pentadbiran dan Sokongan',
                active: true,
                createdBy: 'Admin',
            },
            {
                gradeId: grade![64].id,
                name: 'Pegawai Pentadbiran dan Sokongan',
                active: true,
                createdBy: 'Admin',
            },
            {
                gradeId: grade![65].id,
                name: 'Pegawai Pentadbiran dan Sokongan',
                active: true,
                createdBy: 'Admin',
            },
            {
                gradeId: grade![66].id,
                name: 'Pegawai Pentadbiran dan Sokongan',
                active: true,
                createdBy: 'Admin',
            },
            {
                gradeId: grade![67].id,
                name: 'Pegawai Pentadbiran dan Sokongan',
                active: true,
                createdBy: 'Admin',
            },
            {
                gradeId: grade![68].id,
                name: 'Pegawai Pentadbiran dan Sokongan',
                active: true,
                createdBy: 'Admin',
            },
            {
                gradeId: grade![69].id,
                name: 'Pegawai Pentadbiran dan Sokongan',
                active: true,
                createdBy: 'Admin',
            },
            {
                gradeId: grade![70].id,
                name: 'Pegawai Pentadbiran dan Sokongan',
                active: true,
                createdBy: 'Admin',
            },
            {
                gradeId: grade![71].id,
                name: 'Pentadbiran & Sokongan',
                active: true,
                createdBy: 'Admin',
            },
            {
                gradeId: grade![72].id,
                name: 'Pentadbiran & Sokongan',
                active: true,
                createdBy: 'Admin',
            },
            {
                gradeId: grade![73].id,
                name: 'Pegawai Pentadbiran dan Sokongan',
                active: true,
                createdBy: 'Admin',
            },
            {
                gradeId: grade![74].id,
                name: 'Pegawai Pentadbiran dan Sokongan',
                active: true,
                createdBy: 'Admin',
            },
            {
                gradeId: grade![75].id,
                name: 'Pegawai Pentadbiran dan Sokongan',
                active: true,
                createdBy: 'Admin',
            },
            {
                gradeId: grade![76].id,
                name: 'Pegawai Pentadbiran dan Sokongan',
                active: true,
                createdBy: 'Admin',
            },
            {
                gradeId: grade![77].id,
                name: 'Pegawai Pentadbiran dan Sokongan',
                active: true,
                createdBy: 'Admin',
            },
            {
                gradeId: grade![78].id,
                name: 'Pegawai Pentadbiran dan Sokongan',
                active: true,
                createdBy: 'Admin',
            },
            {
                gradeId: grade![79].id,
                name: 'Pegawai Pentadbiran dan Sokongan',
                active: true,
                createdBy: 'Admin',
            },
            {
                gradeId: grade![80].id,
                name: 'Pegawai Pentadbiran dan Sokongan',
                active: true,
                createdBy: 'Admin',
            },
            {
                gradeId: grade![81].id,
                name: 'Pegawai Bermasalah',
                active: true,
                createdBy: 'Admin',
            },
            {
                gradeId: grade![82].id,
                name: 'Pegwai Mahir Separuh Mahir & Tidak Mahir',
                active: true,
                createdBy: 'Admin',
            },
            {
                gradeId: grade![83].id,
                name: 'Pegwai Mahir Separuh Mahir & Tidak Mahir',
                active: true,
                createdBy: 'Admin',
            },
            {
                gradeId: grade![84].id,
                name: 'Pegwai Mahir Separuh Mahir & Tidak Mahir',
                active: true,
                createdBy: 'Admin',
            },
            {
                gradeId: grade![85].id,
                name: 'Pegwai Mahir Separuh Mahir & Tidak Mahir',
                active: true,
                createdBy: 'Admin',
            },
            {
                gradeId: grade![86].id,
                name: 'Pegwai Mahir Separuh Mahir & Tidak Mahir',
                active: true,
                createdBy: 'Admin',
            },
            {
                gradeId: grade![87].id,
                name: 'Pegwai Mahir Separuh Mahir & Tidak Mahir',
                active: true,
                createdBy: 'Admin',
            },
            {
                gradeId: grade![88].id,
                name: 'Pegwai Mahir Separuh Mahir & Tidak Mahir',
                active: true,
                createdBy: 'Admin',
            },
            {
                gradeId: grade![89].id,
                name: 'Pegwai Mahir Separuh Mahir & Tidak Mahir',
                active: true,
                createdBy: 'Admin',
            },
            {
                gradeId: grade![90].id,
                name: 'Pegawai Sosial',
                active: true,
                createdBy: 'Admin',
            },
            {
                gradeId: grade![91].id,
                name: 'Pegawai Sosial',
                active: true,
                createdBy: 'Admin',
            },
            {
                gradeId: grade![92].id,
                name: 'Pegawai Sosial',
                active: true,
                createdBy: 'Admin',
            },
            {
                gradeId: grade![93].id,
                name: 'Pegawai Sosial',
                active: true,
                createdBy: 'Admin',
            },
            {
                gradeId: grade![94].id,
                name: 'Pegawai Sosial',
                active: true,
                createdBy: 'Admin',
            },
            {
                gradeId: grade![95].id,
                name: 'Pegawai Sosial',
                active: true,
                createdBy: 'Admin',
            },
            {
                gradeId: grade![96].id,
                name: 'Pegawai Sosial',
                active: true,
                createdBy: 'Admin',
            },
            {
                gradeId: grade![97].id,
                name: 'Pegawai Sosial',
                active: true,
                createdBy: 'Admin',
            },
            {
                gradeId: grade![98].id,
                name: 'Pegawai Sosial',
                active: true,
                createdBy: 'Admin',
            },
            {
                gradeId: grade![99].id,
                name: 'Pegawai Sosial',
                active: true,
                createdBy: 'Admin',
            },
            {
                gradeId: grade![100].id,
                name: 'Pengurusan Tertinggi',
                active: true,
                createdBy: 'Admin',
            },
            {
                gradeId: grade![101].id,
                name: 'Pengurusan Tertinggi',
                active: true,
                createdBy: 'Admin',
            },
            {
                gradeId: grade![102].id,
                name: 'Pengurusan Tertinggi',
                active: true,
                createdBy: 'Admin',
            },
            {
                gradeId: grade![103].id,
                name: 'Pengurusan Tertinggi',
                active: true,
                createdBy: 'Admin',
            },
            {
                gradeId: grade![104].id,
                name: 'Pengurusan Tertinggi (JUSA B',
                active: true,
                createdBy: 'Admin',
            },
            {
                gradeId: grade![105].id,
                name: 'Pengurusan Tertinggi',
                active: true,
                createdBy: 'Admin',
            },
            {
                gradeId: grade![106].id,
                name: 'Pegawai Kewangan',
                active: true,
                createdBy: 'Admin',
            },
            {
                gradeId: grade![107].id,
                name: 'Pegawai Kewangan',
                active: true,
                createdBy: 'Admin',
            },
            {
                gradeId: grade![108].id,
                name: 'Pegawai Kewangan',
                active: true,
                createdBy: 'Admin',
            },
            {
                gradeId: grade![109].id,
                name: 'Pegawai Kewangan',
                active: true,
                createdBy: 'Admin',
            },
            {
                gradeId: grade![110].id,
                name: 'Pegawai Kewangan',
                active: true,
                createdBy: 'Admin',
            },
            {
                gradeId: grade![111].id,
                name: 'Pegawai Kewangan',
                active: true,
                createdBy: 'Admin',
            },
            {
                gradeId: grade![112].id,
                name: 'Pegawai Kewangan',
                active: true,
                createdBy: 'Admin',
            },
            {
                gradeId: grade![113].id,
                name: 'Pegawai Kewangan',
                active: true,
                createdBy: 'Admin',
            },
            {
                gradeId: grade![114].id,
                name: 'Pegawai Kewangan',
                active: true,
                createdBy: 'Admin',
            },
            {
                gradeId: grade![115].id,
                name: 'Pegawai Kewangan',
                active: true,
                createdBy: 'Admin',
            },
            {
                gradeId: grade![116].id,
                name: 'Pegawai Kewangan',
                active: true,
                createdBy: 'Admin',
            },
            {
                gradeId: grade![117].id,
                name: 'Pegawai Kewangan',
                active: true,
                createdBy: 'Admin',
            },
            {
                gradeId: grade![118].id,
                name: 'Pegawai Kewangan',
                active: true,
                createdBy: 'Admin',
            },
        ]);
    }
}
