import BaseSeeder from '@ioc:Adonis/Lucid/Seeder';
import Permission from 'App/Models/Permission';

export default class extends BaseSeeder {

	public async run () {
		await Permission.createMany([
			{
				action: "add",
				resource: "transfer-reasons",
				module: "employments",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "add",
				resource: "application-details-for-moving-out",
				module: "loans",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "add",
				resource: "application-details",
				module: "loans",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "add",
				resource: "application-details",
				module: "loans",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "upload",
				resource: "supporting-documents",
				module: "loans",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "add",
				resource: "application-details-for-vehicle-loan",
				module: "lonas",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "upload",
				resource: "supporting-documents-for-vehicle-loan",
				module: "loans",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "add",
				resource: "application-details",
				module: "service allowances",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "upload",
				resource: "supporting-documents",
				module: "service allowances",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "add",
				resource: "application-details-for-non-LKIM",
				module: "loans",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "add",
				resource: "claim-form",
				module: "medicals",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "add",
				resource: "exam-details",
				module: "courses",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "add",
				resource: "application-details",
				module: "leaves",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "add",
				resource: "application-details",
				module: "contracts",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "add",
				resource: "application-details",
				module: "courses",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "add",
				resource: "application-details",
				module: "employments",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "add",
				resource: "application-details",
				module: "service allowances",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "add",
				resource: "application-details",
				module: "leaves",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "add",
				resource: "application-details-education-fun",
				module: "courses",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "add",
				resource: "application-details",
				module: "loans",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "add",
				resource: "application-details-for-PTB-and-KWAP",
				module: "employments",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "add",
				resource: "application-details-appeal",
				module: "integrities",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "add",
				resource: "application-details-claims",
				module: "medicals",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "add",
				resource: "record-detail-suspension",
				module: "integrities",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "add",
				resource: "record-detail-application",
				module: "leaves",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "add",
				resource: "record-detail-tahan-kerja",
				module: "integrities",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "add",
				resource: "record-detail-surcharge",
				module: "integrities",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "add",
				resource: "candidates",
				module: "employments",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "add",
				resource: "payment-type",
				module: "integrities",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "add",
				resource: "detail-for-interim-position",
				module: "employments",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "add",
				resource: "meeting-result",
				module: "employments",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "add",
				resource: "meeting-result",
				module: "integrities",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "add",
				resource: "meeting-result",
				module: "leaves",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "add",
				resource: "meeting-result-placement",
				module: "employments",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "add",
				resource: "insert-name-approver",
				module: "employments",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "add",
				resource: "insert-name-supporter-and-approver",
				module: "employments",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "add",
				resource: "insert-name-supporter-and-approver",
				module: "employments",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "add",
				resource: "insert-name-supporter-and-approver",
				module: "employments",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "add",
				resource: "insert-name-approver",
				module: "employments",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "add",
				resource: "meeting-result",
				module: "salaries",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "add",
				resource: "application-details-for-panel-clinic",
				module: "medicals",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "add",
				resource: "application-detailss",
				module: "leaves",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "add",
				resource: "insert-name-supporter-1-and-supporter-2-and-approver",
				module: "employments",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "add",
				resource: "new-application",
				module: "employments",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "add",
				resource: "postponement-application-from-employee",
				module: "employments",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "add",
				resource: "postponement-application-placement",
				module: "employments",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "add",
				resource: "application-earlier-GCR-withdrawal",
				module: "leaves",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "add",
				resource: "application-details",
				module: "service allowances",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "add",
				resource: "application-details",
				module: "service allowances",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "upload",
				resource: "supported-documents",
				module: "service allowances",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "add",
				resource: "application-details-for-funeral-service",
				module: "service allowances",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "approve",
				resource: "meeting-result",
				module: "employments",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "approve",
				resource: "approval-status",
				module: "employments",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "approve",
				resource: "approval-status-from-director",
				module: "leaves",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "approve",
				resource: "approval-status-from-director-of-management-services",
				module: "leaves",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "approve",
				resource: "approval-status-application",
				module: "leaves",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "approve",
				resource: "approval-status-from-director-of-management-services",
				module: "leaves",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "approve",
				resource: "approval-status-application",
				module: "contracts",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "approve",
				resource: "approval-status-application",
				module: "employments",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "approve",
				resource: "approval-status-application",
				module: "leaves",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "approve",
				resource: "approval-status-application",
				module: "medicals",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "approve",
				resource: "approval-status",
				module: "employments",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "approve",
				resource: "supported-status",
				module: "employments",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "approve",
				resource: "application-status",
				module: "contracts",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "approve",
				resource: "application-status-from-secretary",
				module: "leaves",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "certify",
				resource: "approval-application-status",
				module: "leaves",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "certify",
				resource: "certification-status-from-director",
				module: "employments",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "certify",
				resource: "certification-status-from-director-division-or-state",
				module: "contracts",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "certify",
				resource: "certification-status-from-integrity-director",
				module: "employments",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "certify",
				resource: "certification-status-from-audit-director",
				module: "employments",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "certify",
				resource: "certification-status-from-secretary-integrity",
				module: "employments",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "certify",
				resource: "certification-status-for-application",
				module: "leaves",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "certify",
				resource: "certification-status-for-application-from-integrity-director",
				module: "employments",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "certify",
				resource: "certification-status-for-application-from-audit-director",
				module: "employments",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "certify",
				resource: "certification-status-for-application-from-director-division-or-state",
				module: "employments",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "certify",
				resource: "certification-status-for-application-from-secretary-integrity",
				module: "courses",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "verify",
				resource: "verification-status-for-leave-application",
				module: "leaves",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "confirm",
				resource: "payment-proof",
				module: "medicals",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "confirm",
				resource: "confirmation-status-for-application",
				module: "leaves",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "confirm",
				resource: "salary-movement",
				module: "salaries",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "confirm",
				resource: "confirmation-status-for-agreement-form",
				module: "contracts",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "confirm",
				resource: "confirmation-status-from-secratary",
				module: "leaves",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "confirm",
				resource: "confirmation-status-for-application",
				module: "contracts",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "confirm",
				resource: "confirmation-status-for-application",
				module: "courses",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "confirm",
				resource: "confirmation-status-for-application",
				module: "leaves",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "confirm",
				resource: "confirmation-status-for-leave-application",
				module: "leaves",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "confirm",
				resource: "confirmation-status-for-application-from-secretary",
				module: "leaves",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "confirm",
				resource: "confirmation-status",
				module: "medicals",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "download",
				resource: "payment-order",
				module: "courses",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "download",
				resource: "salary-deduction-order",
				module: "medicals",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "download",
				resource: "supporting-documents",
				module: "employments",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "download",
				resource: "kwap-form",
				module: "employments",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "download",
				resource: "assesment-form",
				module: "employments",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "download",
				resource: "medical-form",
				module: "employments",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "download",
				resource: "employee-profile-CV",
				module: "employments",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "download",
				resource: "payment-proof",
				module: "medicals",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "download",
				resource: "clinic-panel-appointment-letter",
				module: "medicals",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "download",
				resource: "birth-certification-document",
				module: "leaves",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "download",
				resource: "supporting-documents",
				module: "courses",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "download",
				resource: "supporting-documents",
				module: "leaves",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "download",
				resource: "supporting-documents",
				module: "loans",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "download",
				resource: "quotation",
				module: "loans",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "download",
				resource: "documents",
				module: "employments",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "download",
				resource: "employee-payslip",
				module: "salaries",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "download",
				resource: "APC-report",
				module: "performances",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "download",
				resource: "performance-report",
				module: "performances",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "download",
				resource: "biannual-performance-report",
				module: "performances",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "download",
				resource: "documents",
				module: "loans",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "download",
				resource: "payment-order-based-on-placement",
				module: "medicals",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "download",
				resource: "offer-letter",
				module: "loans",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "download",
				resource: "offer-letter",
				module: "loans",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "download",
				resource: "arrears-payment-order-letter",
				module: "loans",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "download",
				resource: "payment-order-finance",
				module: "service allowances",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "download",
				resource: "payment-order-to-finance",
				module: "medicals",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "download",
				resource: "payment-order-to-finance",
				module: "service allowances",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "download",
				resource: "payment-voucher",
				module: "loans",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "download",
				resource: "loan-application-details",
				module: "loans",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "download",
				resource: "receipt",
				module: "loans",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "download",
				resource: "loan",
				module: "loans",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "download",
				resource: "invoice",
				module: "loans",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "download",
				resource: "receipt-uploaded",
				module: "loans",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "download",
				resource: "receipt-invoice",
				module: "loans",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "download",
				resource: "receipt-medical",
				module: "medicals",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "download",
				resource: "failure-letter",
				module: "employments",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "download",
				resource: "failure-letter Penangguhan Rayuan",
				module: "employments",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "download",
				resource: "failure-letter Pertimbangkan",
				module: "employments",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "download",
				resource: "approval-letter",
				module: "service allowances",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "download",
				resource: "result-letter",
				module: "employments",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "download",
				resource: "new-contract-agreement-letter",
				module: "contracts",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "download",
				resource: "application-approved-letter",
				module: "courses",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "download",
				resource: "exceeding-annual-medical-usage-limit-letter",
				module: "medicals",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "download",
				resource: "exam-invitation-letter",
				module: "courses",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "download",
				resource: "interview-invitation-letter",
				module: "employments",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "download",
				resource: "confirmation-form",
				module: "employments",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "download",
				resource: "interim-termination-letter",
				module: "employments",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "download",
				resource: "transfer-postponement-letter",
				module: "employments",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "download",
				resource: "postponement-appeal-letter",
				module: "employments",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "download",
				resource: "confirmation-in-services-letter",
				module: "employments",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "download",
				resource: "agreement-letter",
				module: "loans",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "download",
				resource: "clinic-panel-appointment-letter",
				module: "medicals",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "download",
				resource: "transfer-letter",
				module: "employments",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "download",
				resource: "offer-letter",
				module: "loans",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "download",
				resource: "offer-letter-for-loan-approval",
				module: "loans",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "download",
				resource: "cover-letter",
				module: "loans",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "download",
				resource: "offer-letter-for-promotion",
				module: "employments",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "download",
				resource: "report-duty-form",
				module: "employments",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "download",
				resource: "handover-note",
				module: "employments",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "download",
				resource: "offer-letter-quarters",
				module: "loans",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "download",
				resource: "offer-letter-for-acting-position",
				module: "employments",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "download",
				resource: "acceptance-letter",
				module: "employments",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "download",
				resource: "report-duty-form",
				module: "employments",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "download",
				resource: "handover-note",
				module: "employments",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "download",
				resource: "acceptance-letter",
				module: "employments",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "download",
				resource: "payment-order-finance",
				module: "service allowances",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "certify",
				resource: "certification-status",
				module: "employments",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "edit",
				resource: "first-and-second-schedule",
				module: "loans",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "approve",
				resource: "approval-status",
				module: "employments",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "edit",
				resource: "salary-deduction",
				module: "salaries",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "edit",
				resource: "retirement-application",
				module: "employments",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "edit",
				resource: "changes-in-salary-and-allowances",
				module: "salaries",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "confirm",
				resource: "confirmation-status",
				module: "employments",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "support",
				resource: "supported-status",
				module: "employments",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "support",
				resource: "supported-status",
				module: "employments",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "edit",
				resource: "status",
				module: "employments",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "edit",
				resource: "status",
				module: "employments",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "edit",
				resource: "remark",
				module: "employments",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "approve",
				resource: "approval-status-for-involved-employee",
				module: "salaries",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "edit",
				resource: "status",
				module: "employments",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "edit",
				resource: "remark",
				module: "employments",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "edit",
				resource: "submission-date-for-application-to-KWAP",
				module: "employments",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "approve",
				resource: "approved-status",
				module: "medicals",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "edit",
				resource: "supported-status",
				module: "employments",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "employee-list",
				module: "performances",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "APC-receiver-list",
				module: "performances",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "read",
				resource: "document",
				module: "personalDetail",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "support",
				resource: "supported-status",
				module: "employments",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "support",
				resource: "supported-status-application-from-director-division-or-state",
				module: "leaves",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "support",
				resource: "supported-status-application-from-section-lead",
				module: "leaves",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "support",
				resource: "supported-status",
				module: "employments",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "support",
				resource: "supported-status-from-director-division-or-state",
				module: "leaves",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "support",
				resource: "supported-application-status",
				module: "contracts",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "support",
				resource: "supported-application-status",
				module: "employments",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "support",
				resource: "supported-application-status",
				module: "leaves",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "support",
				resource: "supported-application-status-from-director-division-or-state",
				module: "leaves",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "support",
				resource: "supported-application-status-from-director-division-or-state",
				module: "courses",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "support",
				resource: "supported-application-status-from-director-division-or-state",
				module: "leaves",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "support",
				resource: "application-status",
				module: "contracts",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "approve",
				resource: "approval-status",
				module: "loans",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "update",
				resource: "approval-status",
				module: "service allowances",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "update",
				resource: "insert-name-approver",
				module: "contracts",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "update",
				resource: "insert-name-supporter-and-approver",
				module: "service allowances",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "update",
				resource: "insert-name-approver",
				module: "loans",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "update",
				resource: "medical-balance-for-employee",
				module: "medicals",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "update",
				resource: "agreement-letter",
				module: "contracts",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "update",
				resource: "application-details",
				module: "contracts",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "update",
				resource: "employee-details",
				module: "leaves",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "update",
				resource: "GCR-deduction-details",
				module: "leaves",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "update",
				resource: "invoice",
				module: "service allowances",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "update",
				resource: "document",
				module: "service allowances",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "update",
				resource: "current-eligibility-leave",
				module: "leaves",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "update",
				resource: "KWAP-result",
				module: "employments",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "update",
				resource: "meeting-result",
				module: "courses",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "update",
				resource: "meeting-result",
				module: "employments",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "update",
				resource: "meeting-result",
				module: "integrities",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "update",
				resource: "meeting-result-promotion",
				module: "employments",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "update",
				resource: "meeting-result-postponement",
				module: "employments",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "update",
				resource: "interview-result",
				module: "employments",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "approve",
				resource: "approval-status",
				module: "loans",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "update",
				resource: "employee-details",
				module: "contracts",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "update",
				resource: "employee-details",
				module: "employments",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "update",
				resource: "employee-details",
				module: "leaves",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "update",
				resource: "meeting-details",
				module: "employments",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "update",
				resource: "deduction-based-on-quarter-details",
				module: "loans",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "update",
				resource: "insert-name-supporter-and-approver",
				module: "employments",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "update",
				resource: "APC-year-details",
				module: "performances",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "update",
				resource: "fit-criteria",
				module: "contracts",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "update",
				resource: "insert-name-supporter-and-approver",
				module: "employments",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "update",
				resource: "chasis-engine-or-engine-number",
				module: "loans",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "update",
				resource: "overall-status",
				module: "courses",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "update",
				resource: "overall-status",
				module: "employments",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "update",
				resource: "overall-status",
				module: "integrities",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "update",
				resource: "overall-status",
				module: "leaves",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "update",
				resource: "overall-status-for-request",
				module: "employments",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "update",
				resource: "overall-status",
				module: "courses",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "update",
				resource: "overall-status",
				module: "leaves",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "update",
				resource: "overall-status",
				module: "service allowances",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "update",
				resource: "overall-status",
				module: "integrities",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "update",
				resource: "overall-status",
				module: "leaves",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "update",
				resource: "overall-status",
				module: "leaves",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "update",
				resource: "insert-name-supporter-and-approver",
				module: "employments",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "update",
				resource: "no-longer-over-budget",
				module: "medicals",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "update",
				resource: "salary-details",
				module: "salaries",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "verify",
				resource: "verification-status",
				module: "loans",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "update",
				resource: "insert-name-supporter-and-approver",
				module: "leaves",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "update",
				resource: "approval-status",
				module: "employments",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "update",
				resource: "approval-status-application",
				module: "medicals",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "update",
				resource: "confirmation-result-status",
				module: "employments",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "update",
				resource: "application-approval-process-status",
				module: "loans",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "update",
				resource: "confirmation-status-for-application",
				module: "employments",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "update",
				resource: "supported-status",
				module: "employments",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "update",
				resource: "supported-application-status",
				module: "medicals",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "update",
				resource: "certification-status-from-director-division-or-state",
				module: "employments",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "update",
				resource: "certification-status-from-secretary-integrity",
				module: "employments",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "update",
				resource: "postponement-status-for-placement",
				module: "employments",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "support",
				resource: "supported-status",
				module: "employments",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "update",
				resource: "supported-status-from-director-division-or-state",
				module: "employments",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "verify",
				resource: "verification-status",
				module: "loans",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "verify",
				resource: "verification-status",
				module: "loans",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "approve",
				resource: "approval-status",
				module: "loans",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "support",
				resource: "supported-status",
				module: "loans",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "support",
				resource: "supported-application-status",
				module: "loans",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "support",
				resource: "supported-status",
				module: "service allowances",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "support",
				resource: "supported-status",
				module: "service allowances",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "update",
				resource: "insert-name-supporter-and-approver",
				module: "service allowances",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "update",
				resource: "quarter-details",
				module: "loans",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "approve",
				resource: "approval-status",
				module: "service allowances",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "approve",
				resource: "approval-status",
				module: "service allowances",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "approve",
				resource: "approval-status-application",
				module: "service allowances",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "approve",
				resource: "approval-status-application",
				module: "service allowances",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "approve",
				resource: "approval-status-application",
				module: "loans",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "update",
				resource: "insert-name-supporter-and-approver",
				module: "service allowances",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "update",
				resource: "checklist",
				module: "employments",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "update",
				resource: "insert-checker-and-preparer",
				module: "employments",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "update",
				resource: "insert-name-supporter-and-approver",
				module: "medicals",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "update",
				resource: "insert-name-supporter-and-approver",
				module: "medicals",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "update",
				resource: "overall-status",
				module: "service allowances",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "update",
				resource: "overall-status for the application",
				module: "service allowances",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "update",
				resource: "overall-status",
				module: "contracts",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "update",
				resource: "overall-status",
				module: "medicals",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "update",
				resource: "overall-status",
				module: "service allowances",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "approve",
				resource: "approval-status",
				module: "medicals",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "support",
				resource: "supported-status",
				module: "medicals",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "update",
				resource: "application-details",
				module: "loans",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "approve",
				resource: "approval-application-status",
				module: "medicals",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "verify",
				resource: "verification-status",
				module: "medicals",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "support",
				resource: "supported-application-status",
				module: "medicals",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "approve",
				resource: "approval-application-status",
				module: "loans",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "verify",
				resource: "verification-status",
				module: "loans",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "support",
				resource: "supported-application-status",
				module: "service allowances",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "support",
				resource: "supported-application-status",
				module: "service allowances",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "support",
				resource: "supported-status",
				module: "service allowances",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "update",
				resource: "insert-name-supporter-and-approver",
				module: "service allowances",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "verify",
				resource: "verification-status",
				module: "service allowances",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "upload",
				resource: "retirement-form",
				module: "employments",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "upload",
				resource: "payment-proof",
				module: "medicals",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "upload",
				resource: "birth-certification-document",
				module: "leaves",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "upload",
				resource: "supporting-documents",
				module: "leaves",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "upload",
				resource: "supporting-documents",
				module: "courses",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "upload",
				resource: "supporting-documents",
				module: "service allowances",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "upload",
				resource: "supporting-documents dan Sebut Harga",
				module: "loans",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "upload",
				resource: "appendix-B",
				module: "service allowances",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "upload",
				resource: "receipt",
				module: "loans",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "upload",
				resource: "invoice",
				module: "loans",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "upload",
				resource: "medical-receipt",
				module: "medicals",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "upload",
				resource: "agreement-form",
				module: "loans",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "upload",
				resource: "supporting-documents",
				module: "service allowances",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "verify",
				resource: "candidates-details",
				module: "contracts",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "verify",
				resource: "GCR-payment",
				module: "leaves",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "verify",
				resource: "verification-status",
				module: "medicals",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "verify",
				resource: "verification-status-from-secretary",
				module: "leaves",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "verify",
				resource: "verification-status",
				module: "employments",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "verify",
				resource: "verification-review-status",
				module: "employments",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "verify",
				resource: "verification-status",
				module: "courses",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "verify",
				resource: "verification-status",
				module: "leaves",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "verify",
				resource: "verification-status-from-secretary",
				module: "leaves",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "verify",
				resource: "verification-status-confirmation-requirement",
				module: "employments",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "verify",
				resource: "verification-status",
				module: "medicals",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "certify",
				resource: "certification-status",
				module: "employments",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "application-list-for-computer",
				module: "loans",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "application-list-for-vehicle",
				module: "loans",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "application-list-for-vehicle-related-to-themselves",
				module: "loans",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "list-of-application",
				module: "loans",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "list-of-application",
				module: "service allowances",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "list-of-application-for-moving-out-quarters",
				module: "loans",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "list-of-application-for-quarters",
				module: "loans",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "list-of-application-for-quarters-for-non-employee",
				module: "loans",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "list-of-application-for-quarters-belongs-to-themselves",
				module: "loans",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "list-of-application-for-quarters-belongs-to-themselves",
				module: "loans",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "application-details",
				module: "employments",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "application-details",
				module: "loans",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "application-details",
				module: "loans",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "download",
				resource: "supporting-documents",
				module: "loans",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "application-details",
				module: "loans",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "download",
				resource: "supporting-documents",
				module: "loans",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "application-details",
				module: "service allowances",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "download",
				resource: "supporting-documents",
				module: "service allowances",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "application-details",
				module: "loans",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "download",
				resource: "supporting-documents",
				module: "loans",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "application-details",
				module: "service allowances",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "download",
				resource: "supporting-documents",
				module: "service allowances",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "application-details-for-funeral-services",
				module: "service allowances",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "application-details-for-clinic-panel",
				module: "medicals",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "application-details-for-quarters",
				module: "loans",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "application-details",
				module: "loans",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "application-status",
				module: "loans",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "approve",
				resource: "approval-status-application",
				module: "loans",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "approve",
				resource: "approval-status-application",
				module: "service allowances",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "approve",
				resource: "approval-status-application",
				module: "service allowances",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "edit",
				resource: "name-approver",
				module: "contracts",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "leave-balance",
				module: "leaves",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "maximum-leave-balance",
				module: "leaves",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "medical-balance-for-employee",
				module: "medicals",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "supporting-documents",
				module: "employments",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "agreement-letter",
				module: "contracts",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "leave-details",
				module: "leaves",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "employee-details",
				module: "employments",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "employee-details",
				module: "leaves",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "employee-details",
				module: "performances",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "employee-details-for-termination-contract",
				module: "contracts",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "employee-details-for-confirmation-more-than-three-years",
				module: "employments",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "employee-details-in-trial",
				module: "employments",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "employee-details-for-termination-contract",
				module: "contracts",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "employee-details-for-termination-contract",
				module: "contracts",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "employee-details-for-involved",
				module: "employments",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "employee-details",
				module: "employments",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "recommended-placement",
				module: "employments",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "transfer-reasons",
				module: "employments",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "employee-details",
				module: "employments",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "application-details",
				module: "leaves",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "application-details",
				module: "courses",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "APC-receiver-list",
				module: "performances",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "application-details",
				module: "contracts",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "application-details",
				module: "courses",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "application-details",
				module: "employments",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "application-details",
				module: "leaves",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "application-details-earlier-GCR-withdrawal",
				module: "leaves",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "application-details-rest-day-collection",
				module: "leaves",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "application-details-transfer",
				module: "employments",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "application-details",
				module: "loans",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "application-details-for-PTB-and-KWAP",
				module: "employments",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "application-details-for-appeal",
				module: "integrities",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "application-details-for-claim",
				module: "medicals",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "transfer-detail",
				module: "employments",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "record-detail",
				module: "integrities",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "record-detail-claim",
				module: "medicals",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "record-detail-suspension",
				module: "integrities",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "record-detail-application",
				module: "courses",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "record-detail-applicantion",
				module: "leaves",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "record-detail-tahan-kerja",
				module: "integrities",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "record-detail-surcharge",
				module: "integrities",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "candidates",
				module: "employments",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "payment-type",
				module: "integrities",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "deduction-details-based-on-preset-rules",
				module: "leaves",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "interim-position-details",
				module: "employments",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "download",
				resource: "supporting-document",
				module: "employments",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "list-of-retired-employee",
				module: "salaries",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "final-status",
				module: "employments",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "employee-number-generation",
				module: "contracts",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "employee-number-generation",
				module: "employments",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "seniority-skipping",
				module: "employments",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "remarks",
				module: "employments",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "payment-type",
				module: "medicals",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "arrear-status",
				module: "loans",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "JPA-result",
				module: "employments",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "KWAP-result",
				module: "employments",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "meeting-result",
				module: "courses",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "meeting-result",
				module: "employments",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "meeting-result",
				module: "integrities",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "meeting-result",
				module: "leaves",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "meeting-result-promotion",
				module: "employments",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "meeting-result-postponement",
				module: "employments",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "meeting-result-placement",
				module: "employments",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "exam-result-from-result-examiner",
				module: "courses",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "appeal-status",
				module: "integrities",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "interview-result",
				module: "employments",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "appendix-B",
				module: "service allowances",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "list-of-application-for-funeral-services",
				module: "service allowances",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "list-of-application-for-computer",
				module: "loans",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "list-of-candidates",
				module: "employments",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "list-of-employee",
				module: "employments",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "list-of-potential-employees",
				module: "employments",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "employee-details",
				module: "employments",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "meeting-details",
				module: "employments",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "insert-name-supporter-and-approver",
				module: "employments",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "loan-detail",
				module: "loans",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "first-and-second-schedule",
				module: "loans",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "JPA-letter-details",
				module: "employments",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "insert-name-approver",
				module: "employments",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "insert-name-supporter-and-approver",
				module: "employments",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "insert-name-supporter-and-approver",
				module: "employments",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "insert-name-approver",
				module: "employments",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "fit-criteria",
				module: "contracts",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "insert-name-approver",
				module: "loans",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "insert-name-supporter-and-approver",
				module: "employments",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "GCR-value",
				module: "leaves",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "overal-status",
				module: "courses",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "overall-application-status",
				module: "leaves",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "overall-status",
				module: "employments",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "overall-status",
				module: "integrities",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "overall-status",
				module: "employments",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "overall-status",
				module: "leaves",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "overall-status",
				module: "employments",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "overall-status",
				module: "service allowances",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "overall-status",
				module: "courses",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "overall-status",
				module: "employments",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "overall-status",
				module: "leaves",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "overall-status",
				module: "medicals",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "overall-status",
				module: "service allowances",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "overall-status",
				module: "medicals",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "overall-status",
				module: "integrities",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "overall-status",
				module: "leaves",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "interim-employee",
				module: "employments",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "monthly-deduction-from-salary",
				module: "salaries",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "director-division-or-state",
				module: "employments",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "confirmation-status-for-application",
				module: "leaves",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "interim-allowance-calculation",
				module: "employments",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "GCR-collection-calculation",
				module: "leaves",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "average-two-year-calculation",
				module: "performances",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "average-for-chosen-year",
				module: "performances",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "supporter",
				module: "service allowances",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "insert-name-supporter-1-and-supporter-2-and-approver",
				module: "employments",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "insert-name-supporter-and-approver",
				module: "employments",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "cerify",
				resource: "certification-status-from-integrity-director",
				module: "employments",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "postponement-status",
				module: "employments",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "postponement-status-for-transfer",
				module: "employments",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "director-division-or-state",
				module: "service allowances",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "receipt-medical",
				module: "medicals",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "list-of-involved-employee",
				module: "salaries",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "list-of-involved-employee",
				module: "salaries",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "application-details",
				module: "medicals",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "application-details",
				module: "medicals",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "download",
				resource: "supporting-documents",
				module: "loans",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "claim-details",
				module: "medicals",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "current-service-details",
				module: "employments",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "interim-application-details",
				module: "employments",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "verify",
				resource: "verification-result-application",
				module: "leaves",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "verify",
				resource: "verify-payment-proof",
				module: "medicals",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "verify",
				resource: "verify-retirement-document",
				module: "employments",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "verify",
				resource: "verify-disciplinary-record",
				module: "employments",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "verify",
				resource: "verification-approval-status-application Dari Pengarah Bahagian",
				module: "leaves",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "verify",
				resource: "verification-confirmation-status-for-application",
				module: "leaves",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "verify",
				resource: "submission-date-for-application-to-KWAP",
				module: "employments",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "verify",
				resource: "verification-supported-application-status-from-section-lead",
				module: "leaves",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "verify",
				resource: "verification-status",
				module: "leaves",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "thirteen-years-in-service-employee-list",
				module: "employments",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "leave-application-list",
				module: "leaves",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "list-employee",
				module: "employments",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "list-employee",
				module: "performances",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "list-employee-termination-contract",
				module: "contracts",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "list-employee-in-trial",
				module: "employments",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "list-employee-retired-death-early-dismissal",
				module: "leaves",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "list-employee-termination-contract",
				module: "contracts",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "list-employee-exceed-quota",
				module: "medicals",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "list-employee",
				module: "employments",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "list-employee-confirmation-more-than-three-years",
				module: "employments",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "list-employee-confirmation-more-than-three-years",
				module: "employments",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "list-employee-in-trial",
				module: "employments",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "list-application-for-examination",
				module: "courses",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "insert-name-supporter-and-approver",
				module: "leaves",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "exam-list",
				module: "courses",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "list-retirement-application",
				module: "employments",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "list-of-clinic-panel-application",
				module: "medicals",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "list-of-application",
				module: "contracts",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "list-of-application",
				module: "courses",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "list-of-application",
				module: "employments",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "list-of-application-for-clinic-panel",
				module: "medicals",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "list-of-application-education-fund",
				module: "courses",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "list-of-application-earlier-GCR-withdrawal",
				module: "leaves",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "list-of-application-earlier-GCR-withdrawal",
				module: "leaves",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "list-of-application-retirement",
				module: "employments",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "list-of-application-transfer",
				module: "employments",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "list-of-application-loan-computer",
				module: "loans",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "list-of-application-PTB-and-KWAP",
				module: "employments",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "list-of-application-appeal",
				module: "integrities",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "list-of-application-claim",
				module: "medicals",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "forced-retirement-list",
				module: "employments",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "voluntary-retirement-list",
				module: "employments",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "claim-list",
				module: "medicals",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "list-for-suspension",
				module: "integrities",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "list-of-involved-employee",
				module: "employments",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "list-of-involved-employee-for-surcharge",
				module: "integrities",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "list-sentencing",
				module: "integrities",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "list-application",
				module: "courses",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "list-application",
				module: "leaves",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "list-leave-application",
				module: "leaves",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "list-of-accusations",
				module: "integrities",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "list-of-tahan-kerja",
				module: "integrities",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "list-of-suspension",
				module: "employments",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "list-of-new-offer",
				module: "employments",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "list-of-application",
				module: "leaves",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "status",
				module: "employments",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "status",
				module: "employments",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "remark",
				module: "employments",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "approval-status",
				module: "employments",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "approval-status",
				module: "loans",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "approval-status-from-director",
				module: "leaves",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "approval-status-from-director-division-or-state",
				module: "leaves",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "approval-status-from-director-of-management-services",
				module: "leaves",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "approval-status-application",
				module: "contracts",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "approval-status-application",
				module: "employments",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "approval-status-application",
				module: "leaves",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "approval-status-application",
				module: "medicals",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "approval-status-application-director",
				module: "leaves",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "approval-status-application-director-of-management-services",
				module: "leaves",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "approval-status-application-postponement",
				module: "employments",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "approval-result-status",
				module: "employments",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "is-fit-criteria-status",
				module: "contracts",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "status of application supports",
				module: "loans",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "approval-status",
				module: "loans",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "application-status",
				module: "loans",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "approval-status-from-director",
				module: "leaves",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "approval-application-status",
				module: "leaves",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "approval-application-status",
				module: "leaves",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "approval-application-status",
				module: "medicals",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "approval-application-status-from-director-of-management-services",
				module: "leaves",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "confirmation-status",
				module: "contracts",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "confirmation-status-for-agreement-letter",
				module: "contracts",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "confirmation-status-for-application-details",
				module: "leaves",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "confirmation-status-for-secretary",
				module: "leaves",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "confirmation-status-for-retirement-secratary",
				module: "employments",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "confirmation-status-for-qualification",
				module: "leaves",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "confirmation-status-for-application",
				module: "leaves",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "Status confirmation-status-for-application",
				module: "leaves",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "confirmation-status-for-application",
				module: "contracts",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "confirmation-status-for-application",
				module: "courses",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "confirmation-status-for-application",
				module: "employments",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "confirmation-status-for-application",
				module: "leaves",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "confirmation-status-for-application",
				module: "medicals",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "confirmation-status-for-application-from-secretary",
				module: "leaves",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "verification-application-status",
				module: "medicals",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "supported-status",
				module: "employments",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "supported-status",
				module: "medicals",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "supported-status-from-director",
				module: "leaves",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "supported-status",
				module: "employments",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "supported-status-from-section-lead",
				module: "loans",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "supported-status-from-director-division-or-state",
				module: "leaves",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "supported-status-from-director-of-management-services",
				module: "leaves",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "supported-status-from-director-division-or-state",
				module: "leaves",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "supported-status-from-director-division-or-state",
				module: "leaves",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "supported-status-from-director-of-management-services",
				module: "leaves",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "supported-status",
				module: "contracts",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "supported-application-status",
				module: "contracts",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "supported-application-status",
				module: "employments",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "supported-application-status",
				module: "leaves",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "supported-application-status",
				module: "medicals",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "supported-application-status-from-director-division-or-state",
				module: "leaves",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "supported-application-status-from-director-division-or-state",
				module: "leaves",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "supported-application-status-from-director-of-management-services",
				module: "leaves",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "supported-application-status-from-director-division-or-state",
				module: "courses",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "supported-application-status-from-director-division-or-state",
				module: "leaves",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "certification-status-from-from-director-division-or-state",
				module: "contracts",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "certification-status-from-from-director-division-or-state",
				module: "employments",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "certification-status-from-integrity-director",
				module: "employments",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "certification-status-from-audit-director",
				module: "employments",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "certification-status-from-director-division-or-state",
				module: "employments",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "certification-status-from-secretary-integrity",
				module: "employments",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "certification-status",
				module: "leaves",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "certification-status-for-application",
				module: "leaves",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "certification-status-for-application-from-integrity-director",
				module: "employments",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "certification-status-for-application-from-audit-director",
				module: "employments",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "certification-status-for-application-from-director-division-or-state",
				module: "employments",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "certification-status-for-application-from-secretary-integrity",
				module: "courses",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "application-status",
				module: "leaves",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "postponement-status-for-transfer",
				module: "employments",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "allocation-fund-for-employee-status",
				module: "medicals",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "verification-status-from-secretary",
				module: "leaves",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "verification-status-eligibility",
				module: "leaves",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "verification-status-eligibility-leave",
				module: "leaves",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "verification-status-GCR-criteria",
				module: "leaves",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "verification-status-for-candidates-details",
				module: "contracts",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "verification-statusfor-candidates-details",
				module: "employments",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "verification-status",
				module: "employments",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "verification-status",
				module: "courses",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "VIEW",
				resource: "verification-status",
				module: "leaves",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "verification-status",
				module: "loans",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "verification-status",
				module: "medicals",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "verification-status-from-secretary",
				module: "leaves",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "verification-qualification-status",
				module: "employments",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "supported-status",
				module: "employments",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "supported-status-from-director",
				module: "employments",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "status",
				module: "employments",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "remark",
				module: "employments",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "supported-status",
				module: "loans",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "approval-status",
				module: "loans",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "supported-status",
				module: "service allowances",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "support-status",
				module: "service allowances",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "insert-name-supporter-and-approver",
				module: "service allowances",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "failure-letter",
				module: "employments",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "download",
				resource: "interview-invitation-letter",
				module: "employments",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "download",
				resource: "confirmation-form",
				module: "employments",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "postponement-appeal-letter",
				module: "employments",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "transfer-letter",
				module: "employments",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "offer-letter-for-promotion",
				module: "employments",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "report-duty-form",
				module: "employments",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "handover-note",
				module: "employments",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "submission-date-for-application-to-KWAP",
				module: "employments",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "suspension-period",
				module: "employments",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "supporting-documents",
				module: "service allowances",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "application-details",
				module: "service allowances",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "application-details",
				module: "service allowances",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "download",
				resource: "supporting-documents",
				module: "service allowances",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "application-detail",
				module: "service allowances",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "download",
				resource: "supporting-documents",
				module: "service allowances",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "application-details",
				module: "loans",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "download",
				resource: "supporting documents",
				module: "loans",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "application-details and supportings documents for selected application",
				module: "loans",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "application-details",
				module: "loans",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "download",
				resource: "supporting-documents",
				module: "loans",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "application-details",
				module: "service allowances",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "download",
				resource: "supporting-documents",
				module: "service allowances",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "application-details-for-funeral-service",
				module: "service allowances",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "application-details",
				module: "loans",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "application-details-for-moving-out-quarters",
				module: "loans",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "application-list",
				module: "service allowances",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "application-overall-status",
				module: "service allowances",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "applicationd-details",
				module: "service allowances",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "download",
				resource: "supporting-documents",
				module: "service allowances",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "approval-status",
				module: "service allowances",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "approval-status",
				module: "service allowances",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "current-support-status",
				module: "medicals",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "interim-position-application-for-selected-employee",
				module: "employments",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "list-of-application",
				module: "service allowances",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "overall-status",
				module: "contracts",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "overall-status",
				module: "service allowances",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "current-service-detail-for-employee",
				module: "employments",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "approved-status-loan-secretary",
				module: "loans",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "approval-status-for-director-division-or-state",
				module: "loans",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "application-status",
				module: "service allowances",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "verification-status-from-loan-secretary",
				module: "loans",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "supported-application-status",
				module: "service allowances",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "supported-application-status",
				module: "service allowances",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "supported-application-status-from-director-division-or-state",
				module: "service allowances",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "support-status",
				module: "service allowances",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "support-status",
				module: "service allowances",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "supported-status-from-supporter",
				module: "service allowances",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "supported-application-status-for-director-division-or-state",
				module: "service allowances",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "verification-status",
				module: "service allowances",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "verification-status-from-allowance-secretary",
				module: "service allowances",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "verification-status",
				module: "loans",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "verification-status",
				module: "service allowances",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "verification-status-from-allowance-secretary",
				module: "service allowances",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "download",
				resource: "supporting-document-from-allowance-secretary",
				module: "service allowances",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "secretary-integrity",
				module: "employments",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "allowance-secretary",
				module: "service allowances",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "loan-secretary",
				module: "loans",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "verification-status-from-next-of-kins",
				module: "service allowances",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "confirmation-status-from-next-of-kins",
				module: "service allowances",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "verification-status",
				module: "service allowances",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "verification-status",
				module: "service allowances",
				active: true,
				createdBy: "Admin",
			},
			{
				action: "view",
				resource: "insert-name-supporter-and-approver",
				module: "service allowances",
				active: true,
				createdBy: "Admin",
			},
		])
	}
}
