import BaseSeeder from '@ioc:Adonis/Lucid/Seeder';
import Employee from 'App/Models/Employee';
import Permission from 'App/Models/Permission';
import Role from 'App/Models/Role';

export default class extends BaseSeeder {

	public async run () {
		const employees = await Employee.all();
		const roles = await Role.all();
		await Permission.createMany([
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[4]!.id,
				action: "view",
				resource: "Senarai Cuti Kakitangan",
				module: "Cuti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[4]!.id,
				action: "view",
				resource: "Butiran Cuti Kakitangan",
				module: "Cuti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[2]!.id,
				action: "view",
				resource: "Senarai Cuti Kakitangan",
				module: "Cuti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[2]!.id,
				action: "view",
				resource: "Butiran Cuti Kakitangan",
				module: "Cuti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[2]!.id,
				action: "view",
				resource: "Senarai Permohonan Pengumpulan Cuti Rehat",
				module: "Cuti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[2]!.id,
				action: "add",
				resource: "new application detaiils",
				module: "Cuti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[2]!.id,
				action: "view",
				resource: "Semak Status Penyokongan Permohonan Dari Ketua Seksyen",
				module: "Cuti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[2]!.id,
				action: "view",
				resource: "Semak Status Kelulusan Permohonan Dari Pengarah Bahagian",
				module: "Cuti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[2]!.id,
				action: "view",
				resource: "Semak Status Semakan Permohonan ",
				module: "Cuti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[2]!.id,
				action: "view",
				resource: "Semak Status Pengesahan Permohonan",
				module: "Cuti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[2]!.id,
				action: "view",
				resource: "Semak Keputusan Permohonan",
				module: "Cuti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[17]!.id,
				action: "view",
				resource: "Senarai Permohonan Pengumpulan Cuti Rehat",
				module: "Cuti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[17]!.id,
				action: "view",
				resource: "Butiran Permohonan Pengumpulan Cuti Rehat",
				module: "Cuti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[17]!.id,
				action: "support",
				resource: "Status Penyokong Permohonan Dari Ketua Seksyen",
				module: "Cuti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[15]!.id,
				action: "view",
				resource: "Senarai Permohonan Pengumpulan Cuti Rehat",
				module: "Cuti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[15]!.id,
				action: "view",
				resource: "Butiran Permohonan Pengumpulan Cuti Rehat",
				module: "Cuti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[15]!.id,
				action: "approve",
				resource: "Status Kelulusan Pemohonan",
				module: "Cuti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[4]!.id,
				action: "view",
				resource: "Butiran Permohonan Pengumpulan Cuti Rehat",
				module: "Cuti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[4]!.id,
				action: "view",
				resource: "Butiran Permohonan Pengumpulan Cuti Rehat",
				module: "Cuti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[4]!.id,
				action: "view",
				resource: "Semak Status Penyokongan Permohonan Dari Ketua Seksyen",
				module: "Cuti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[4]!.id,
				action: "view",
				resource: "Semak Status Kelulusan Permohonan Dari Pengarah Bahagian",
				module: "Cuti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[4]!.id,
				action: "verify",
				resource: "Status Semakan Permohonan",
				module: "Cuti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[4]!.id,
				action: "confirm",
				resource: "Status Pengesahan Permohonan",
				module: "Cuti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[4]!.id,
				action: "update",
				resource: "employee's details related to leave",
				module: "Cuti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[4]!.id,
				action: "update",
				resource: "overall status of the selected application",
				module: "Cuti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[4]!.id,
				action: "view",
				resource: "Senarai Kakitangan Yang Akan Bersara/Meninggal Dunia/Pengeluaran Awal",
				module: "Cuti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[4]!.id,
				action: "view",
				resource: "Butiran Kakitangan",
				module: "Cuti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[4]!.id,
				action: "view",
				resource: "Baki Cuti",
				module: "Cuti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[4]!.id,
				action: "view",
				resource: "Baki Cuti Maksimum",
				module: "Cuti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[4]!.id,
				action: "view",
				resource: "Nilai GCR",
				module: "Cuti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[4]!.id,
				action: "view",
				resource: "Status Semakan Kriteria untuk GCR",
				module: "Cuti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[4]!.id,
				action: "view",
				resource: "deduction details based on preset rules",
				module: "Cuti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[4]!.id,
				action: "update",
				resource: "GCR based on deduction details",
				module: "Cuti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[4]!.id,
				action: "update",
				resource: "overall status of the record",
				module: "Cuti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[2]!.id,
				action: "view",
				resource: "overall status of the record",
				module: "Cuti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[2]!.id,
				action: "view",
				resource: "Senarai Permohonan Pengeluaran GCR Awal",
				module: "Cuti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[2]!.id,
				action: "add",
				resource: "Permohonan Pengeluaran GCR Awal",
				module: "Cuti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[2]!.id,
				action: "view",
				resource: "Senarai Permohonan Pengeluaran GCR Awal",
				module: "Cuti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[2]!.id,
				action: "view",
				resource: "Status Penyokong Permohonan dari Pengarah Bahagian/Negeri",
				module: "Cuti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[2]!.id,
				action: "view",
				resource: "Status Semakan Kelayakan",
				module: "Cuti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[2]!.id,
				action: "view",
				resource: "Status Pengesahan Kelayakan",
				module: "Cuti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[2]!.id,
				action: "view",
				resource: "Status Perakuan Pemohonan",
				module: "Cuti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[2]!.id,
				action: "view",
				resource: "Status Pelulusan Pemohonan",
				module: "Cuti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[2]!.id,
				action: "view",
				resource: "overall status for the application",
				module: "Cuti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[15]!.id,
				action: "view",
				resource: "Senarai Permohonan Pengeluaran GCR Awal",
				module: "Cuti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[15]!.id,
				action: "view",
				resource: "Butiran Permohonan Pengeluaran GCR Awal",
				module: "Cuti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[15]!.id,
				action: "support",
				resource: "Status Penyokongan Permohonan",
				module: "Cuti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[4]!.id,
				action: "view",
				resource: "Senarai Permohonan Pengeluaran GCR Awal",
				module: "Cuti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[4]!.id,
				action: "view",
				resource: "Butiran Permohonan Pengeluaran GCR Awal",
				module: "Cuti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[4]!.id,
				action: "support",
				resource: "Status Penyokongan Permohonan",
				module: "Cuti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[4]!.id,
				action: "confirm",
				resource: "Status Pengesahan Permohonan",
				module: "Cuti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[4]!.id,
				action: "view",
				resource: "Status Perakuan Permohonan",
				module: "Cuti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[4]!.id,
				action: "view",
				resource: "Status Pelulusan Permohonan",
				module: "Cuti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[4]!.id,
				action: "view",
				resource: "Pengiraan Pengumpulan GCR",
				module: "Cuti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[4]!.id,
				action: "verity",
				resource: "Pengiraan Bayaran GCR",
				module: "Cuti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[4]!.id,
				action: "update",
				resource: "overall status for the application",
				module: "Cuti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[6]!.id,
				action: "view",
				resource: "Senarai Permohonan Pengeluaran GCR Awal",
				module: "Cuti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[6]!.id,
				action: "view",
				resource: "Butiran Permohonan Pengeluaran GCR Awal",
				module: "Cuti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[6]!.id,
				action: "view",
				resource: "Status Pengesahan Permohonan",
				module: "Cuti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[6]!.id,
				action: "certify",
				resource: "Status Perakuan Permohonan",
				module: "Cuti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[18]!.id,
				action: "view",
				resource: "Senarai Permohonan Pengeluaran GCR Awal",
				module: "Cuti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[18]!.id,
				action: "view",
				resource: "Butiran Permohonan Pengeluaran GCR Awal",
				module: "Cuti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[18]!.id,
				action: "view",
				resource: "Status Semakan Kelayakan",
				module: "Cuti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[18]!.id,
				action: "view",
				resource: "Status Pengesahan Permohonan",
				module: "Cuti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[18]!.id,
				action: "view",
				resource: "Status Perakuan Permohonan",
				module: "Cuti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[18]!.id,
				action: "certify",
				resource: "Status Pelulusan Permohonan",
				module: "Cuti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[2]!.id,
				action: "view",
				resource: "Senarai Rekod Permohonan Cuti",
				module: "Cuti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[2]!.id,
				action: "confirm",
				resource: "Pengesahan Maklumat Permohonan",
				module: "Cuti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[2]!.id,
				action: "view",
				resource: "Butiran Permohonan Cuti",
				module: "Cuti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[2]!.id,
				action: "view",
				resource: "Pengesahan Maklumat Permohonan",
				module: "Cuti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[2]!.id,
				action: "view",
				resource: "Status Penyokongan Permohonan",
				module: "Cuti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[2]!.id,
				action: "view",
				resource: "Status Semakan Permohonan",
				module: "Cuti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[2]!.id,
				action: "view",
				resource: "Status Pengesahan Permohonan",
				module: "Cuti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[2]!.id,
				action: "view",
				resource: "Senarai Penyokong dan Pelulus",
				module: "Cuti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[2]!.id,
				action: "view",
				resource: "Status Penyokongan Permohonan",
				module: "Cuti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[2]!.id,
				action: "view",
				resource: "Status Kelulusan Permohonan",
				module: "Cuti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[2]!.id,
				action: "view",
				resource: "overall status of the application",
				module: "Cuti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[15]!.id,
				action: "view",
				resource: "Senarai Rekod Permohonan Cuti",
				module: "Cuti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[15]!.id,
				action: "view",
				resource: "Butiran Permohonan Cuti",
				module: "Cuti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[15]!.id,
				action: "view",
				resource: "Status Pengesahan Maklumat Permohonan",
				module: "Cuti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[15]!.id,
				action: "support",
				resource: "Status Penyokongan Permohonan",
				module: "Cuti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[4]!.id,
				action: "view",
				resource: "Senarai Rekod Permohonan Cuti",
				module: "Cuti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[4]!.id,
				action: "view",
				resource: "Butiran Permohonan Cuti",
				module: "Cuti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[4]!.id,
				action: "view",
				resource: "Pengesahan Maklumat Permohonan",
				module: "Cuti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[4]!.id,
				action: "view",
				resource: "Status Penyokongan Permohonan",
				module: "Cuti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[4]!.id,
				action: "verify",
				resource: "Status Semakan Permohonan",
				module: "Cuti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[4]!.id,
				action: "confirm",
				resource: "Status Pengesahan Permohonan",
				module: "Cuti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[4]!.id,
				action: "update",
				resource: "Senarai Penyokong dan Pelulus",
				module: "Cuti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[4]!.id,
				action: "view",
				resource: "Status Penyokongan Permohonan",
				module: "Cuti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[4]!.id,
				action: "view",
				resource: "Status Kelulusan Permohonan",
				module: "Cuti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[4]!.id,
				action: "update",
				resource: "Maklumat Kakitangan",
				module: "Cuti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[4]!.id,
				action: "update",
				resource: "overall status of the application",
				module: "Cuti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[13]!.id,
				action: "view",
				resource: "Senarai Rekod Permohonan Cuti",
				module: "Cuti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[13]!.id,
				action: "view",
				resource: "Butiran Permohonan Cuti",
				module: "Cuti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[13]!.id,
				action: "view",
				resource: "Pengesahan Maklumat Permohonan",
				module: "Cuti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[13]!.id,
				action: "view",
				resource: "Status Penyokongan Permohonan",
				module: "Cuti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[13]!.id,
				action: "VIEW",
				resource: "Status Semakan Permohonan",
				module: "Cuti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[13]!.id,
				action: "confirm",
				resource: "Status Pengesahan Permohonan",
				module: "Cuti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[13]!.id,
				action: "support",
				resource: "Status Penyokongan Permohonan",
				module: "Cuti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[14]!.id,
				action: "view",
				resource: "Senarai Rekod Permohonan Cuti",
				module: "Cuti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[14]!.id,
				action: "view",
				resource: "Butiran Permohonan Cuti",
				module: "Cuti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[14]!.id,
				action: "view",
				resource: "Pengesahan Maklumat Permohonan",
				module: "Cuti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[14]!.id,
				action: "view",
				resource: "Status Penyokongan Permohonan",
				module: "Cuti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[14]!.id,
				action: "VIEW",
				resource: "Status Semakan Permohonan",
				module: "Cuti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[14]!.id,
				action: "confirm",
				resource: "Status Pengesahan Permohonan",
				module: "Cuti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[14]!.id,
				action: "view",
				resource: "Status Penyokongan Permohonan",
				module: "Cuti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[14]!.id,
				action: "approve",
				resource: "Status Kelulusan Permohonan",
				module: "Cuti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[2]!.id,
				action: "view",
				resource: "Senerai Rekod Permohonan",
				module: "Cuti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[2]!.id,
				action: "add",
				resource: "Butiran Rekod Permohonan",
				module: "Cuti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[2]!.id,
				action: "view",
				resource: "Butiran Rekod Permohonan",
				module: "Cuti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[2]!.id,
				action: "view",
				resource: "Status Pengesahan Butiran Maklumat dan Permohonan",
				module: "Cuti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[2]!.id,
				action: "view",
				resource: "Status Penyokongan Dari Pengaraha Bahagian/Negeri",
				module: "Cuti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[2]!.id,
				action: "view",
				resource: "Keputusan Mesyuarat",
				module: "Cuti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[2]!.id,
				action: "view",
				resource: "Status Permohonan dari Urus Setia",
				module: "Cuti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[2]!.id,
				action: "view",
				resource: "overall status for the application",
				module: "Cuti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[2]!.id,
				action: "view",
				resource: "Status Pengesahan dari Urus Setia",
				module: "Cuti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[2]!.id,
				action: "view",
				resource: "Status Pelulusan dari Pengarah Bahagian/Negeri",
				module: "Cuti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[2]!.id,
				action: "view",
				resource: "overall status for the application",
				module: "Cuti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[15]!.id,
				action: "view",
				resource: "Senarai Rekod Permohonan",
				module: "Cuti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[15]!.id,
				action: "view",
				resource: "Butiran Rekod Permohonan",
				module: "Cuti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[15]!.id,
				action: "view",
				resource: "Status Pengeshan Butiran Maklumat dan Permohonan",
				module: "Cuti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[15]!.id,
				action: "support",
				resource: "Status Penyokong Permohonan dari Ketua Bahagian/Negeri",
				module: "Cuti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[4]!.id,
				action: "view",
				resource: "Senarai Rekod Permohonan",
				module: "Cuti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[4]!.id,
				action: "view",
				resource: "Butiran Rekod Permohonan",
				module: "Cuti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[4]!.id,
				action: "view",
				resource: "Status Pengesahan Maklumat dan Permohonan",
				module: "Cuti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[4]!.id,
				action: "view",
				resource: "Status Penyokongan dari Pengarah Bahagian/Negeri",
				module: "Cuti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[4]!.id,
				action: "add",
				resource: "Keputusan Mesyuarat",
				module: "Cuti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[4]!.id,
				action: "approve",
				resource: "Status Permohonan dari Urus Setia",
				module: "Cuti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[4]!.id,
				action: "update",
				resource: "overall status for the application",
				module: "Cuti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[4]!.id,
				action: "confirm",
				resource: "Status Pengesahan dari Urus Setia",
				module: "Cuti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[4]!.id,
				action: "view",
				resource: "Status Pelulusan dari Pengarah Bahagian/Negeri",
				module: "Cuti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[4]!.id,
				action: "update",
				resource: "overall status for the application",
				module: "Cuti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[18]!.id,
				action: "view",
				resource: "Senarai Rekod Permohonan",
				module: "Cuti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[18]!.id,
				action: "view",
				resource: "Butiran Rekod Permohonan",
				module: "Cuti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[18]!.id,
				action: "view",
				resource: "Status Pengesahan Maklumat dan Permohonan",
				module: "Cuti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[18]!.id,
				action: "view",
				resource: "Status Penyokongan dari Pengarah Bahagian/Negeri",
				module: "Cuti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[18]!.id,
				action: "view",
				resource: "Status Pengesahan dari Urus Setia",
				module: "Cuti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[18]!.id,
				action: "approve",
				resource: "Status Kelulusan dari Ketua Pengarah",
				module: "Cuti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[2]!.id,
				action: "view",
				resource: "Senarai Rekod Permohonan",
				module: "Cuti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[2]!.id,
				action: "add",
				resource: "Butiran Maklumat Permohonan",
				module: "Cuti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[2]!.id,
				action: "confirm",
				resource: "Pengesahan Maklumat Permohonan",
				module: "Cuti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[2]!.id,
				action: "view",
				resource: "Butiran Maklumat Permohonan",
				module: "Cuti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[2]!.id,
				action: "download",
				resource: "Dokumen Sokongan",
				module: "Cuti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[2]!.id,
				action: "view",
				resource: "Status Pengesahan Maklumat Permohonan",
				module: "Cuti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[2]!.id,
				action: "view",
				resource: "Status Penyokongan Permohonan dari 'PN'",
				module: "Cuti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[2]!.id,
				action: "view",
				resource: "Status Pengesahan Permohonan dari Urus Setia",
				module: "Cuti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[2]!.id,
				action: "view",
				resource: "Status Penyokongan dari Pengarah Khidmat Pengurusan",
				module: "Cuti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[2]!.id,
				action: "view",
				resource: "Status Kelulusan dari Ketua Pengarah",
				module: "Cuti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[2]!.id,
				action: "view",
				resource: "overall status for the application",
				module: "Cuti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[15]!.id,
				action: "view",
				resource: "Senarai Rekod Permohonan",
				module: "Cuti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[15]!.id,
				action: "view",
				resource: "Butiran Maklumat Permohonan",
				module: "Cuti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[15]!.id,
				action: "downlaod",
				resource: "Dokumen Sokongan",
				module: "Cuti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[15]!.id,
				action: "support",
				resource: "Status Penyokongan Permohonan dari Pengarah Bahagian/Negeri",
				module: "Cuti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[15]!.id,
				action: "update",
				resource: "kelayakan cuti rehat terkini",
				module: "Cuti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[4]!.id,
				action: "view",
				resource: "Senarai Rekod Permohonan",
				module: "Cuti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[4]!.id,
				action: "view",
				resource: "Butiran Maklumat Permohonan",
				module: "Cuti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[4]!.id,
				action: "download",
				resource: "Dokumen Sokongan",
				module: "Cuti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[4]!.id,
				action: "view",
				resource: "Status Pengesahan Maklumat Permohonan",
				module: "Cuti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[4]!.id,
				action: "view",
				resource: "Status Penyokongan Permohonan dari Pengarah Bahagian/Negeri",
				module: "Cuti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[4]!.id,
				action: "certify",
				resource: "Status Semakan Kelayakan Permohonan Cuti",
				module: "Cuti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[4]!.id,
				action: "confirm",
				resource: "Status Pengesahan Permohonan Cuti",
				module: "Cuti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[4]!.id,
				action: "view",
				resource: "Status Penyokongan Permohonan dari Pengarah Khidmat Pengurusan",
				module: "Cuti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[4]!.id,
				action: "view",
				resource: "Status Kelulusan Permohonan dari Ketua Pengarah",
				module: "Cuti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[4]!.id,
				action: "update",
				resource: "overall status for the application",
				module: "Cuti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[16]!.id,
				action: "view",
				resource: "Senarai Rekod Permohonan",
				module: "Cuti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[16]!.id,
				action: "view",
				resource: "Butiran Maklumat Permohonan",
				module: "Cuti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[16]!.id,
				action: "download",
				resource: "Dokumen Sokongan",
				module: "Cuti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[16]!.id,
				action: "view",
				resource: "Status Pengesahan Maklumat Permohonan",
				module: "Cuti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[16]!.id,
				action: "view",
				resource: "Status Penyokongan Permohonan dari Pengarah Bahagian/Negeri",
				module: "Cuti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[16]!.id,
				action: "view",
				resource: "Status Semakan Kelayakan Permohonan Cuti",
				module: "Cuti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[16]!.id,
				action: "support",
				resource: "Status Penyokongan Permohonan",
				module: "Cuti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[18]!.id,
				action: "view",
				resource: "Senarai Rekod Permohonan",
				module: "Cuti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[18]!.id,
				action: "view",
				resource: "Butiran Maklumat Permohonan",
				module: "Cuti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[18]!.id,
				action: "download",
				resource: "Dokumen Sokongan",
				module: "Cuti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[18]!.id,
				action: "view",
				resource: "Status Pengesahan Maklumat Permohonan",
				module: "Cuti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[18]!.id,
				action: "view",
				resource: "Status Penyokongan Permohonan dari Pengarah Bahagian/Negeri",
				module: "Cuti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[18]!.id,
				action: "view",
				resource: "Status Semakan Kelayakan Permohonan Cuti",
				module: "Cuti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[18]!.id,
				action: "view",
				resource: "Status Penyokongan Maklumat Permohonan Cuti dari Pengarah Khidmat Pengurusan",
				module: "Cuti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[18]!.id,
				action: "approve",
				resource: "Status Kelulusan Permohonan",
				module: "Cuti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[2]!.id,
				action: "view",
				resource: "Senarai Rekod Permohonan",
				module: "Cuti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[2]!.id,
				action: "add",
				resource: "Butiran Permohonan Cuti",
				module: "Cuti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[2]!.id,
				action: "upload",
				resource: "Dokumen Perakuan Bersalin",
				module: "Cuti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[2]!.id,
				action: "view",
				resource: "Butiran Permohonan Cuti",
				module: "Cuti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[2]!.id,
				action: "download",
				resource: "Dokumen Perakuan Bersalin",
				module: "Cuti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[2]!.id,
				action: "view",
				resource: "Status Semakan Permohonan",
				module: "Cuti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[2]!.id,
				action: "view",
				resource: "Status Kelulusan Pengarah Khidmat Pengurusan",
				module: "Cuti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[2]!.id,
				action: "view",
				resource: "overall status of the application",
				module: "Cuti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[4]!.id,
				action: "view",
				resource: "Senarai Rekod Permohonan ",
				module: "Cuti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[4]!.id,
				action: "view",
				resource: "Butiran Permohonan Cuti",
				module: "Cuti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[4]!.id,
				action: "download",
				resource: "Dokumen Perakuan Bersalin",
				module: "Cuti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[4]!.id,
				action: "verify",
				resource: "Status Semakan Permohonan",
				module: "Cuti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[4]!.id,
				action: "view",
				resource: "Status Kelulusan Pengarah Khidmat Pengurusan",
				module: "Cuti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[4]!.id,
				action: "update",
				resource: "overall status of the application",
				module: "Cuti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[16]!.id,
				action: "view",
				resource: "Senarai Rekod Permohonan ",
				module: "Cuti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[16]!.id,
				action: "view",
				resource: "Butiran Permohonan Cuti",
				module: "Cuti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[16]!.id,
				action: "download",
				resource: "Dokumen Perakuan Bersalin",
				module: "Cuti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[16]!.id,
				action: "approve",
				resource: "Status Kelulusan Pengarah Khidmat Pengurusan",
				module: "Cuti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[2]!.id,
				action: "view",
				resource: "Senarai Rekod Permohonan",
				module: "Cuti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[2]!.id,
				action: "add",
				resource: "Butiran Permohonan Cuti",
				module: "Cuti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[2]!.id,
				action: "upload",
				resource: "Dokumen Sokong",
				module: "Cuti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[2]!.id,
				action: "view",
				resource: "Butiran Permohonan Cuti",
				module: "Cuti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[2]!.id,
				action: "download",
				resource: "Dokumen Sokongan",
				module: "Cuti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[2]!.id,
				action: "view",
				resource: "Status Penyokongan dari Pengarah Negeri/Bahagian",
				module: "Cuti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[2]!.id,
				action: "view",
				resource: "Status Semakan dari Urus Setia",
				module: "Cuti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[2]!.id,
				action: "view",
				resource: "overall application status",
				module: "Cuti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[15]!.id,
				action: "view",
				resource: "Senarai Rekod Permohonan",
				module: "Cuti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[15]!.id,
				action: "view",
				resource: "Butiran Permohonan Cuti",
				module: "Cuti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[15]!.id,
				action: "download",
				resource: "Dokumen Sokongan",
				module: "Cuti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[15]!.id,
				action: "support",
				resource: "Status Penyokongan Pengarah Negeri/Bahagian",
				module: "Cuti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[4]!.id,
				action: "view",
				resource: "Senarai Rekod Permohonan",
				module: "Cuti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[4]!.id,
				action: "view",
				resource: "Butiran Permohonan Cuti",
				module: "Cuti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[4]!.id,
				action: "download",
				resource: "Dokumen Sokongan",
				module: "Cuti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[4]!.id,
				action: "view",
				resource: "Status Penyokongan dari Pengarah Negeri/Bahagian",
				module: "Cuti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[4]!.id,
				action: "verify",
				resource: "Status Semakan dari Urus Setia",
				module: "Cuti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[4]!.id,
				action: "view",
				resource: "Status Kelulusan dari Pengarah Khidmat Pengurusan",
				module: "Cuti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[4]!.id,
				action: "view",
				resource: "overall application status",
				module: "Cuti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[16]!.id,
				action: "view",
				resource: "Senarai Rekod Permohonan",
				module: "Cuti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[16]!.id,
				action: "view",
				resource: "Butiran Permohonan Cuti",
				module: "Cuti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[16]!.id,
				action: "download",
				resource: "Dokumen Sokongan",
				module: "Cuti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[16]!.id,
				action: "view",
				resource: "Status Penyokongan dari Pengarah Negeri/Bahagian",
				module: "Cuti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[16]!.id,
				action: "view",
				resource: "Status Pengesahan dari Urus Setia",
				module: "Cuti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[16]!.id,
				action: "approve",
				resource: "Status Kelulusan dari Pengarah Khidmat Pengurusan",
				module: "Cuti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[2]!.id,
				action: "view",
				resource: "Senarai Rekod Permohonan",
				module: "Cuti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[2]!.id,
				action: "view",
				resource: "Butiran Rekod Permohonan",
				module: "Cuti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[2]!.id,
				action: "confirm",
				resource: "Status Pengesahan Permohonan",
				module: "Cuti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[2]!.id,
				action: "view",
				resource: "Butiran Rekod Permohonan",
				module: "Cuti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[2]!.id,
				action: "view",
				resource: "Status Pengesahan Permohonan",
				module: "Cuti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[2]!.id,
				action: "view",
				resource: "Status Penyokongan Permohonan dari Pengarah Negeri/Bahagian",
				module: "Cuti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[2]!.id,
				action: "view",
				resource: "Status Semakan Permohonan dari Urus Setia",
				module: "Cuti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[2]!.id,
				action: "view",
				resource: "Status Pengesahan Permohonan dari Urus Setia",
				module: "Cuti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[2]!.id,
				action: "view",
				resource: "Status Pelulusan Permohonan dari Pengarah Khidmat Pengurusan",
				module: "Cuti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[2]!.id,
				action: "view",
				resource: "overall status of the application",
				module: "Cuti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[15]!.id,
				action: "view",
				resource: "Senarai Rekod Permohonan",
				module: "Cuti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[15]!.id,
				action: "view",
				resource: "Butiran Rekod Permohonan",
				module: "Cuti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[15]!.id,
				action: "view",
				resource: "Status Pengesahan Permohonan",
				module: "Cuti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[15]!.id,
				action: "support",
				resource: "Status Penyokongan Permohonan dari Pengarah Negeri/Bahagian",
				module: "Cuti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[4]!.id,
				action: "view",
				resource: "Senarai Rekod Permohonan",
				module: "Cuti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[4]!.id,
				action: "view",
				resource: "Butiran Rekod Permohonan",
				module: "Cuti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[4]!.id,
				action: "view",
				resource: "Status Pengesahan Permohonan",
				module: "Cuti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[4]!.id,
				action: "view",
				resource: "Status Penyokongan Permohonan dari Pengarah Negeri/Bahagian",
				module: "Cuti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[4]!.id,
				action: "verify",
				resource: "Status Semakan Permohonan dari Urus Setia",
				module: "Cuti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[4]!.id,
				action: "confirm",
				resource: "Status Pengesahan Permohonan dari Urus Setia",
				module: "Cuti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[4]!.id,
				action: "view",
				resource: "Status Kelulusan Permohonan dari Pengarah Khidmat Pengurusan",
				module: "Cuti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[4]!.id,
				action: "update",
				resource: "overall status of the application",
				module: "Cuti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[16]!.id,
				action: "view",
				resource: "Senarai Rekod Permohonan",
				module: "Cuti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[16]!.id,
				action: "view",
				resource: "Butiran Rekod Permohonan",
				module: "Cuti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[16]!.id,
				action: "view",
				resource: "Status Pengesahan Permohonan",
				module: "Cuti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[16]!.id,
				action: "view",
				resource: "Status Penyokongan Permohonan dari Pengarah Negeri/Bahagian",
				module: "Cuti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[16]!.id,
				action: "view",
				resource: "Status Semakan Permohonan dari Urus Setia",
				module: "Cuti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[16]!.id,
				action: "view",
				resource: "Status Pengesahan Permohonan dari Urus Setia",
				module: "Cuti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[16]!.id,
				action: "view",
				resource: "Status Kelulusan Permohonan dari Pengarah Khidmat Pengurusan",
				module: "Cuti",
				active: true,
				createdBy: "Admin",
			},
		])
	}
}
