import BaseSeeder from '@ioc:Adonis/Lucid/Seeder';
import Employee from 'App/Models/Employee';
import Permission from 'App/Models/Permission';
import Role from 'App/Models/Role';

export default class extends BaseSeeder {

	public async run () {
		const employees = await Employee.all();
		const roles = await Role.all();
		await Permission.createMany([
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[2]!.id,
				action: "add",
				resource: "Butiran Permohonan",
				module: "Elaun-Elaun Perkhidmatan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[2]!.id,
				action: "upload",
				resource: "Dokumen Sokongan",
				module: "Elaun-Elaun Perkhidmatan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[2]!.id,
				action: "view",
				resource: "application details and their supported documents",
				module: "Elaun-Elaun Perkhidmatan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[2]!.id,
				action: "view",
				resource: "the support status of the application",
				module: "Elaun-Elaun Perkhidmatan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[2]!.id,
				action: "view",
				resource: "the verification status of the application from 'US Elaun'",
				module: "Elaun-Elaun Perkhidmatan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[2]!.id,
				action: "view",
				resource: "who is the approver and supporter",
				module: "Elaun-Elaun Perkhidmatan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[2]!.id,
				action: "view",
				resource: "the approval status of the application",
				module: "Elaun-Elaun Perkhidmatan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[2]!.id,
				action: "view",
				resource: "the overall status of the application",
				module: "Elaun-Elaun Perkhidmatan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[12]!.id,
				action: "view",
				resource: "and search list of application",
				module: "Elaun-Elaun Perkhidmatan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[12]!.id,
				action: "view",
				resource: "the application details and uploaded documents",
				module: "Elaun-Elaun Perkhidmatan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[12]!.id,
				action: "view",
				resource: "the support status of the application",
				module: "Elaun-Elaun Perkhidmatan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[12]!.id,
				action: "update",
				resource: "the verification status of the application",
				module: "Elaun-Elaun Perkhidmatan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[12]!.id,
				action: "update",
				resource: "approver and supporter into the application",
				module: "Elaun-Elaun Perkhidmatan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[12]!.id,
				action: "view",
				resource: "the approval status of the application",
				module: "Elaun-Elaun Perkhidmatan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[12]!.id,
				action: "update",
				resource: "the overall status of the application",
				module: "Elaun-Elaun Perkhidmatan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[15]!.id,
				action: "view",
				resource: "and search list of application",
				module: "Elaun-Elaun Perkhidmatan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[15]!.id,
				action: "view",
				resource: "the application details and uploaded documents",
				module: "Elaun-Elaun Perkhidmatan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[15]!.id,
				action: "update",
				resource: "support status of the application",
				module: "Elaun-Elaun Perkhidmatan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[13]!.id,
				action: "view",
				resource: "and search list of application",
				module: "Elaun-Elaun Perkhidmatan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[13]!.id,
				action: "view",
				resource: "the application details and uploaded documents",
				module: "Elaun-Elaun Perkhidmatan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[13]!.id,
				action: "view",
				resource: "the support status of the application from 'PN'",
				module: "Elaun-Elaun Perkhidmatan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[13]!.id,
				action: "view",
				resource: "the verification status of the application from 'US Elaun'",
				module: "Elaun-Elaun Perkhidmatan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[13]!.id,
				action: "update",
				resource: "the support status of the application",
				module: "Elaun-Elaun Perkhidmatan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[14]!.id,
				action: "view",
				resource: "and search list of application",
				module: "Elaun-Elaun Perkhidmatan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[14]!.id,
				action: "view",
				resource: "the application details and uploaded documents",
				module: "Elaun-Elaun Perkhidmatan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[14]!.id,
				action: "view",
				resource: "the support status of the application from 'PN'",
				module: "Elaun-Elaun Perkhidmatan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[14]!.id,
				action: "view",
				resource: "the verification status of the application from 'US Elaun'",
				module: "Elaun-Elaun Perkhidmatan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[14]!.id,
				action: "view",
				resource: "the support status of the application",
				module: "Elaun-Elaun Perkhidmatan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[14]!.id,
				action: "update",
				resource: "the approval status of the application from 'Penyokong'",
				module: "Elaun-Elaun Perkhidmatan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[2]!.id,
				action: "view",
				resource: "and search list of application",
				module: "Elaun-Elaun Perkhidmatan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[2]!.id,
				action: "add",
				resource: "application details and the supporting documents",
				module: "Elaun-Elaun Perkhidmatan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[2]!.id,
				action: "view",
				resource: "application details and its supporting documents",
				module: "Elaun-Elaun Perkhidmatan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[2]!.id,
				action: "view",
				resource: "the verification status of the application from 'US Elaun'",
				module: "Elaun-Elaun Perkhidmatan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[2]!.id,
				action: "view",
				resource: "the support status of the application from 'Penyokong'",
				module: "Elaun-Elaun Perkhidmatan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[2]!.id,
				action: "view",
				resource: "the approval status of the application from 'Pelulus'",
				module: "Elaun-Elaun Perkhidmatan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[2]!.id,
				action: "view",
				resource: "the application overall status",
				module: "Elaun-Elaun Perkhidmatan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[2]!.id,
				action: "download",
				resource: "Surat Kelulusan",
				module: "Elaun-Elaun Perkhidmatan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[12]!.id,
				action: "view",
				resource: "and search list of application",
				module: "Elaun-Elaun Perkhidmatan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[12]!.id,
				action: "view",
				resource: "application details and its supporting documents",
				module: "Elaun-Elaun Perkhidmatan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[12]!.id,
				action: "update",
				resource: "verification status of the application",
				module: "Elaun-Elaun Perkhidmatan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[12]!.id,
				action: "update",
				resource: "approver and supporter into the application",
				module: "Elaun-Elaun Perkhidmatan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[12]!.id,
				action: "view",
				resource: "the support status into the application",
				module: "Elaun-Elaun Perkhidmatan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[12]!.id,
				action: "view",
				resource: "the verification status for the application",
				module: "Elaun-Elaun Perkhidmatan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[12]!.id,
				action: "update",
				resource: "the overall status of the application",
				module: "Elaun-Elaun Perkhidmatan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[13]!.id,
				action: "view",
				resource: "and search list of application",
				module: "Elaun-Elaun Perkhidmatan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[13]!.id,
				action: "view",
				resource: "the application details and its supporting documents",
				module: "Elaun-Elaun Perkhidmatan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[13]!.id,
				action: "view",
				resource: "the verification status of the application",
				module: "Elaun-Elaun Perkhidmatan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[13]!.id,
				action: "update",
				resource: "the support status into the application",
				module: "Elaun-Elaun Perkhidmatan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[14]!.id,
				action: "view",
				resource: "and search list of application",
				module: "Elaun-Elaun Perkhidmatan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[14]!.id,
				action: "view",
				resource: "the application details and its supporting documents",
				module: "Elaun-Elaun Perkhidmatan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[14]!.id,
				action: "view",
				resource: "the verification status of the application",
				module: "Elaun-Elaun Perkhidmatan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[14]!.id,
				action: "view",
				resource: "the support status for the application",
				module: "Elaun-Elaun Perkhidmatan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[14]!.id,
				action: "update",
				resource: "the approval status into the application",
				module: "Elaun-Elaun Perkhidmatan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[12]!.id,
				action: "view",
				resource: "list of application for funeral service",
				module: "Elaun-Elaun Perkhidmatan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[12]!.id,
				action: "add",
				resource: "the application details for funeral service",
				module: "Elaun-Elaun Perkhidmatan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[12]!.id,
				action: "upload",
				resource: "Lampiran B",
				module: "Elaun-Elaun Perkhidmatan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[12]!.id,
				action: "view",
				resource: "the application details for funeral service",
				module: "Elaun-Elaun Perkhidmatan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[12]!.id,
				action: "view",
				resource: "Lampiran B",
				module: "Elaun-Elaun Perkhidmatan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[12]!.id,
				action: "view",
				resource: "verification status for the application",
				module: "Elaun-Elaun Perkhidmatan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[12]!.id,
				action: "view",
				resource: "support status for the application",
				module: "Elaun-Elaun Perkhidmatan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[12]!.id,
				action: "view",
				resource: "approval status for the application",
				module: "Elaun-Elaun Perkhidmatan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[12]!.id,
				action: "view",
				resource: "verification and confirmation status from the next of kins",
				module: "Elaun-Elaun Perkhidmatan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[12]!.id,
				action: "view",
				resource: "the status of the application",
				module: "Elaun-Elaun Perkhidmatan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[12]!.id,
				action: "view",
				resource: "list of application for funeral service",
				module: "Elaun-Elaun Perkhidmatan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[12]!.id,
				action: "view",
				resource: "application details for funeral service",
				module: "Elaun-Elaun Perkhidmatan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[12]!.id,
				action: "update",
				resource: "verification status of the application",
				module: "Elaun-Elaun Perkhidmatan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[12]!.id,
				action: "update",
				resource: "the supporter and approver into the application",
				module: "Elaun-Elaun Perkhidmatan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[12]!.id,
				action: "view",
				resource: "the support status of the application",
				module: "Elaun-Elaun Perkhidmatan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[12]!.id,
				action: "view",
				resource: "the approval status of the application",
				module: "Elaun-Elaun Perkhidmatan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[12]!.id,
				action: "download",
				resource: "the payment order to finance department",
				module: "Elaun-Elaun Perkhidmatan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[12]!.id,
				action: "update",
				resource: "the overall status",
				module: "Elaun-Elaun Perkhidmatan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[13]!.id,
				action: "view",
				resource: "the list of application",
				module: "Elaun-Elaun Perkhidmatan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[13]!.id,
				action: "view",
				resource: "the application details",
				module: "Elaun-Elaun Perkhidmatan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[13]!.id,
				action: "view",
				resource: "verification status of the application",
				module: "Elaun-Elaun Perkhidmatan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[13]!.id,
				action: "update",
				resource: "the support status of the application",
				module: "Elaun-Elaun Perkhidmatan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[14]!.id,
				action: "view",
				resource: "the list of application",
				module: "Elaun-Elaun Perkhidmatan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[14]!.id,
				action: "view",
				resource: "the application details",
				module: "Elaun-Elaun Perkhidmatan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[14]!.id,
				action: "view",
				resource: "verification status of the application",
				module: "Elaun-Elaun Perkhidmatan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[14]!.id,
				action: "view",
				resource: "the support status of the application",
				module: "Elaun-Elaun Perkhidmatan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[14]!.id,
				action: "update",
				resource: "the approval status of the application",
				module: "Elaun-Elaun Perkhidmatan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[2]!.id,
				action: "view",
				resource: "the list of application",
				module: "Elaun-Elaun Perkhidmatan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[2]!.id,
				action: "add",
				resource: "the application details and its supported document",
				module: "Elaun-Elaun Perkhidmatan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[2]!.id,
				action: "view",
				resource: "the application details and its supported document",
				module: "Elaun-Elaun Perkhidmatan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[2]!.id,
				action: "view",
				resource: "the support status from 'PN'",
				module: "Elaun-Elaun Perkhidmatan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[2]!.id,
				action: "view",
				resource: "US Elaun",
				module: "Elaun-Elaun Perkhidmatan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[2]!.id,
				action: "view",
				resource: "supporter and approver for the application",
				module: "Elaun-Elaun Perkhidmatan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[2]!.id,
				action: "view",
				resource: "Penyokong",
				module: "Elaun-Elaun Perkhidmatan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[2]!.id,
				action: "view",
				resource: "overall status of the application",
				module: "Elaun-Elaun Perkhidmatan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[12]!.id,
				action: "view",
				resource: "the list of application",
				module: "Elaun-Elaun Perkhidmatan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[12]!.id,
				action: "view",
				resource: "the application details and its supported documents",
				module: "Elaun-Elaun Perkhidmatan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[12]!.id,
				action: "view",
				resource: "the support status from 'PN'",
				module: "Elaun-Elaun Perkhidmatan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[12]!.id,
				action: "update",
				resource: "verification status for the the application",
				module: "Elaun-Elaun Perkhidmatan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[12]!.id,
				action: "update",
				resource: "supporter and approver into the application",
				module: "Elaun-Elaun Perkhidmatan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[12]!.id,
				action: "view",
				resource: "Penyokong",
				module: "Elaun-Elaun Perkhidmatan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[12]!.id,
				action: "download",
				resource: "payment order for finance department",
				module: "Elaun-Elaun Perkhidmatan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[12]!.id,
				action: "update",
				resource: "the overall status for the application",
				module: "Elaun-Elaun Perkhidmatan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[15]!.id,
				action: "view",
				resource: "the application list",
				module: "Elaun-Elaun Perkhidmatan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[15]!.id,
				action: "view",
				resource: "the application details and its supported documents",
				module: "Elaun-Elaun Perkhidmatan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[15]!.id,
				action: "update",
				resource: "the support status for the application",
				module: "Elaun-Elaun Perkhidmatan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[13]!.id,
				action: "view",
				resource: "the list of application",
				module: "Elaun-Elaun Perkhidmatan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[13]!.id,
				action: "view",
				resource: "the applicationd details and its supported documents",
				module: "Elaun-Elaun Perkhidmatan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[13]!.id,
				action: "view",
				resource: "PN",
				module: "Elaun-Elaun Perkhidmatan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[13]!.id,
				action: "view",
				resource: "US Elaun",
				module: "Elaun-Elaun Perkhidmatan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[13]!.id,
				action: "update",
				resource: "the support status for the application",
				module: "Elaun-Elaun Perkhidmatan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[14]!.id,
				action: "view",
				resource: "the list of application",
				module: "Elaun-Elaun Perkhidmatan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[14]!.id,
				action: "view",
				resource: "the application details and its supported documents",
				module: "Elaun-Elaun Perkhidmatan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[14]!.id,
				action: "view",
				resource: "PN",
				module: "Elaun-Elaun Perkhidmatan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[14]!.id,
				action: "view",
				resource: "US Elaun",
				module: "Elaun-Elaun Perkhidmatan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[14]!.id,
				action: "view",
				resource: "Penyokong",
				module: "Elaun-Elaun Perkhidmatan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[14]!.id,
				action: "update",
				resource: "the approval status for the application",
				module: "Elaun-Elaun Perkhidmatan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[2]!.id,
				action: "view",
				resource: "the list of application",
				module: "Elaun-Elaun Perkhidmatan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[2]!.id,
				action: "add",
				resource: "the application details and its supported documents",
				module: "Elaun-Elaun Perkhidmatan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[2]!.id,
				action: "view",
				resource: "the application details and its supported documents",
				module: "Elaun-Elaun Perkhidmatan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[2]!.id,
				action: "view",
				resource: "the verification status from 'US Elaun'",
				module: "Elaun-Elaun Perkhidmatan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[2]!.id,
				action: "view",
				resource: "the support status from 'Penyokong'",
				module: "Elaun-Elaun Perkhidmatan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[2]!.id,
				action: "view",
				resource: "overall status of application",
				module: "Elaun-Elaun Perkhidmatan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[12]!.id,
				action: "view",
				resource: "the list of application",
				module: "Elaun-Elaun Perkhidmatan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[12]!.id,
				action: "view",
				resource: "the application and its supported documents",
				module: "Elaun-Elaun Perkhidmatan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[12]!.id,
				action: "update",
				resource: "the verification status for the application",
				module: "Elaun-Elaun Perkhidmatan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[12]!.id,
				action: "update",
				resource: "approver and supporter into the application",
				module: "Elaun-Elaun Perkhidmatan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[12]!.id,
				action: "view",
				resource: "the support status of the application",
				module: "Elaun-Elaun Perkhidmatan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[12]!.id,
				action: "view",
				resource: "the approval status of the application",
				module: "Elaun-Elaun Perkhidmatan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[12]!.id,
				action: "update",
				resource: "the overall status of the application",
				module: "Elaun-Elaun Perkhidmatan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[13]!.id,
				action: "view",
				resource: "the list of application",
				module: "Elaun-Elaun Perkhidmatan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[13]!.id,
				action: "view",
				resource: "the application details and its supported documents",
				module: "Elaun-Elaun Perkhidmatan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[13]!.id,
				action: "view",
				resource: "US Elaun",
				module: "Elaun-Elaun Perkhidmatan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[13]!.id,
				action: "update",
				resource: "the support status for the application",
				module: "Elaun-Elaun Perkhidmatan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[14]!.id,
				action: "view",
				resource: "the list of application",
				module: "Elaun-Elaun Perkhidmatan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[14]!.id,
				action: "view",
				resource: "the application details and its supported documents",
				module: "Elaun-Elaun Perkhidmatan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[14]!.id,
				action: "view",
				resource: "US Elaun",
				module: "Elaun-Elaun Perkhidmatan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[14]!.id,
				action: "view",
				resource: "Penyokong",
				module: "Elaun-Elaun Perkhidmatan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[14]!.id,
				action: "update",
				resource: "the approval status for the application",
				module: "Elaun-Elaun Perkhidmatan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[2]!.id,
				action: "view",
				resource: "and search list of application",
				module: "Elaun-Elaun Perkhidmatan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[2]!.id,
				action: "add",
				resource: "the application details",
				module: "Elaun-Elaun Perkhidmatan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[2]!.id,
				action: "view",
				resource: "the application details",
				module: "Elaun-Elaun Perkhidmatan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[2]!.id,
				action: "view",
				resource: "uploaded supported documents from 'US Elaun'",
				module: "Elaun-Elaun Perkhidmatan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[2]!.id,
				action: "view",
				resource: "support status of the application",
				module: "Elaun-Elaun Perkhidmatan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[2]!.id,
				action: "view",
				resource: "approval status of the application",
				module: "Elaun-Elaun Perkhidmatan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[2]!.id,
				action: "view",
				resource: "overall status of the application",
				module: "Elaun-Elaun Perkhidmatan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[12]!.id,
				action: "view",
				resource: "and search list of application",
				module: "Elaun-Elaun Perkhidmatan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[12]!.id,
				action: "view",
				resource: "the application details",
				module: "Elaun-Elaun Perkhidmatan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[12]!.id,
				action: "upload",
				resource: "the supported document",
				module: "Elaun-Elaun Perkhidmatan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[12]!.id,
				action: "update",
				resource: "the approver and supporter into the application",
				module: "Elaun-Elaun Perkhidmatan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[12]!.id,
				action: "view",
				resource: "support status of the application",
				module: "Elaun-Elaun Perkhidmatan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[12]!.id,
				action: "view",
				resource: "approval status of the application",
				module: "Elaun-Elaun Perkhidmatan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[12]!.id,
				action: "update",
				resource: "invoice details and its documents related to the application to the system",
				module: "Elaun-Elaun Perkhidmatan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[12]!.id,
				action: "download",
				resource: "payment order to the finance department",
				module: "Elaun-Elaun Perkhidmatan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[12]!.id,
				action: "update",
				resource: "overall status of the application",
				module: "Elaun-Elaun Perkhidmatan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[13]!.id,
				action: "view",
				resource: "and search list of application",
				module: "Elaun-Elaun Perkhidmatan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[13]!.id,
				action: "view",
				resource: "the application details and its supported document",
				module: "Elaun-Elaun Perkhidmatan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[13]!.id,
				action: "update",
				resource: "support status for the application",
				module: "Elaun-Elaun Perkhidmatan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[14]!.id,
				action: "view",
				resource: "and search list of application",
				module: "Elaun-Elaun Perkhidmatan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[14]!.id,
				action: "view",
				resource: "the application details and its supported documents",
				module: "Elaun-Elaun Perkhidmatan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[14]!.id,
				action: "view",
				resource: "the support status of the application",
				module: "Elaun-Elaun Perkhidmatan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[14]!.id,
				action: "update",
				resource: "approval status for the application",
				module: "Elaun-Elaun Perkhidmatan",
				active: true,
				createdBy: "Admin",
			},
		])
	}
}
