import BaseSeeder from '@ioc:Adonis/Lucid/Seeder';
import Employee from 'App/Models/Employee';
import Permission from 'App/Models/Permission';
import Role from 'App/Models/Role';

export default class extends BaseSeeder {

	public async run () {
		const employees = await Employee.all();
		const roles = await Role.all();
		await Permission.createMany([
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[6]!.id,
				action: "view",
				resource: "Senarai Rekod Pekerja untuk proses tindakan surcaj",
				module: "Integriti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[6]!.id,
				action: "add",
				resource: "Butiran Rekod untuk Tindakan Surcaj",
				module: "Integriti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[6]!.id,
				action: "add",
				resource: "Cara Pembayaran",
				module: "Integriti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[6]!.id,
				action: "update",
				resource: "overall status of the record",
				module: "Integriti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[6]!.id,
				action: "view",
				resource: "Butiran Rekod untuk Tindakan Surcaj",
				module: "Integriti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[6]!.id,
				action: "view",
				resource: "Cara Pembayaran",
				module: "Integriti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[6]!.id,
				action: "view",
				resource: "overall status of the record",
				module: "Integriti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[2]!.id,
				action: "view",
				resource: "Senarai Rekod Pekerja untuk proses tindakan surcaj",
				module: "Integriti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[2]!.id,
				action: "view",
				resource: "Butiran Rekod untuk Tindakan Surcaj",
				module: "Integriti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[2]!.id,
				action: "view",
				resource: "Cara Pembayaran",
				module: "Integriti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[2]!.id,
				action: "view",
				resource: "overall status of the record",
				module: "Integriti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[6]!.id,
				action: "view",
				resource: "Senarai Rekod Pertuduhan",
				module: "Integriti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[6]!.id,
				action: "add",
				resource: "Keputusan Mesyuarat",
				module: "Integriti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[6]!.id,
				action: "update",
				resource: "overall status",
				module: "Integriti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[6]!.id,
				action: "view",
				resource: "Butiran Rekod",
				module: "Integriti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[6]!.id,
				action: "view",
				resource: "Keputusan Mesyuarat",
				module: "Integriti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[6]!.id,
				action: "view",
				resource: "overall status",
				module: "Integriti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[2]!.id,
				action: "view",
				resource: "Senarai Rekod Pertuduhan",
				module: "Integriti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[2]!.id,
				action: "view",
				resource: "Butiran Rekod",
				module: "Integriti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[2]!.id,
				action: "view",
				resource: "Keputusan Mesyuarat",
				module: "Integriti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[2]!.id,
				action: "view",
				resource: "overall status",
				module: "Integriti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[6]!.id,
				action: "view",
				resource: "Senarai Rekod Penentuan Hukuman",
				module: "Integriti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[6]!.id,
				action: "add",
				resource: "Keputusan Mesyuarat",
				module: "Integriti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[6]!.id,
				action: "update",
				resource: "overall status",
				module: "Integriti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[6]!.id,
				action: "view",
				resource: "Butiran Rekod",
				module: "Integriti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[6]!.id,
				action: "view",
				resource: "Keputusan Mesyuarat",
				module: "Integriti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[6]!.id,
				action: "view",
				resource: "overall status",
				module: "Integriti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[2]!.id,
				action: "view",
				resource: "Senarai Rekod Penentuan Hukuman",
				module: "Integriti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[2]!.id,
				action: "view",
				resource: "Butiran Rekod",
				module: "Integriti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[2]!.id,
				action: "view",
				resource: "Keputusan Mesyuarat",
				module: "Integriti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[2]!.id,
				action: "view",
				resource: "overall status",
				module: "Integriti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[2]!.id,
				action: "view",
				resource: "Senarai Permohonan Rayuan",
				module: "Integriti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[2]!.id,
				action: "add",
				resource: "Butiran Permohonan Rayuan",
				module: "Integriti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[2]!.id,
				action: "view",
				resource: "Butiran Permohonan Rayuan",
				module: "Integriti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[2]!.id,
				action: "view",
				resource: "Keputusan Rayuan",
				module: "Integriti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[6]!.id,
				action: "view",
				resource: "Senarai Permohonan Rayuan",
				module: "Integriti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[6]!.id,
				action: "view",
				resource: "Butiran Permohonan Rayuan",
				module: "Integriti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[6]!.id,
				action: "update",
				resource: "Keputusan Mesyuarat",
				module: "Integriti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[6]!.id,
				action: "view",
				resource: "Senarai Rekod Tahan Kerja",
				module: "Integriti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[6]!.id,
				action: "add",
				resource: "Butiran Rekod Tahan Kerja",
				module: "Integriti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[6]!.id,
				action: "update",
				resource: "Keputusan Mesyuarat",
				module: "Integriti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[6]!.id,
				action: "view",
				resource: "Butiran Rekod Tahan Kerja",
				module: "Integriti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[6]!.id,
				action: "view",
				resource: "Keputusan Mesyuarat",
				module: "Integriti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[2]!.id,
				action: "view",
				resource: "Senarai Rekod Tahan Kerja",
				module: "Integriti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[2]!.id,
				action: "view",
				resource: "Butiran Rekod Tahan Kerja",
				module: "Integriti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[2]!.id,
				action: "view",
				resource: "Keputusan Mesyuarat",
				module: "Integriti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[6]!.id,
				action: "view",
				resource: "Senarai Rekod Gantung Kerja",
				module: "Integriti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[6]!.id,
				action: "add",
				resource: "Butiran Rekod Gantung Kerja",
				module: "Integriti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[6]!.id,
				action: "update",
				resource: "Keputusan Mesyuarat",
				module: "Integriti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[6]!.id,
				action: "view",
				resource: "Butiran Rekod Gantung Kerja",
				module: "Integriti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[6]!.id,
				action: "view",
				resource: "Keputusan Mesyuarat",
				module: "Integriti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[2]!.id,
				action: "view",
				resource: "Senarai Rekod Gantung Kerja",
				module: "Integriti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[2]!.id,
				action: "view",
				resource: "Butiran Rekod Gantung Kerja",
				module: "Integriti",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[2]!.id,
				action: "view",
				resource: "Keputusan Mesyuarat",
				module: "Integriti",
				active: true,
				createdBy: "Admin",
			},
		])
	}
}
