import BaseSeeder from '@ioc:Adonis/Lucid/Seeder';
import Employee from 'App/Models/Employee';
import Permission from 'App/Models/Permission';
import Role from 'App/Models/Role';

export default class extends BaseSeeder {

	public async run () {
		const employees = await Employee.all();
		const roles = await Role.all();
		await Permission.createMany([
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[20]!.id,
				action: "view",
				resource: "Senarai Permohonan",
				module: "Kakitangan Kontrak",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[20]!.id,
				action: "add",
				resource: "Butiran Permohonan",
				module: "Kakitangan Kontrak",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[20]!.id,
				action: "view",
				resource: "Butiran Permohonan",
				module: "Kakitangan Kontrak",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[20]!.id,
				action: "view",
				resource: "Status Semakan Maklumat Calon",
				module: "Kakitangan Kontrak",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[20]!.id,
				action: "view",
				resource: "Status memenuhi kriteria",
				module: "Kakitangan Kontrak",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[20]!.id,
				action: "update",
				resource: "Butiran Permohonan",
				module: "Kakitangan Kontrak",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[20]!.id,
				action: "view",
				resource: "Status Penyokongan Permohonan",
				module: "Kakitangan Kontrak",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[20]!.id,
				action: "view",
				resource: "ID Kakitangan",
				module: "Kakitangan Kontrak",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[3]!.id,
				action: "view",
				resource: "Senarai Permohonan",
				module: "Kakitangan Kontrak",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[3]!.id,
				action: "view",
				resource: "Butiran Permohonan",
				module: "Kakitangan Kontrak",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[3]!.id,
				action: "verify",
				resource: "Maklumat Calon",
				module: "Kakitangan Kontrak",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[3]!.id,
				action: "update",
				resource: "Memenuhi Kriteria",
				module: "Kakitangan Kontrak",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[3]!.id,
				action: "update",
				resource: "approver",
				module: "Kakitangan Kontrak",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[3]!.id,
				action: "support",
				resource: "Status Permohonan",
				module: "Kakitangan Kontrak",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[3]!.id,
				action: "approve",
				resource: "Status Permohonan",
				module: "Kakitangan Kontrak",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[3]!.id,
				action: "view",
				resource: "ID Kakitangan",
				module: "Kakitangan Kontrak",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[3]!.id,
				action: "update",
				resource: "Maklumat Kakitangan",
				module: "Kakitangan Kontrak",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[13]!.id,
				action: "view",
				resource: "Senarai Permohonan",
				module: "Kakitangan Kontrak",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[13]!.id,
				action: "view",
				resource: "Butiran Permohonan",
				module: "Kakitangan Kontrak",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[13]!.id,
				action: "view",
				resource: "Status Semakan Maklumat Calon",
				module: "Kakitangan Kontrak",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[13]!.id,
				action: "view",
				resource: "Memenuhi Kriteria",
				module: "Kakitangan Kontrak",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[13]!.id,
				action: "support",
				resource: "Status Penyokongan Permohonan",
				module: "Kakitangan Kontrak",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[14]!.id,
				action: "view",
				resource: "Senarai Permohonan",
				module: "Kakitangan Kontrak",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[14]!.id,
				action: "view",
				resource: "Butiran Permohonan",
				module: "Kakitangan Kontrak",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[14]!.id,
				action: "view",
				resource: "Status Semakan Maklumat Calon",
				module: "Kakitangan Kontrak",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[14]!.id,
				action: "view",
				resource: "Memenuhi Kriteria",
				module: "Kakitangan Kontrak",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[14]!.id,
				action: "view",
				resource: "Status Penyokongan Permohonan",
				module: "Kakitangan Kontrak",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[14]!.id,
				action: "approve",
				resource: "Status Kelulusan Permohonan",
				module: "Kakitangan Kontrak",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[9]!.id,
				action: "view",
				resource: "senarai kakitangan akan tamat kontrak",
				module: "Kakitangan Kontrak",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[9]!.id,
				action: "view",
				resource: "Butiran Kakitangan yang akan tamat kontrak",
				module: "Kakitangan Kontrak",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[9]!.id,
				action: "view",
				resource: "Status Perakuan dari Pengarah Bahagian/Negeri",
				module: "Kakitangan Kontrak",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[9]!.id,
				action: "confirm",
				resource: "Status Pengesahan Pemohonan",
				module: "Kakitangan Kontrak",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[9]!.id,
				action: "update",
				resource: "approver",
				module: "Kakitangan Kontrak",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[9]!.id,
				action: "view",
				resource: "Status Penyokongan Permohonan",
				module: "Kakitangan Kontrak",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[9]!.id,
				action: "view",
				resource: "Status Kelulusan Permohonan",
				module: "Kakitangan Kontrak",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[9]!.id,
				action: "view",
				resource: "Borang Perjanjian",
				module: "Kakitangan Kontrak",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[9]!.id,
				action: "confirm",
				resource: "Status Pengesahan Borang Perjanjian",
				module: "Kakitangan Kontrak",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[9]!.id,
				action: "update",
				resource: "the overall status of the application",
				module: "Kakitangan Kontrak",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[2]!.id,
				action: "view",
				resource: "Senarai Kakitangan Yang akan Tamat Kontrak",
				module: "Kakitangan Kontrak",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[2]!.id,
				action: "view",
				resource: "Butiran Kakitangan Yamg akan tamat kontrak",
				module: "Kakitangan Kontrak",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[2]!.id,
				action: "view",
				resource: "Status Perakuan dari Pengarah Bahagian/Negeri",
				module: "Kakitangan Kontrak",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[2]!.id,
				action: "view",
				resource: "Status Pengesahan Pemohonan",
				module: "Kakitangan Kontrak",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[2]!.id,
				action: "view",
				resource: "approver",
				module: "Kakitangan Kontrak",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[2]!.id,
				action: "view",
				resource: "Status Penyokongan Permohonan",
				module: "Kakitangan Kontrak",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[2]!.id,
				action: "view",
				resource: "Status Kelulusan Permohonan",
				module: "Kakitangan Kontrak",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[2]!.id,
				action: "update",
				resource: "Borang Perjanjian",
				module: "Kakitangan Kontrak",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[2]!.id,
				action: "view",
				resource: "Status Pengesahan Borang Perjanjian",
				module: "Kakitangan Kontrak",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[2]!.id,
				action: "view",
				resource: "the overall status of the application",
				module: "Kakitangan Kontrak",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[2]!.id,
				action: "download",
				resource: "Surat Kontrak Perjanjian Baru",
				module: "Kakitangan Kontrak",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[15]!.id,
				action: "view",
				resource: "senarai kakitangan akan tamat kontrak",
				module: "Kakitangan Kontrak",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[15]!.id,
				action: "view",
				resource: "Butiran kakitangan akan tamat kontrak",
				module: "Kakitangan Kontrak",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[15]!.id,
				action: "certify",
				resource: "Status Perakuan dari Pengarah Bahagian/Negeri",
				module: "Kakitangan Kontrak",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[13]!.id,
				action: "view",
				resource: "senarai kakitangan akan tamat kontrak",
				module: "Kakitangan Kontrak",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[13]!.id,
				action: "view",
				resource: "Butiran Kakitangan yang akan tamat kontrak",
				module: "Kakitangan Kontrak",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[13]!.id,
				action: "view",
				resource: "Status Perakuan dari Pengarah Bahagian/Negeri",
				module: "Kakitangan Kontrak",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[13]!.id,
				action: "view",
				resource: "Status Pengesahan ",
				module: "Kakitangan Kontrak",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[13]!.id,
				action: "support",
				resource: "Status Penyokongan Permohonan",
				module: "Kakitangan Kontrak",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[14]!.id,
				action: "view",
				resource: "senarai kakitangan akan tamat kontrak",
				module: "Kakitangan Kontrak",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[14]!.id,
				action: "view",
				resource: "Butiran Kakitangan yang akan tamat kontrak",
				module: "Kakitangan Kontrak",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[14]!.id,
				action: "view",
				resource: "Status Perakuan dari Pengarah Bahagian/Negeri",
				module: "Kakitangan Kontrak",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[14]!.id,
				action: "view",
				resource: "Status Pengesahan Pemohonan",
				module: "Kakitangan Kontrak",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[14]!.id,
				action: "view",
				resource: "Status Penyokongan Pemohonan",
				module: "Kakitangan Kontrak",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[14]!.id,
				action: "approve",
				resource: "Status Kelulusan Permohonan",
				module: "Kakitangan Kontrak",
				active: true,
				createdBy: "Admin",
			},
		])
	}
}
