import BaseSeeder from '@ioc:Adonis/Lucid/Seeder';
import Employee from 'App/Models/Employee';
import Permission from 'App/Models/Permission';
import Role from 'App/Models/Role';

export default class extends BaseSeeder {

	public async run () {
		const employees = await Employee.all();
		const roles = await Role.all();
		await Permission.createMany([
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[8]!.id,
				action: "view",
				resource: "Senarai Peperiksaan",
				module: "Latihan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[8]!.id,
				action: "add",
				resource: "Butiran Maklumat Peperiksaan",
				module: "Latihan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[2]!.id,
				action: "view",
				resource: "Senarai Pemohonan Menduduki Peperiksaan",
				module: "Latihan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[2]!.id,
				action: "view",
				resource: "Butiran Pemohonon",
				module: "Latihan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[2]!.id,
				action: "view",
				resource: "Status Semakan Permohonan",
				module: "Latihan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[2]!.id,
				action: "view",
				resource: "Status Pengesahan Permohonan",
				module: "Latihan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[2]!.id,
				action: "download",
				resource: "Surat Panggilan Peperiksaan",
				module: "Latihan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[2]!.id,
				action: "view",
				resource: "Keputusan Peperiksaan dari Panel Pemeriksaan",
				module: "Latihan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[8]!.id,
				action: "view",
				resource: "Senarai Pemohonan Menduduki Peperiksaan",
				module: "Latihan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[8]!.id,
				action: "view",
				resource: "Butiran Pemohonon",
				module: "Latihan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[8]!.id,
				action: "verify",
				resource: "Status Semakan Permohonan",
				module: "Latihan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[8]!.id,
				action: "download",
				resource: "Surat Panggilan Peperiksaan",
				module: "Latihan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[8]!.id,
				action: "view",
				resource: "Keputusan Peperiksaan dari Panel Pemeriksaan",
				module: "Latihan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[2]!.id,
				action: "view",
				resource: "Senarai Permohonan Pembiayaan Pelajaran",
				module: "Latihan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[2]!.id,
				action: "add",
				resource: "Butiran Permohonan Pembiayaan Pelajaran",
				module: "Latihan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[2]!.id,
				action: "upload",
				resource: "Dokumen Sokongan",
				module: "Latihan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[2]!.id,
				action: "view",
				resource: "Butiran Permohonan",
				module: "Latihan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[2]!.id,
				action: "download",
				resource: "Dokumen Sokongan",
				module: "Latihan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[2]!.id,
				action: "view",
				resource: "Status Penyokongan Permohonan dari Pengarah Negeri/Bahagian",
				module: "Latihan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[2]!.id,
				action: "view",
				resource: "Status Perakukan Permohonan dari Urus Setia Integriti",
				module: "Latihan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[2]!.id,
				action: "view",
				resource: "Status Semakan Permohonan",
				module: "Latihan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[2]!.id,
				action: "view",
				resource: "Status Pengesahan Permohonan",
				module: "Latihan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[2]!.id,
				action: "view",
				resource: "Keputusan Mesyuarat",
				module: "Latihan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[2]!.id,
				action: "download",
				resource: "Surat Lulus Permohonan",
				module: "Latihan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[2]!.id,
				action: "view",
				resource: "overall status of the application",
				module: "Latihan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[8]!.id,
				action: "view",
				resource: "Senarai Rekod Permohonan",
				module: "Latihan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[8]!.id,
				action: "view",
				resource: "Butiran Rekod Permohonan",
				module: "Latihan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[8]!.id,
				action: "download",
				resource: "Dokumen Sokongan",
				module: "Latihan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[8]!.id,
				action: "view",
				resource: "Status Penyokongan Permohonan dari Pengarah Negeri/Bahagian",
				module: "Latihan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[8]!.id,
				action: "view",
				resource: "Status Perakukan Permohonan dari Urus Setia Integriti",
				module: "Latihan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[8]!.id,
				action: "verify",
				resource: "Status Semakan Permohonan",
				module: "Latihan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[8]!.id,
				action: "confirm",
				resource: "Status Pengesahan Permohonan",
				module: "Latihan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[8]!.id,
				action: "update",
				resource: "Keputusan Mesyuarat",
				module: "Latihan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[8]!.id,
				action: "update",
				resource: "overall status of the application",
				module: "Latihan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[15]!.id,
				action: "view",
				resource: "Senarai Rekod Permohonan",
				module: "Latihan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[15]!.id,
				action: "view",
				resource: "Butiran Rekod Permohonan",
				module: "Latihan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[15]!.id,
				action: "download",
				resource: "Dokumen Sokongan",
				module: "Latihan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[15]!.id,
				action: "support",
				resource: "Status Penyokongan Permohonan dari Pengarah Negeri/Bahagian",
				module: "Latihan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[6]!.id,
				action: "view",
				resource: "Senarai Rekod Permohonan",
				module: "Latihan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[6]!.id,
				action: "view",
				resource: "Butiran Rekod Permohonan",
				module: "Latihan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[6]!.id,
				action: "download",
				resource: "Dokumen Sokongan",
				module: "Latihan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[6]!.id,
				action: "view",
				resource: "Status Penyokongan Permohonan dari Pengarah Negeri/Bahagian",
				module: "Latihan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[8]!.id,
				action: "certify",
				resource: "Status Perakukan Permohonan dari Urus Setia Integriti",
				module: "Latihan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[2]!.id,
				action: "view",
				resource: "Senarai Permohonan",
				module: "Latihan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[2]!.id,
				action: "add",
				resource: "Butiran Permohonan",
				module: "Latihan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[2]!.id,
				action: "upload",
				resource: "Dokumen Sokongan",
				module: "Latihan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[2]!.id,
				action: "view",
				resource: "Butiran Permohonan",
				module: "Latihan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[2]!.id,
				action: "download",
				resource: "Dokumen Sokongan",
				module: "Latihan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[2]!.id,
				action: "view",
				resource: "Status Semakan Permohonan",
				module: "Latihan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[2]!.id,
				action: "view",
				resource: "Status Pengesahan Permohonan",
				module: "Latihan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[2]!.id,
				action: "view",
				resource: "overal status",
				module: "Latihan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[8]!.id,
				action: "view",
				resource: "Senarai Permohonan",
				module: "Latihan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[8]!.id,
				action: "view",
				resource: "Butiran Permohonan",
				module: "Latihan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[8]!.id,
				action: "download",
				resource: "Dokumen Sokongan",
				module: "Latihan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[8]!.id,
				action: "verify",
				resource: "Status Semakan Permohonan",
				module: "Latihan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[8]!.id,
				action: "confirm",
				resource: "Status Pengesahan Permohonan",
				module: "Latihan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[8]!.id,
				action: "download",
				resource: "arahan bayaran",
				module: "Latihan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[8]!.id,
				action: "update",
				resource: "overal status",
				module: "Latihan",
				active: true,
				createdBy: "Admin",
			},
		])
	}
}
