import BaseSeeder from '@ioc:Adonis/Lucid/Seeder';
import Employee from 'App/Models/Employee';
import Permission from 'App/Models/Permission';
import Role from 'App/Models/Role';

export default class extends BaseSeeder {

	public async run () {
		const employees = await Employee.all();
		const roles = await Role.all();
		await Permission.createMany([
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[90]!.id,
				action: "view",
				resource: "senarai permohonan klinik panel",
				module: "Perubatan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[90]!.id,
				action: "add",
				resource: "new application and its details for panel clinic",
				module: "Perubatan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[90]!.id,
				action: "view",
				resource: "application details for panel clinic",
				module: "Perubatan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[90]!.id,
				action: "view",
				resource: "Status Semakan Permohonan",
				module: "Perubatan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[90]!.id,
				action: "view",
				resource: "Status Pengesahan Permohonan",
				module: "Perubatan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[90]!.id,
				action: "view",
				resource: "Status Penyokongan Permohonan",
				module: "Perubatan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[90]!.id,
				action: "view",
				resource: "Status Pelulusan Permohonan",
				module: "Perubatan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[90]!.id,
				action: "download",
				resource: "Cetak Surat Perlantikan Klinik Panel",
				module: "Perubatan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[90]!.id,
				action: "view",
				resource: "overall status of the applicaton",
				module: "Perubatan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[11]!.id,
				action: "view",
				resource: "senarai permohonan klinik panel",
				module: "Perubatan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[11]!.id,
				action: "view",
				resource: "selected application and its details",
				module: "Perubatan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[11]!.id,
				action: "verify",
				resource: "the selected application by updating the status to either 'SEMAK/TIDAK SEMAK'",
				module: "Perubatan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[11]!.id,
				action: "confirm",
				resource: "the selected application by updaing the status to either 'SAH/TIDAK SAH'",
				module: "Perubatan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[11]!.id,
				action: "update",
				resource: "the name of supporter and approver",
				module: "Perubatan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[11]!.id,
				action: "view",
				resource: "the current support status for the application",
				module: "Perubatan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[11]!.id,
				action: "download",
				resource: "surat perlantikan klinik panel",
				module: "Perubatan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[11]!.id,
				action: "update",
				resource: "the overall status of the application",
				module: "Perubatan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[13]!.id,
				action: "view",
				resource: "senarai permohonan klinik panel",
				module: "Perubatan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[13]!.id,
				action: "view",
				resource: "selected application and its details",
				module: "Perubatan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[13]!.id,
				action: "view",
				resource: "Status Semakan Permohonan",
				module: "Perubatan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[13]!.id,
				action: "view",
				resource: "Status Pengesahan Permohonan",
				module: "Perubatan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[13]!.id,
				action: "update",
				resource: "the selected application by updating the status to either 'SOKONG/TIDAK SOKONG'",
				module: "Perubatan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[14]!.id,
				action: "view",
				resource: "senarai permohon klinik panel",
				module: "Perubatan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[14]!.id,
				action: "view",
				resource: "selected application and its details",
				module: "Perubatan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[14]!.id,
				action: "view",
				resource: "Status Semakan Permohonan",
				module: "Perubatan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[14]!.id,
				action: "view",
				resource: "Status Pengesahan Permohonan",
				module: "Perubatan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[14]!.id,
				action: "view",
				resource: "Status Penyokong Permohonan",
				module: "Perubatan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[14]!.id,
				action: "update",
				resource: "the selected application by updating the status to either 'LULUS/TIDAK LULUS'",
				module: "Perubatan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[21]!.id,
				action: "view",
				resource: "Senarai Rekod Bil Tuntutan",
				module: "Perubatan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[21]!.id,
				action: "add",
				resource: "Borang Bil Tuntutan",
				module: "Perubatan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[21]!.id,
				action: "view",
				resource: "selected details for bil tuntutan",
				module: "Perubatan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[21]!.id,
				action: "view",
				resource: "Status Semakan Permohonan",
				module: "Perubatan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[21]!.id,
				action: "view",
				resource: "Status Kelulusan Permohonan",
				module: "Perubatan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[21]!.id,
				action: "edit",
				resource: "TIDAK LULUS",
				module: "Perubatan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[21]!.id,
				action: "view",
				resource: "Status Penyokongan Permohonan",
				module: "Perubatan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[21]!.id,
				action: "view",
				resource: "Status Pelulusan Permohonan",
				module: "Perubatan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[21]!.id,
				action: "view",
				resource: "overall status of the application",
				module: "Perubatan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[11]!.id,
				action: "view",
				resource: "Senarai Rekod Bil Tuntutan",
				module: "Perubatan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[11]!.id,
				action: "view",
				resource: "Butiran Rekod Bil Tuntutan",
				module: "Perubatan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[11]!.id,
				action: "update",
				resource: "the selected record by updating the status to either 'SEMAK/TIDAK SEMAK'",
				module: "Perubatan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[11]!.id,
				action: "update",
				resource: "the selected record by updating the status to either 'LULUS/TIDAK LULUS'",
				module: "Perubatan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[11]!.id,
				action: "update",
				resource: "the name of the approver and supporter",
				module: "Perubatan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[11]!.id,
				action: "view",
				resource: "Status Penyokongan Permohonan",
				module: "Perubatan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[11]!.id,
				action: "view",
				resource: "Status Kelulusan Permohonan",
				module: "Perubatan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[11]!.id,
				action: "download",
				resource: "Mencetak Arahan Bayaran Mengikut Penempatan Kakitangan",
				module: "Perubatan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[11]!.id,
				action: "update",
				resource: "the overall status of the application",
				module: "Perubatan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[13]!.id,
				action: "view",
				resource: "Senarai Rekod Bil Tuntutan",
				module: "Perubatan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[13]!.id,
				action: "view",
				resource: "Butiran Rekod Bil Tuntutan",
				module: "Perubatan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[13]!.id,
				action: "view",
				resource: "Status Semakan Permohonan",
				module: "Perubatan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[13]!.id,
				action: "view",
				resource: "Status Kelulusan Permohonan",
				module: "Perubatan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[13]!.id,
				action: "update",
				resource: "the selected record by updating the status to either 'SOKONG/TIDAK SOKONG'",
				module: "Perubatan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[14]!.id,
				action: "view",
				resource: "Senarai Rekod Bil Tuntutan",
				module: "Perubatan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[14]!.id,
				action: "view",
				resource: "Butiran Rekod Bil Tuntutan",
				module: "Perubatan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[14]!.id,
				action: "view",
				resource: "Status Semakan Permohonan",
				module: "Perubatan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[14]!.id,
				action: "view",
				resource: "Status Kelulusan Permohonan",
				module: "Perubatan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[14]!.id,
				action: "view",
				resource: "Status Penyokongan Permohonan",
				module: "Perubatan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[14]!.id,
				action: "update",
				resource: "the selected record by updating the status to either 'LULUS/TIDAK LULUS'",
				module: "Perubatan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[2]!.id,
				action: "view",
				resource: "Senarai Permohonan Tuntutan",
				module: "Perubatan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[2]!.id,
				action: "add",
				resource: "Butiran Permohonan Tuntutan",
				module: "Perubatan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[2]!.id,
				action: "upload",
				resource: "Resit Pembelian Ubat/Klinik",
				module: "Perubatan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[2]!.id,
				action: "view",
				resource: "Butiran Permohonan Tuntutan",
				module: "Perubatan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[2]!.id,
				action: "view",
				resource: ""Resit Pembelian Ubat/Klinik",
				module: "Perubatan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[2]!.id,
				action: "view",
				resource: "Status Semak Baki Peruntukan Kakitangan",
				module: "Perubatan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[2]!.id,
				action: "view",
				resource: "Status Penyemakan Permohonan",
				module: "Perubatan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[2]!.id,
				action: "view",
				resource: "Status Kelulusan Permohonan",
				module: "Perubatan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[2]!.id,
				action: "view",
				resource: "Status Penyokongan Permohonan",
				module: "Perubatan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[2]!.id,
				action: "view",
				resource: "Status Kelulusan Permohonan",
				module: "Perubatan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[2]!.id,
				action: "view",
				resource: "overall status of the application",
				module: "Perubatan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[11]!.id,
				action: "view",
				resource: "Senarai Permohonan Tuntutan",
				module: "Perubatan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[11]!.id,
				action: "view",
				resource: "Butiran Permohonan Tuntutan",
				module: "Perubatan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[11]!.id,
				action: "download",
				resource: "Resit Pembelian Ubat/Klinik",
				module: "Perubatan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[11]!.id,
				action: "view",
				resource: "Status Semak Baki Peruntukan Kakitangan",
				module: "Perubatan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[11]!.id,
				action: "verify",
				resource: "Status Penyemakan Permohonan",
				module: "Perubatan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[11]!.id,
				action: "approve",
				resource: "Status Kelulusan Permohonan",
				module: "Perubatan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[11]!.id,
				action: "view",
				resource: "Status Penyokongan Permohonan",
				module: "Perubatan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[11]!.id,
				action: "view",
				resource: "Status Kelulusan Permohonan",
				module: "Perubatan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[11]!.id,
				action: "download",
				resource: "payment order to finance department",
				module: "Perubatan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[11]!.id,
				action: "update",
				resource: "the overall status of the application",
				module: "Perubatan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[13]!.id,
				action: "view",
				resource: "Senarai Permohonan Tuntutan",
				module: "Perubatan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[13]!.id,
				action: "view",
				resource: "Butiran Permohonan Tuntutan",
				module: "Perubatan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[13]!.id,
				action: "view",
				resource: ""Resit Pembelian Ubat/Klinik",
				module: "Perubatan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[13]!.id,
				action: "view",
				resource: "Status Semak Baki Peruntukan Kakitangan",
				module: "Perubatan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[13]!.id,
				action: "view",
				resource: "Status Penyemakan Permohonan",
				module: "Perubatan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[13]!.id,
				action: "view",
				resource: "Status Kelulusan Permohonan",
				module: "Perubatan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[13]!.id,
				action: "update",
				resource: "Status Penyokongan Permohonan",
				module: "Perubatan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[14]!.id,
				action: "view",
				resource: "Senarai Permohonan Tuntutan",
				module: "Perubatan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[14]!.id,
				action: "view",
				resource: "Butiran Permohonan Tuntutan",
				module: "Perubatan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[14]!.id,
				action: "view",
				resource: ""Resit Pembelian Ubat/Klinik",
				module: "Perubatan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[14]!.id,
				action: "view",
				resource: "Status Semak Baki Peruntukan Kakitangan",
				module: "Perubatan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[14]!.id,
				action: "view",
				resource: "Status Penyemakan Permohonan",
				module: "Perubatan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[14]!.id,
				action: "view",
				resource: "Status Kelulusan Permohonan",
				module: "Perubatan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[14]!.id,
				action: "view",
				resource: "Status Penyokongan Permohonan",
				module: "Perubatan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[14]!.id,
				action: "update",
				resource: "Status Kelulusan Permohonan",
				module: "Perubatan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[2]!.id,
				action: "view",
				resource: "Baki Perubatan Kakitangan",
				module: "Perubatan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[2]!.id,
				action: "download",
				resource: "surat melebihi had penggunaan perubatan tahunan",
				module: "Perubatan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[2]!.id,
				action: "download",
				resource: "arahan penolakan gaji",
				module: "Perubatan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[2]!.id,
				action: "upload",
				resource: "Bukti Pembayaran",
				module: "Perubatan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[2]!.id,
				action: "view",
				resource: "Semak Pengesahan Bukti Pembayaran",
				module: "Perubatan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[2]!.id,
				action: "upload",
				resource: "Butki Pembayaran",
				module: "Perubatan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[2]!.id,
				action: "view",
				resource: "Baki Perubatan Kakitangan",
				module: "Perubatan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[11]!.id,
				action: "view",
				resource: "Senarai Kakitangan Yang Melebihi Kuota",
				module: "Perubatan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[11]!.id,
				action: "view",
				resource: "details of selected employee",
				module: "Perubatan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[11]!.id,
				action: "view",
				resource: "if which payment the employee wanted",
				module: "Perubatan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[11]!.id,
				action: "download",
				resource: "Bukti Pembayaran",
				module: "Perubatan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[11]!.id,
				action: "confirm",
				resource: "Bukti Pembayaran",
				module: "Perubatan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[11]!.id,
				action: "update",
				resource: "Baki Perubatan Kakitangan",
				module: "Perubatan",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[11]!.id,
				action: "update",
				resource: "record where that particular record no longer over budget",
				module: "Perubatan",
				active: true,
				createdBy: "Admin",
			},
		])
	}
}
