import BaseSeeder from '@ioc:Adonis/Lucid/Seeder';
import Employee from 'App/Models/Employee';
import Permission from 'App/Models/Permission';
import Role from 'App/Models/Role';

export default class extends BaseSeeder {

	public async run () {
		const employees = await Employee.all();
		const roles = await Role.all();
		await Permission.createMany([
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[2]!.id,
				action: "view",
				resource: "Senarai Permohonan Pinjaman Komputer dan Telefon Pintar",
				module: "Pinjaman",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[2]!.id,
				action: "add",
				resource: "Butiran Permohonan Pinjaman",
				module: "Pinjaman",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[2]!.id,
				action: "upload",
				resource: "Dokumen Sokongan dan Sebut Harga",
				module: "Pinjaman",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[2]!.id,
				action: "view",
				resource: "Butiran Permohonan Pinjaman",
				module: "Pinjaman",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[2]!.id,
				action: "download",
				resource: "Dokumen Sokongan dan Sebut Harga",
				module: "Pinjaman",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[2]!.id,
				action: "view",
				resource: "Status Semakan Permohonan",
				module: "Pinjaman",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[2]!.id,
				action: "view",
				resource: "Mengisi nama bagi Pelulus",
				module: "Pinjaman",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[2]!.id,
				action: "view",
				resource: "Status Penyokongan dari Ketua Seksyen",
				module: "Pinjaman",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[2]!.id,
				action: "view",
				resource: "Status Kelulusan",
				module: "Pinjaman",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[2]!.id,
				action: "view",
				resource: "Maklumat Pinjaman, Jadual Pertama dan Kedua",
				module: "Pinjaman",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[2]!.id,
				action: "download",
				resource: "Surat Tawaran Kelulusan Pinjaman dan Surat Iringan",
				module: "Pinjaman",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[2]!.id,
				action: "download",
				resource: "Surat Tawaran",
				module: "Pinjaman",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[2]!.id,
				action: "download",
				resource: "offer letter from the system",
				module: "Pinjaman",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[2]!.id,
				action: "upload",
				resource: "Surat Perjanjian",
				module: "Pinjaman",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[2]!.id,
				action: "upload",
				resource: "receipt and invoice to the system",
				module: "Pinjaman",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[10]!.id,
				action: "",
				resource: "",
				module: "Pinjaman",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[10]!.id,
				action: "",
				resource: "",
				module: "Pinjaman",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[10]!.id,
				action: "update",
				resource: "status to application details to either 'SEMAK/TIDAK SEMAK'",
				module: "Pinjaman",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[10]!.id,
				action: "update",
				resource: "approver name",
				module: "Pinjaman",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[10]!.id,
				action: "",
				resource: "",
				module: "Pinjaman",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[10]!.id,
				action: "edit",
				resource: "jadual pertama dan kedua",
				module: "Pinjaman",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[10]!.id,
				action: "download",
				resource: "offer letter",
				module: "Pinjaman",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[10]!.id,
				action: "download",
				resource: "surat perjanjian",
				module: "Pinjaman",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[10]!.id,
				action: "download",
				resource: "update",
				module: "Pinjaman",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[10]!.id,
				action: "download",
				resource: "receipt and invoice from the system",
				module: "Pinjaman",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[17]!.id,
				action: "",
				resource: "",
				module: "Pinjaman",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[17]!.id,
				action: "update",
				resource: "status to supported the application in one go",
				module: "Pinjaman",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[17]!.id,
				action: "",
				resource: "",
				module: "Pinjaman",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[17]!.id,
				action: "update",
				resource: "status to support selected application",
				module: "Pinjaman",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[14]!.id,
				action: "view",
				resource: "and list of application for smartphone and computer loan",
				module: "Pinjaman",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[14]!.id,
				action: "view",
				resource: "application details and any supported document for selected application",
				module: "Pinjaman",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[14]!.id,
				action: "view",
				resource: "status of application supports",
				module: "Pinjaman",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[14]!.id,
				action: "update",
				resource: "status to approve the application",
				module: "Pinjaman",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[2]!.id,
				action: "view",
				resource: "and list of application for vehicle loan that related to themselves only",
				module: "Pinjaman",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[2]!.id,
				action: "add",
				resource: "application details and supporting documents for vehicle loan",
				module: "Pinjaman",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[2]!.id,
				action: "view",
				resource: "application status",
				module: "Pinjaman",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[2]!.id,
				action: "download",
				resource: "offer letter from the system",
				module: "Pinjaman",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[2]!.id,
				action: "upload",
				resource: "Surat Perjanjian",
				module: "Pinjaman",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[2]!.id,
				action: "upload",
				resource: "receipt and invoice to the system",
				module: "Pinjaman",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[10]!.id,
				action: "view",
				resource: "and list of application for vehicle loan",
				module: "Pinjaman",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[10]!.id,
				action: "view",
				resource: "application details and any supported documents for each selected employee",
				module: "Pinjaman",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[10]!.id,
				action: "update",
				resource: "status to application details to either 'SEMAK/TIDAK SEMAK'",
				module: "Pinjaman",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[10]!.id,
				action: "update",
				resource: "approver name",
				module: "Pinjaman",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[10]!.id,
				action: "view",
				resource: "support and approval status",
				module: "Pinjaman",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[10]!.id,
				action: "edit",
				resource: "jadual pertama dan kedua",
				module: "Pinjaman",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[10]!.id,
				action: "download",
				resource: "offer letter",
				module: "Pinjaman",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[10]!.id,
				action: "download",
				resource: "surat perjanjian",
				module: "Pinjaman",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[10]!.id,
				action: "download",
				resource: "payment voucher and updated loan application details",
				module: "Pinjaman",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[10]!.id,
				action: "update",
				resource: "No Chasis and No Enjin",
				module: "Pinjaman",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[10]!.id,
				action: "download",
				resource: "receipt and invoice uploaded by applicant",
				module: "Pinjaman",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[17]!.id,
				action: "view",
				resource: "and list of application for smartphone and computer loan",
				module: "Pinjaman",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[17]!.id,
				action: "update",
				resource: "status to supported the application in one go",
				module: "Pinjaman",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[14]!.id,
				action: "view",
				resource: "application details and any supported document for selected application",
				module: "Pinjaman",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[14]!.id,
				action: "view",
				resource: "status of application supports",
				module: "Pinjaman",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[14]!.id,
				action: "update",
				resource: "status to approve the application",
				module: "Pinjaman",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[14]!.id,
				action: "view",
				resource: "and list of application for smartphone and computer loan",
				module: "Pinjaman",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[14]!.id,
				action: "view",
				resource: "application details and any supported document for selected application",
				module: "Pinjaman",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[14]!.id,
				action: "view",
				resource: "status of application supports",
				module: "Pinjaman",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[14]!.id,
				action: "update",
				resource: "status to approve the application",
				module: "Pinjaman",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[2]!.id,
				action: "view",
				resource: "and search list of application that belongs to themselves",
				module: "Pinjaman",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[2]!.id,
				action: "add",
				resource: "application details",
				module: "Pinjaman",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[2]!.id,
				action: "view",
				resource: "application details of selected application",
				module: "Pinjaman",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[2]!.id,
				action: "view",
				resource: "US Pinjaman",
				module: "Pinjaman",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[10]!.id,
				action: "view",
				resource: "and search list of application",
				module: "Pinjaman",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[10]!.id,
				action: "view",
				resource: "selected application details and its supported documents",
				module: "Pinjaman",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[10]!.id,
				action: "update",
				resource: "SEMAK/TIDAK SEMAK",
				module: "Pinjaman",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[10]!.id,
				action: "update",
				resource: "LULUS/TIDAK LULUS",
				module: "Pinjaman",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[10]!.id,
				action: "download",
				resource: "Surat Tawaran menduduki Kuarters",
				module: "Pinjaman",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[15]!.id,
				action: "view",
				resource: "and search list of application for quarters",
				module: "Pinjaman",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[15]!.id,
				action: "view",
				resource: "application details and supported document",
				module: "Pinjaman",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[15]!.id,
				action: "view",
				resource: "the status if the application is verified, and approved status by the 'US Pinjaman'",
				module: "Pinjaman",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[15]!.id,
				action: "update",
				resource: "status of application approval process",
				module: "Pinjaman",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[91]!.id,
				action: "view",
				resource: "and search list of application for quarters",
				module: "Pinjaman",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[91]!.id,
				action: "view",
				resource: "the application details and the supported documents",
				module: "Pinjaman",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[91]!.id,
				action: "view",
				resource: "status of the application",
				module: "Pinjaman",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[91]!.id,
				action: "update",
				resource: "Maklumat Pemotongan Mengikut Jenis Kelayakan Kuarters",
				module: "Pinjaman",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[91]!.id,
				action: "download",
				resource: "Surat Tawaran menduduki Kuarters",
				module: "Pinjaman",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[10]!.id,
				action: "view",
				resource: "and search list of application for quarters from non-LKIM",
				module: "Pinjaman",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[10]!.id,
				action: "add",
				resource: "application details on behalf of non-LKIM",
				module: "Pinjaman",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[10]!.id,
				action: "view",
				resource: "application details",
				module: "Pinjaman",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[10]!.id,
				action: "view",
				resource: "status of approval of application",
				module: "Pinjaman",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[10]!.id,
				action: "update",
				resource: "upload",
				module: "Pinjaman",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[10]!.id,
				action: "download",
				resource: "Surat Tawaran Menduduki Kuarters",
				module: "Pinjaman",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[15]!.id,
				action: "view",
				resource: "and search list of application for quarters from non-LKIM",
				module: "Pinjaman",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[15]!.id,
				action: "view",
				resource: "application details for quarters for selected application",
				module: "Pinjaman",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[15]!.id,
				action: "update",
				resource: "approval status for the application",
				module: "Pinjaman",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[91]!.id,
				action: "view",
				resource: "and search list of application for quarters from non-LKIM",
				module: "Pinjaman",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[91]!.id,
				action: "view",
				resource: "application details for quarters for selected application",
				module: "Pinjaman",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[91]!.id,
				action: "view",
				resource: "approval status for the application",
				module: "Pinjaman",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[91]!.id,
				action: "download",
				resource: "Surat Tawaran Menduduki Kuarters",
				module: "Pinjaman",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[2]!.id,
				action: "view",
				resource: "and search list of application for quarters that belongs to themselves",
				module: "Pinjaman",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[2]!.id,
				action: "add",
				resource: "application details and supporting documents",
				module: "Pinjaman",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[2]!.id,
				action: "view",
				resource: "application details",
				module: "Pinjaman",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[2]!.id,
				action: "view",
				resource: "the status of verification from 'US Pinjaman'",
				module: "Pinjaman",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[2]!.id,
				action: "view",
				resource: "the status of approval from 'PN'",
				module: "Pinjaman",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[2]!.id,
				action: "download",
				resource: "memo surat and form from the system",
				module: "Pinjaman",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[10]!.id,
				action: "view",
				resource: "and search list of application for 'Keluar Kuarters'",
				module: "Pinjaman",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[10]!.id,
				action: "view",
				resource: "the application details and supporting documents for selected application",
				module: "Pinjaman",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[10]!.id,
				action: "update",
				resource: "the status of verification of the application",
				module: "Pinjaman",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[10]!.id,
				action: "view",
				resource: "the status of approval from 'PN'",
				module: "Pinjaman",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[10]!.id,
				action: "update",
				resource: "the all the details related to quarters",
				module: "Pinjaman",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[15]!.id,
				action: "view",
				resource: "and search list of application for 'Keluar Kuarters'",
				module: "Pinjaman",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[15]!.id,
				action: "view",
				resource: "the application details and supportings documents for selected application",
				module: "Pinjaman",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[15]!.id,
				action: "view",
				resource: "the verification status of the application",
				module: "Pinjaman",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[15]!.id,
				action: "update",
				resource: "the status of approval of the application to either 'LULUS/TIDAK LULUS'",
				module: "Pinjaman",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[91]!.id,
				action: "view",
				resource: "and search list of application for 'Keluar Kuarters'",
				module: "Pinjaman",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[91]!.id,
				action: "view",
				resource: "the application details related to 'Keluar Kuarters'",
				module: "Pinjaman",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[10]!.id,
				action: "view",
				resource: "and search list of application for 'Keluar Kuarters'",
				module: "Pinjaman",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[10]!.id,
				action: "add",
				resource: "application detail for 'Keluar Kuarters'",
				module: "Pinjaman",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[10]!.id,
				action: "download",
				resource: "order letter (Surat Arahan Bayaran Tungggakan)",
				module: "Pinjaman",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[10]!.id,
				action: "update",
				resource: "the selected application details",
				module: "Pinjaman",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[15]!.id,
				action: "view",
				resource: "and search list of application for 'Keluar Kuarters'",
				module: "Pinjaman",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[15]!.id,
				action: "view",
				resource: "the application details for selected application",
				module: "Pinjaman",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[15]!.id,
				action: "view",
				resource: "isArrear status whether is settled or not",
				module: "Pinjaman",
				active: true,
				createdBy: "Admin",
			},
			{
				employeeId: employees![Math.floor(Math.random() *10)].id,
				roleId: roles[15]!.id,
				action: "update",
				resource: "the approval status of the application status",
				module: "Pinjaman",
				active: true,
				createdBy: "Admin",
			},
		])
	}
}
