1. "Unit Bahagian/Negeri" can "view" "senarai permohonan klinik panel". ['Unit Bahagian/Negeri', 'view', 'senarai permohonan klinik panel']
1. "Unit Bahagian/Negeri" can "add" new application and its details for panel clinic. ['Unit Bahagian/Negeri', 'add']
1. "Unit Bahagian/Negeri" can "view" application details for panel clinic. ['Unit Bahagian/Negeri', 'view']
2. "Unit Bahagian/Negeri" can "view" "Status Semakan Permohonan" from 'US'. ['Unit Bahagian/Negeri', 'view', 'Status Semakan Permohonan', 'US']
3. "Unit Bahagian/Negeri" can "view" "Status Pengesahan Permohonan" from 'US'. ['Unit Bahagian/Negeri', 'view', 'Status Pengesahan Permohonan', 'US']
4. "Unit Bahagian/Negeri" can "view" "Status Penyokongan Permohonan" from 'Penyokong'. ['Unit Bahagian/Negeri', 'view', 'Status Penyokongan Permohonan', 'Penyokong']
5. "Unit Bahagian/Negeri" can "view" "Status Pelulusan Permohonan" from 'Pelulus'. ['Unit Bahagian/Negeri', 'view', 'Status Pelulusan Permohonan', 'Pelulus']
6. "Unit Bahagian/Negeri" can "download" the "Cetak Surat Perlantikan Klinik Panel". ['Unit Bahagian/Negeri', 'download', 'Cetak Surat Perlantikan Klinik Panel']
7. "Unit Bahagian/Negeri" can "view" overall status of the applicaton. ['Unit Bahagian/Negeri', 'view']
1. "US" can "view" "senarai permohonan klinik panel". ['US', 'view', 'senarai permohonan klinik panel']
1. "US" can "view" selected application and its details. ['US', 'view']
2. "US" can "verify" the selected application by updating the status to either 'SEMAK/TIDAK SEMAK'. ['US', 'verify', 'SEMAK/TIDAK SEMAK']
3. "US" can "confirm" the selected application by updaing the status to either 'SAH/TIDAK SAH'. ['US', 'confirm', 'SAH/TIDAK SAH']
4. "US" can "update" the name of supporter and approver. ['US', 'update']
5. "US" can "view" the current support status for the application. ['US', 'view']
7. "US" can "download" "surat perlantikan klinik panel". ['US', 'download', 'surat perlantikan klinik panel']
8. "US" can "update" the overall status of the application. ['US', 'update']
1. "Penyokong" can "view" "senarai permohonan klinik panel". ['Penyokong', 'view', 'senarai permohonan klinik panel']
1. "Penyokong" can "view" selected application and its details. ['Penyokong', 'view']
2. "Penyokong" can "view" "Status Semakan Permohonan". ['Penyokong', 'view', 'Status Semakan Permohonan']
3. "Penyokong" can "view" "Status Pengesahan Permohonan". ['Penyokong', 'view', 'Status Pengesahan Permohonan']
4. "Penyokong" can "update" the selected application by updating the status to either 'SOKONG/TIDAK SOKONG'. ['Penyokong', 'update', 'SOKONG/TIDAK SOKONG']
1. "Pelulus" can "view" "senarai permohon klinik panel". ['Pelulus', 'view', 'senarai permohon klinik panel']
1. "Pelulus" can "view" selected application and its details. ['Pelulus', 'view']
2. "Pelulus" can "view" "Status Semakan Permohonan" from 'US'. ['Pelulus', 'view', 'Status Semakan Permohonan', 'US']
3. "Pelulus" can "view" "Status Pengesahan Permohonan" from 'US'. ['Pelulus', 'view', 'Status Pengesahan Permohonan', 'US']
4. "Pelulus" can "view" "Status Penyokong Permohonan" from 'Penyokong'. ['Pelulus', 'view', 'Status Penyokong Permohonan', 'Penyokong']
5. "Pelulus" can "update" the selected application by updating the status to either 'LULUS/TIDAK LULUS'. ['Pelulus', 'update', 'LULUS/TIDAK LULUS']
1. System can "generate" "Surat Tidak Berjaya" and "email" to clinic panel. ['generate', 'Surat Tidak Berjaya', 'email']
2. System can "generate" "Surat Perlantikan Klinik Panel" and "email" to clinic panel. ['generate', 'Surat Perlantikan Klinik Panel', 'email']
3. System can "update" "maklumat klinik". ['update', 'maklumat klinik']
1. "KP" can "view" "Senarai Rekod Bil Tuntutan", only for that particular clinic. ['KP', 'view', 'Senarai Rekod Bil Tuntutan']
1. "KP" can "add" "Borang Bil Tuntutan". ['KP', 'add', 'Borang Bil Tuntutan']
1. "KP" can "view" selected details for bil tuntutan. ['KP', 'view']
2. "KP" can "view" "Status Semakan Permohonan" from 'US'. ['KP', 'view', 'Status Semakan Permohonan', 'US']
3. "KP" can "view" "Status Kelulusan Permohonan" from 'US'. ['KP', 'view', 'Status Kelulusan Permohonan', 'US']
4. "KP" can "edit" selected details for bil tuntutan if the status "TIDAK LULUS" from 'US'. ['KP', 'edit', 'TIDAK LULUS', 'US']
5. "KP" can "view" "Status Penyokongan Permohonan" from 'Penyokong'. ['KP', 'view', 'Status Penyokongan Permohonan', 'Penyokong']
6. "KP" can "view" "Status Pelulusan Permohonan" from 'Pelulus'. ['KP', 'view', 'Status Pelulusan Permohonan', 'Pelulus']
7. "KP" can "view" overall status of the application. ['KP', 'view']
1. "US" can "view" "Senarai Rekod Bil Tuntutan" from all the panel clinic. ['US', 'view', 'Senarai Rekod Bil Tuntutan']
1."US" can "view" "Butiran Rekod Bil Tuntutan" from selected record. ['US', 'view', 'Butiran Rekod Bil Tuntutan']
2."US" can "update" the selected record by updating the status to either 'SEMAK/TIDAK SEMAK'. ['US', 'update', 'SEMAK/TIDAK SEMAK']
3."US" can "update" the selected record by updating the status to either 'LULUS/TIDAK LULUS'. ['US', 'update', 'LULUS/TIDAK LULUS']
4. "US" can "update" the name of the approver and supporter. ['US', 'update']
5. "US" can "view" "Status Penyokongan Permohonan" from 'Penyokong'. ['US', 'view', 'Status Penyokongan Permohonan', 'Penyokong']
6. "US" can "view" "Status Kelulusan Permohonan" from 'Pelulus'. ['US', 'view', 'Status Kelulusan Permohonan', 'Pelulus']
7. "US" can "download" "Mencetak Arahan Bayaran Mengikut Penempatan Kakitangan". ['US', 'download', 'Mencetak Arahan Bayaran Mengikut Penempatan Kakitangan']
8. "US" can "update" the overall status of the application. ['US', 'update']
1. "Penyokong" can "view" "Senarai Rekod Bil Tuntutan" from all the panel clinic. ['Penyokong', 'view', 'Senarai Rekod Bil Tuntutan']
1. "Penyokong" can "view" "Butiran Rekod Bil Tuntutan" from selected record. ['Penyokong', 'view', 'Butiran Rekod Bil Tuntutan']
2. "Penyokong" can "view" "Status Semakan Permohonan" from 'US'. ['Penyokong', 'view', 'Status Semakan Permohonan', 'US']
3. "Penyokong" can "view" "Status Kelulusan Permohonan" from 'US'. ['Penyokong', 'view', 'Status Kelulusan Permohonan', 'US']
4. "Penyokong" can "update" the selected record by updating the status to either 'SOKONG/TIDAK SOKONG'. ['Penyokong', 'update', 'SOKONG/TIDAK SOKONG']
1. "Pelulus" can "view" "Senarai Rekod Bil Tuntutan" from all the panel clinic. ['Pelulus', 'view', 'Senarai Rekod Bil Tuntutan']
1. "Pelulus" can "view" "Butiran Rekod Bil Tuntutan" from selected record. ['Pelulus', 'view', 'Butiran Rekod Bil Tuntutan']
2. "Pelulus" can "view" "Status Semakan Permohonan" from 'US'. ['Pelulus', 'view', 'Status Semakan Permohonan', 'US']
3. "Pelulus" can "view" "Status Kelulusan Permohonan" from 'US'. ['Pelulus', 'view', 'Status Kelulusan Permohonan', 'US']
4. "Pelulus" can "view" "Status Penyokongan Permohonan" from 'Penyokong'. ['Pelulus', 'view', 'Status Penyokongan Permohonan', 'Penyokong']
4. "Pelulus" can "update" the selected record by updating the status to either 'LULUS/TIDAK LULUS'. ['Pelulus', 'update', 'LULUS/TIDAK LULUS']
1. System can "generate" "Arahan Bayaran Mengikut Penempatan Kakitangan". ['generate', 'Arahan Bayaran Mengikut Penempatan Kakitangan']
2. System can "update" "Maklumat Klinik Panel". ['update', 'Maklumat Klinik Panel']
1. "Kakitangan" can "view" "Senarai Permohonan Tuntutan" only for that particular employee. ['Kakitangan', 'view', 'Senarai Permohonan Tuntutan']
1. "Kakitangan" can "add" "Butiran Permohonan Tuntutan". ['Kakitangan', 'add', 'Butiran Permohonan Tuntutan']
2. "Kakitangan" can "upload" "Resit Pembelian Ubat/Klinik". ['Kakitangan', 'upload', 'Resit Pembelian Ubat/Klinik']
1. "Kakitangan" can "view" "Butiran Permohonan Tuntutan" for selected application. ['Kakitangan', 'view', 'Butiran Permohonan Tuntutan']
2. "Kakitangan" can "view" "Resit Pembelian Ubat/Klinik. ['Kakitangan', 'view']
3. "Kakitangan" can "view" "Status Semak Baki Peruntukan Kakitangan". ['Kakitangan', 'view', 'Status Semak Baki Peruntukan Kakitangan']
4. "Kakitangan" can "view" "Status Penyemakan Permohonan" from 'US'. ['Kakitangan', 'view', 'Status Penyemakan Permohonan', 'US']
5. "Kakitangan" can "view" "Status Kelulusan Permohonan" from 'US'. ['Kakitangan', 'view', 'Status Kelulusan Permohonan', 'US']
6. "Kakitangan" can "view" "Status Penyokongan Permohonan" from 'Penyokong'. ['Kakitangan', 'view', 'Status Penyokongan Permohonan', 'Penyokong']
7. "Kakitangan" can "view" "Status Kelulusan Permohonan" from 'Pelulus'. ['Kakitangan', 'view', 'Status Kelulusan Permohonan', 'Pelulus']
8. "Kakitangan" can "view" overall status of the application. ['Kakitangan', 'view']
1. "US" can "view" "Senarai Permohonan Tuntutan" for all employee. ['US', 'view', 'Senarai Permohonan Tuntutan']
1."US" can "view" "Butiran Permohonan Tuntutan" for selected application. ['US', 'view', 'Butiran Permohonan Tuntutan']
2. "US" can "download" "Resit Pembelian Ubat/Klinik". ['US', 'download', 'Resit Pembelian Ubat/Klinik']
3. "US" can "view" "Status Semak Baki Peruntukan Kakitangan". ['US', 'view', 'Status Semak Baki Peruntukan Kakitangan']
4. "US" can "verify" "Status Penyemakan Permohonan" by updating the status to either 'SEMAK/TIDAK SEMAK'. ['US', 'verify', 'Status Penyemakan Permohonan', 'SEMAK/TIDAK SEMAK']
5. "US" can "approve" "Status Kelulusan Permohonan" by updating the status to either 'LULUS/TIDAK LULUS'. ['US', 'approve', 'Status Kelulusan Permohonan', 'LULUS/TIDAK LULUS']
7. "US" can "view" "Status Penyokongan Permohonan" from 'Penyokong'. ['US', 'view', 'Status Penyokongan Permohonan', 'Penyokong']
8. "US" can "view" "Status Kelulusan Permohonan" from 'Pelulus'. ['US', 'view', 'Status Kelulusan Permohonan', 'Pelulus']
9. "US" can "download" payment order to finance department. ['US', 'download']
10."US" can "update" the overall status of the application. ['US', 'update']
1. "Penyokong" can "view" "Senarai Permohonan Tuntutan" for all employee. ['Penyokong', 'view', 'Senarai Permohonan Tuntutan']
1. "Penyokong" can "view" "Butiran Permohonan Tuntutan" for selected application. ['Penyokong', 'view', 'Butiran Permohonan Tuntutan']
2. "Penyokong" can "view" "Resit Pembelian Ubat/Klinik. ['Penyokong', 'view']
3. "Penyokong" can "view" "Status Semak Baki Peruntukan Kakitangan". ['Penyokong', 'view', 'Status Semak Baki Peruntukan Kakitangan']
4. "Penyokong" can "view" "Status Penyemakan Permohonan" from 'US'. ['Penyokong', 'view', 'Status Penyemakan Permohonan', 'US']
5. "Penyokong" can "view" "Status Kelulusan Permohonan" from 'US'. ['Penyokong', 'view', 'Status Kelulusan Permohonan', 'US']
6. "Penyokong" can "update" "Status Penyokongan Permohonan" by updating the status to either 'SOKONG/TIDAK SOKONG'. ['Penyokong', 'update', 'Status Penyokongan Permohonan', 'SOKONG/TIDAK SOKONG']
1."Pelulus" can "view" "Senarai Permohonan Tuntutan" for all employee. ['Pelulus', 'view', 'Senarai Permohonan Tuntutan']
1. "Pelulus" can "view" "Butiran Permohonan Tuntutan" for selected application. ['Pelulus', 'view', 'Butiran Permohonan Tuntutan']
2. "Pelulus" can "view" "Resit Pembelian Ubat/Klinik. ['Pelulus', 'view']
3. "Pelulus" can "view" "Status Semak Baki Peruntukan Kakitangan". ['Pelulus', 'view', 'Status Semak Baki Peruntukan Kakitangan']
4. "Pelulus" can "view" "Status Penyemakan Permohonan" from 'US'. ['Pelulus', 'view', 'Status Penyemakan Permohonan', 'US']
5. "Pelulus" can "view" "Status Kelulusan Permohonan" from 'US'. ['Pelulus', 'view', 'Status Kelulusan Permohonan', 'US']
6. "Pelulus" can "view" "Status Penyokongan Permohonan" from 'Penyokong'. ['Pelulus', 'view', 'Status Penyokongan Permohonan', 'Penyokong']
7. "Pelulus" can "update" "Status Kelulusan Permohonan" by updating the status to either 'LULUS/TIDAK LULUS'. ['Pelulus', 'update', 'Status Kelulusan Permohonan', 'LULUS/TIDAK LULUS']
2. System "generate" payment order to finance department. ['generate']
3. System "update" "Butiran Kakitangan". ['update', 'Butiran Kakitangan']
1. System "update" salary details for the employee by 'generate" "arahan penolakan gaji". ['update', ' ']
1. "Kakitangan" can "view" "Baki Perubatan Kakitangan". ['Kakitangan', 'view', 'Baki Perubatan Kakitangan']
2."Kakitangan" can "download" "surat melebihi had penggunaan perubatan tahunan". ['Kakitangan', 'download', 'surat melebihi had penggunaan perubatan tahunan']
3. "Kakitangan" can "download" "arahan penolakan gaji". ['Kakitangan', 'download', 'arahan penolakan gaji']
4. "Kakitangan" can "upload" "Bukti Pembayaran". ['Kakitangan', 'upload', 'Bukti Pembayaran']
5. "Kakitangan" can "view" "Semak Pengesahan Bukti Pembayaran". ['Kakitangan', 'view', 'Semak Pengesahan Bukti Pembayaran']
6. "Kakitangan" can re-"upload" "Butki Pembayaran" and repeat the same process. ['Kakitangan', 'upload', 'Butki Pembayaran']
7. "Kakitangan" can "view" updated "Baki Perubatan Kakitangan". ['Kakitangan', 'view', 'Baki Perubatan Kakitangan']
1. "US" can "view" "Senarai Kakitangan Yang Melebihi Kuota". ['US', 'view', 'Senarai Kakitangan Yang Melebihi Kuota']
1. "US" can "view" details of selected employee. ['US', 'view']
2. "US" can "view" if which payment the employee wanted. ['US', 'view']
3. "US" can "download" uploaded "Bukti Pembayaran" from the employee. ['US', 'download', 'Bukti Pembayaran']
4. "US" can "confirm" the "Bukti Pembayaran" by updating the status to either 'SAH/TIDAK SAH'. ['US', 'confirm', 'Bukti Pembayaran', 'SAH/TIDAK SAH']
5. "US" can "update" updated "Baki Perubatan Kakitangan" which should not be over budget anymore. ['US', 'update', 'Baki Perubatan Kakitangan']
6. "US" can "update" record where that particular record no longer over budget. ['US', 'update']
			},
		])
	}
}
